//This file is part of AudioCuesheetEditor.

//AudioCuesheetEditor is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.

//AudioCuesheetEditor is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with Foobar.  If not, see
//<http: //www.gnu.org/licenses />.
using AudioCuesheetEditor.End2EndTests.Models;
using Microsoft.Playwright;

namespace AudioCuesheetEditor.End2EndTests.Tests.Desktop
{
    [TestClass]
    public class ImportTest : PlaywrightTestBase
    {
        [TestMethod]
        public async Task Import_ShouldImportTracks_WhenUsingSampleInputfile()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            var detailView = new DetailView(TestPage);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Sample_Inputfile.txt");
            await importView.Analyze();
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Artist Title Begin End Length Status"":
      - columnheader:
        - checkbox
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Increment Decrement Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Increment Decrement Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
      - cell:
        - button
  - rowgroup:
    - row");
            await Expect(detailView.AudiofileInput).ToBeEmptyAsync();
            await importView.GotoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Button, new() { Name = "Analyze" })).ToBeVisibleAsync();
        }

        [TestMethod]
        public async Task Import_ShouldBeEditable_WhenEditingTrack()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Sample_Inputfile.txt");
            await importView.Analyze();
            await importView.SelectTracksAsync([5]);
            await importView.EditTracksModalAsync("Sample Title Edited 5");
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Artist Title Begin End Length Status"":
      - columnheader:
        - checkbox
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Increment Decrement Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Increment Decrement Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 5 Clear Sample Title Edited 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title Edited 5 Clear"":
        - textbox: Sample Title Edited 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
      - cell:
        - button
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WithSpecialTextfile()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Textimport-Bug-#54.txt");
            await importView.SwitchImportProfileAsync("Textfile (just track data)");
            await importView.Analyze();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync("- table:\r\n  - rowgroup:\r\n    - row \"# Artist Title Begin End Length\":\r\n      - columnheader:\r\n        - checkbox\r\n      - columnheader \"#\"\r\n      - columnheader \"Artist\"\r\n      - columnheader \"Title\"\r\n      - columnheader \"Begin\"\r\n      - columnheader \"End\"\r\n      - columnheader \"Length\"\r\n  - rowgroup:\r\n    - row \"Increment Decrement Adriatique Clear X. Clear 00:00:00 00:05:24 00:05:24\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"1\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Adriatique Clear\":\r\n        - textbox: Adriatique\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"X. Clear\":\r\n        - textbox: X.\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:00:00\":\r\n        - textbox: 00:00:00\r\n      - cell \"00:05:24\":\r\n        - textbox: 00:05:24\r\n      - cell \"00:05:24\":\r\n        - textbox: 00:05:24\r\n    - row \"Increment Decrement Third Harmony Clear Fears And Dreams (Original Mix) Clear 00:05:24 00:10:39 00:05:15\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"2\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Third Harmony Clear\":\r\n        - textbox: Third Harmony\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Fears And Dreams (Original Mix) Clear\":\r\n        - textbox: Fears And Dreams (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:05:24\":\r\n        - textbox: 00:05:24\r\n      - cell \"00:10:39\":\r\n        - textbox: 00:10:39\r\n      - cell \"00:05:15\":\r\n        - textbox: 00:05:15\r\n    - row \"Increment Decrement Dele Sosimi Afrobeat Orchestra Clear Too Much Information (Laolu Remix; Edit) Clear 00:10:39 00:17:06 00:06:27\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"3\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Dele Sosimi Afrobeat Orchestra Clear\":\r\n        - textbox: Dele Sosimi Afrobeat Orchestra\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Too Much Information (Laolu Remix; Edit) Clear\":\r\n        - textbox: Too Much Information (Laolu Remix; Edit)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:10:39\":\r\n        - textbox: 00:10:39\r\n      - cell \"00:17:06\":\r\n        - textbox: 00:17:06\r\n      - cell \"00:06:27\":\r\n        - textbox: 00:06:27\r\n    - row \"Increment Decrement Edem, Govan Clear Ankh (Onetwo MX Remix) Clear 00:17:06 00:23:21 00:06:15\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"4\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Edem, Govan Clear\":\r\n        - textbox: Edem, Govan\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Ankh (Onetwo MX Remix) Clear\":\r\n        - textbox: Ankh (Onetwo MX Remix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:17:06\":\r\n        - textbox: 00:17:06\r\n      - cell \"00:23:21\":\r\n        - textbox: 00:23:21\r\n      - cell \"00:06:15\":\r\n        - textbox: 00:06:15\r\n    - row \"Increment Decrement Jody Wisternoff Clear For All Time (feat. Hendrik Burkhard) (Extended Mix) Clear 00:23:21 00:29:02 00:05:41\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"5\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Jody Wisternoff Clear\":\r\n        - textbox: Jody Wisternoff\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"For All Time (feat. Hendrik Burkhard) (Extended Mix) Clear\":\r\n        - textbox: For All Time (feat. Hendrik Burkhard) (Extended Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:23:21\":\r\n        - textbox: 00:23:21\r\n      - cell \"00:29:02\":\r\n        - textbox: 00:29:02\r\n      - cell \"00:05:41\":\r\n        - textbox: 00:05:41\r\n    - row \"Increment Decrement Einmusik Clear Bead (Original Mix) Clear 00:29:02 00:34:27 00:05:25\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"6\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Einmusik Clear\":\r\n        - textbox: Einmusik\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Bead (Original Mix) Clear\":\r\n        - textbox: Bead (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:29:02\":\r\n        - textbox: 00:29:02\r\n      - cell \"00:34:27\":\r\n        - textbox: 00:34:27\r\n      - cell \"00:05:25\":\r\n        - textbox: 00:05:25\r\n    - row \"Increment Decrement Sebastien Leger Clear La Danse du Scorpion Clear 00:34:27 00:40:59 00:06:32\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"7\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Sebastien Leger Clear\":\r\n        - textbox: Sebastien Leger\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"La Danse du Scorpion Clear\":\r\n        - textbox: La Danse du Scorpion\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:34:27\":\r\n        - textbox: 00:34:27\r\n      - cell \"00:40:59\":\r\n        - textbox: 00:40:59\r\n      - cell \"00:06:32\":\r\n        - textbox: 00:06:32\r\n    - row \"Increment Decrement Paul Thomas & Solid Stone Clear La Bombo (Solid Stone Remix) Clear 00:40:59 00:46:19 00:05:20\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"8\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Paul Thomas & Solid Stone Clear\":\r\n        - textbox: Paul Thomas & Solid Stone\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"La Bombo (Solid Stone Remix) Clear\":\r\n        - textbox: La Bombo (Solid Stone Remix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:40:59\":\r\n        - textbox: 00:40:59\r\n      - cell \"00:46:19\":\r\n        - textbox: 00:46:19\r\n      - cell \"00:05:20\":\r\n        - textbox: 00:05:20\r\n    - row \"Increment Decrement GusGus Clear Crossfade (Maceo Plex Mix) Clear 00:46:19 00:52:20 00:06:01\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"9\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"GusGus Clear\":\r\n        - textbox: GusGus\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Crossfade (Maceo Plex Mix) Clear\":\r\n        - textbox: Crossfade (Maceo Plex Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:46:19\":\r\n        - textbox: 00:46:19\r\n      - cell \"00:52:20\":\r\n        - textbox: 00:52:20\r\n      - cell \"00:06:01\":\r\n        - textbox: 00:06:01\r\n    - row \"Increment Decrement Klangkarussell Clear Time (Original Mix) Clear 00:52:20 00:56:19 00:03:59\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"10\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Klangkarussell Clear\":\r\n        - textbox: Klangkarussell\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Time (Original Mix) Clear\":\r\n        - textbox: Time (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:52:20\":\r\n        - textbox: 00:52:20\r\n      - cell \"00:56:19\":\r\n        - textbox: 00:56:19\r\n      - cell \"00:03:59\":\r\n        - textbox: 00:03:59\r\n    - row \"Increment Decrement Anysense & Un:said Clear Missing Path (Original Mix) Clear 00:56:19 01:01:41 00:05:22\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"11\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Anysense & Un:said Clear\":\r\n        - textbox: Anysense & Un:said\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Missing Path (Original Mix) Clear\":\r\n        - textbox: Missing Path (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"00:56:19\":\r\n        - textbox: 00:56:19\r\n      - cell \"01:01:41\":\r\n        - textbox: 01:01:41\r\n      - cell \"00:05:22\":\r\n        - textbox: 00:05:22\r\n    - row \"Increment Decrement Space Food Clear Bombay Clear 01:01:41 01:06:33 00:04:52\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"12\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Space Food Clear\":\r\n        - textbox: Space Food\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Bombay Clear\":\r\n        - textbox: Bombay\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:01:41\":\r\n        - textbox: 01:01:41\r\n      - cell \"01:06:33\":\r\n        - textbox: 01:06:33\r\n      - cell \"00:04:52\":\r\n        - textbox: 00:04:52\r\n    - row \"Increment Decrement SHDW & Obscure Shape Clear Wächter der Nacht (Original Mix) Clear 01:06:33 01:11:04 00:04:31\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"13\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"SHDW & Obscure Shape Clear\":\r\n        - textbox: SHDW & Obscure Shape\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Wächter der Nacht (Original Mix) Clear\":\r\n        - textbox: Wächter der Nacht (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:06:33\":\r\n        - textbox: 01:06:33\r\n      - cell \"01:11:04\":\r\n        - textbox: 01:11:04\r\n      - cell \"00:04:31\":\r\n        - textbox: 00:04:31\r\n    - row \"Increment Decrement HOSH Clear Karma Clear 01:11:04 01:15:28 00:04:24\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"14\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"HOSH Clear\":\r\n        - textbox: HOSH\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Karma Clear\":\r\n        - textbox: Karma\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:11:04\":\r\n        - textbox: 01:11:04\r\n      - cell \"01:15:28\":\r\n        - textbox: 01:15:28\r\n      - cell \"00:04:24\":\r\n        - textbox: 00:04:24\r\n    - row \"Increment Decrement Alexey Union Clear Olympia (Original Mix) Clear 01:15:28 01:21:08 00:05:40\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"15\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Alexey Union Clear\":\r\n        - textbox: Alexey Union\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Olympia (Original Mix) Clear\":\r\n        - textbox: Olympia (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:15:28\":\r\n        - textbox: 01:15:28\r\n      - cell \"01:21:08\":\r\n        - textbox: 01:21:08\r\n      - cell \"00:05:40\":\r\n        - textbox: 00:05:40\r\n    - row \"Increment Decrement Paul Taylor Clear Afterglow Clear 01:21:08 01:25:38 00:04:30\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"16\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Paul Taylor Clear\":\r\n        - textbox: Paul Taylor\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Afterglow Clear\":\r\n        - textbox: Afterglow\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:21:08\":\r\n        - textbox: 01:21:08\r\n      - cell \"01:25:38\":\r\n        - textbox: 01:25:38\r\n      - cell \"00:04:30\":\r\n        - textbox: 00:04:30\r\n    - row \"Increment Decrement Philter Clear Stranger Clear 01:25:38 01:31:52 00:06:14\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"17\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Philter Clear\":\r\n        - textbox: Philter\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Stranger Clear\":\r\n        - textbox: Stranger\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:25:38\":\r\n        - textbox: 01:25:38\r\n      - cell \"01:31:52\":\r\n        - textbox: 01:31:52\r\n      - cell \"00:06:14\":\r\n        - textbox: 00:06:14\r\n    - row \"Increment Decrement Skizologic Clear Hypersphere (Original Mix) Clear 01:31:52 01:36:40 00:04:48\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"18\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Skizologic Clear\":\r\n        - textbox: Skizologic\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Hypersphere (Original Mix) Clear\":\r\n        - textbox: Hypersphere (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:31:52\":\r\n        - textbox: 01:31:52\r\n      - cell \"01:36:40\":\r\n        - textbox: 01:36:40\r\n      - cell \"00:04:48\":\r\n        - textbox: 00:04:48\r\n    - row \"Increment Decrement Thomas Schumacher, Caitlin Clear All of You (Remix) Clear 01:36:40 01:42:16 00:05:36\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"19\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Thomas Schumacher, Caitlin Clear\":\r\n        - textbox: Thomas Schumacher, Caitlin\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"All of You (Remix) Clear\":\r\n        - textbox: All of You (Remix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:36:40\":\r\n        - textbox: 01:36:40\r\n      - cell \"01:42:16\":\r\n        - textbox: 01:42:16\r\n      - cell \"00:05:36\":\r\n        - textbox: 00:05:36\r\n    - row \"Increment Decrement A. Skomoroh Clear White Horse Conquest (Original Mix) Clear 01:42:16 01:47:04 00:04:48\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"20\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"A. Skomoroh Clear\":\r\n        - textbox: A. Skomoroh\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"White Horse Conquest (Original Mix) Clear\":\r\n        - textbox: White Horse Conquest (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:42:16\":\r\n        - textbox: 01:42:16\r\n      - cell \"01:47:04\":\r\n        - textbox: 01:47:04\r\n      - cell \"00:04:48\":\r\n        - textbox: 00:04:48\r\n    - row \"Increment Decrement Patrik Berg Clear Bright (Original Mix) Clear 01:47:04 01:52:37 00:05:33\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"21\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Patrik Berg Clear\":\r\n        - textbox: Patrik Berg\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Bright (Original Mix) Clear\":\r\n        - textbox: Bright (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:47:04\":\r\n        - textbox: 01:47:04\r\n      - cell \"01:52:37\":\r\n        - textbox: 01:52:37\r\n      - cell \"00:05:33\":\r\n        - textbox: 00:05:33\r\n    - row \"Increment Decrement Hidden Empire Clear Bengal Clear 01:52:37 01:58:05 00:05:28\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"22\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Hidden Empire Clear\":\r\n        - textbox: Hidden Empire\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Bengal Clear\":\r\n        - textbox: Bengal\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:52:37\":\r\n        - textbox: 01:52:37\r\n      - cell \"01:58:05\":\r\n        - textbox: 01:58:05\r\n      - cell \"00:05:28\":\r\n        - textbox: 00:05:28\r\n    - row \"Increment Decrement Mario Ochoa Clear Levitate Clear 01:58:05 02:03:00 00:04:55\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"23\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Mario Ochoa Clear\":\r\n        - textbox: Mario Ochoa\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Levitate Clear\":\r\n        - textbox: Levitate\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"01:58:05\":\r\n        - textbox: 01:58:05\r\n      - cell \"02:03:00\":\r\n        - textbox: 02:03:00\r\n      - cell \"00:04:55\":\r\n        - textbox: 00:04:55\r\n    - row \"Increment Decrement Raul Facio Clear Eyes Wide Shut (Original Mix) Clear 02:03:00 02:08:21 00:05:21\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"24\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Raul Facio Clear\":\r\n        - textbox: Raul Facio\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Eyes Wide Shut (Original Mix) Clear\":\r\n        - textbox: Eyes Wide Shut (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:03:00\":\r\n        - textbox: 02:03:00\r\n      - cell \"02:08:21\":\r\n        - textbox: 02:08:21\r\n      - cell \"00:05:21\":\r\n        - textbox: 00:05:21\r\n    - row \"Increment Decrement Soolver Clear Regular (Original Mix) Clear 02:08:21 02:14:31 00:06:10\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"25\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Soolver Clear\":\r\n        - textbox: Soolver\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Regular (Original Mix) Clear\":\r\n        - textbox: Regular (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:08:21\":\r\n        - textbox: 02:08:21\r\n      - cell \"02:14:31\":\r\n        - textbox: 02:14:31\r\n      - cell \"00:06:10\":\r\n        - textbox: 00:06:10\r\n    - row \"Increment Decrement Weska Clear EQ64 (Original Mix) Clear 02:14:31 02:18:35 00:04:04\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"26\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Weska Clear\":\r\n        - textbox: Weska\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"EQ64 (Original Mix) Clear\":\r\n        - textbox: EQ64 (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:14:31\":\r\n        - textbox: 02:14:31\r\n      - cell \"02:18:35\":\r\n        - textbox: 02:18:35\r\n      - cell \"00:04:04\":\r\n        - textbox: 00:04:04\r\n    - row \"Increment Decrement Tempo Giusto Clear The Fall (Extended Mix) Clear 02:18:35 02:24:12 00:05:37\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"27\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Tempo Giusto Clear\":\r\n        - textbox: Tempo Giusto\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"The Fall (Extended Mix) Clear\":\r\n        - textbox: The Fall (Extended Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:18:35\":\r\n        - textbox: 02:18:35\r\n      - cell \"02:24:12\":\r\n        - textbox: 02:24:12\r\n      - cell \"00:05:37\":\r\n        - textbox: 00:05:37\r\n    - row \"Increment Decrement Vlind & Asteroid & Gary Leroy Clear Trinity (Extended Mix) Clear 02:24:12 02:29:38 00:05:26\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"28\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Vlind & Asteroid & Gary Leroy Clear\":\r\n        - textbox: Vlind & Asteroid & Gary Leroy\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Trinity (Extended Mix) Clear\":\r\n        - textbox: Trinity (Extended Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:24:12\":\r\n        - textbox: 02:24:12\r\n      - cell \"02:29:38\":\r\n        - textbox: 02:29:38\r\n      - cell \"00:05:26\":\r\n        - textbox: 00:05:26\r\n    - row \"Increment Decrement Astral Legacy Clear Vaveyla (Original Mix) Clear 02:29:38 02:32:52 00:03:14\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"29\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Astral Legacy Clear\":\r\n        - textbox: Astral Legacy\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Vaveyla (Original Mix) Clear\":\r\n        - textbox: Vaveyla (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:29:38\":\r\n        - textbox: 02:29:38\r\n      - cell \"02:32:52\":\r\n        - textbox: 02:32:52\r\n      - cell \"00:03:14\":\r\n        - textbox: 00:03:14\r\n    - row \"Increment Decrement Gerrox Clear Chakra (Original Mix) Clear 02:32:52 02:37:00 00:04:08\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"30\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Gerrox Clear\":\r\n        - textbox: Gerrox\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Chakra (Original Mix) Clear\":\r\n        - textbox: Chakra (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:32:52\":\r\n        - textbox: 02:32:52\r\n      - cell \"02:37:00\":\r\n        - textbox: 02:37:00\r\n      - cell \"00:04:08\":\r\n        - textbox: 00:04:08\r\n    - row \"Increment Decrement Charlotte De Witte Clear Pattern Clear 02:37:00 02:41:55 00:04:55\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"31\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Charlotte De Witte Clear\":\r\n        - textbox: Charlotte De Witte\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Pattern Clear\":\r\n        - textbox: Pattern\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:37:00\":\r\n        - textbox: 02:37:00\r\n      - cell \"02:41:55\":\r\n        - textbox: 02:41:55\r\n      - cell \"00:04:55\":\r\n        - textbox: 00:04:55\r\n    - row \"Increment Decrement Space Food Clear Amabey Clear 02:41:55 02:46:55 00:05:00\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"32\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Space Food Clear\":\r\n        - textbox: Space Food\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Amabey Clear\":\r\n        - textbox: Amabey\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:41:55\":\r\n        - textbox: 02:41:55\r\n      - cell \"02:46:55\":\r\n        - textbox: 02:46:55\r\n      - cell \"00:05:00\":\r\n        - textbox: 00:05:00\r\n    - row \"Increment Decrement ARTBAT Clear Papilion (Original Mix) Clear 02:46:55 02:51:13 00:04:18\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"33\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"ARTBAT Clear\":\r\n        - textbox: ARTBAT\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Papilion (Original Mix) Clear\":\r\n        - textbox: Papilion (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:46:55\":\r\n        - textbox: 02:46:55\r\n      - cell \"02:51:13\":\r\n        - textbox: 02:51:13\r\n      - cell \"00:04:18\":\r\n        - textbox: 00:04:18\r\n    - row \"Increment Decrement PETER PAHN Clear Enjoy Infinity (Original Mix) Clear 02:51:13 02:56:08 00:04:55\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"34\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"PETER PAHN Clear\":\r\n        - textbox: PETER PAHN\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Enjoy Infinity (Original Mix) Clear\":\r\n        - textbox: Enjoy Infinity (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:51:13\":\r\n        - textbox: 02:51:13\r\n      - cell \"02:56:08\":\r\n        - textbox: 02:56:08\r\n      - cell \"00:04:55\":\r\n        - textbox: 00:04:55\r\n    - row \"Increment Decrement Solitek Clear Instinct (Original Mix) Clear 02:56:08 03:00:57 00:04:49\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"35\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Solitek Clear\":\r\n        - textbox: Solitek\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Instinct (Original Mix) Clear\":\r\n        - textbox: Instinct (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"02:56:08\":\r\n        - textbox: 02:56:08\r\n      - cell \"03:00:57\":\r\n        - textbox: 03:00:57\r\n      - cell \"00:04:49\":\r\n        - textbox: 00:04:49\r\n    - row \"Increment Decrement Veerus Clear Heavy Clear 03:00:57 03:05:19 00:04:22\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"36\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Veerus Clear\":\r\n        - textbox: Veerus\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Heavy Clear\":\r\n        - textbox: Heavy\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"03:00:57\":\r\n        - textbox: 03:00:57\r\n      - cell \"03:05:19\":\r\n        - textbox: 03:05:19\r\n      - cell \"00:04:22\":\r\n        - textbox: 00:04:22\r\n    - row \"Increment Decrement Secret Cinema & Reinier Zonneveld Clear Pain Thing (Original Mix) Clear 03:05:19 03:09:38 00:04:19\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"37\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Secret Cinema & Reinier Zonneveld Clear\":\r\n        - textbox: Secret Cinema & Reinier Zonneveld\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Pain Thing (Original Mix) Clear\":\r\n        - textbox: Pain Thing (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"03:05:19\":\r\n        - textbox: 03:05:19\r\n      - cell \"03:09:38\":\r\n        - textbox: 03:09:38\r\n      - cell \"00:04:19\":\r\n        - textbox: 00:04:19\r\n    - row \"Increment Decrement Amelie Lens Clear Hypnotized Clear 03:09:38 03:13:13 00:03:35\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"38\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Amelie Lens Clear\":\r\n        - textbox: Amelie Lens\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Hypnotized Clear\":\r\n        - textbox: Hypnotized\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"03:09:38\":\r\n        - textbox: 03:09:38\r\n      - cell \"03:13:13\":\r\n        - textbox: 03:13:13\r\n      - cell \"00:03:35\":\r\n        - textbox: 00:03:35\r\n    - row \"Increment Decrement Nikolay Kirov Clear Chasing the Sun (Original Mix) Clear 03:13:13\":\r\n      - cell:\r\n        - checkbox\r\n      - cell \"Increment Decrement\":\r\n        - spinbutton: \"39\"\r\n        - button \"Increment\"\r\n        - button \"Decrement\"\r\n      - cell \"Nikolay Kirov Clear\":\r\n        - textbox: Nikolay Kirov\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"Chasing the Sun (Original Mix) Clear\":\r\n        - textbox: Chasing the Sun (Original Mix)\r\n        - button \"Clear\"\r\n        - button\r\n      - cell \"03:13:13\":\r\n        - textbox: 03:13:13\r\n      - cell:\r\n        - textbox\r\n      - cell:\r\n        - textbox\r\n  - rowgroup:\r\n    - row");
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WhenUsingSampleInputfile2()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Sample_Inputfile2.txt");
            await importView.ClearSchemeCommonDataAsync();
            await importView.Analyze();
            await Expect(importView.CuesheetArtistInput).ToBeEmptyAsync();
            await Expect(importView.CuesheetTitleInput).ToBeEmptyAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Artist Title Begin End Length"":
      - columnheader:
        - checkbox
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
  - rowgroup:
    - row ""Increment Decrement Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
    - row ""Increment Decrement Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
    - row ""Increment Decrement Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
    - row ""Increment Decrement Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
    - row ""Increment Decrement Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
    - row ""Increment Decrement Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
    - row ""Increment Decrement Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
    - row ""Increment Decrement Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WithTraktorOutput()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Traktor Export.html");
            await importView.SwitchImportProfileAsync("Traktor history");
            await importView.Analyze();
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Artist Title Begin End Length Status"":
      - columnheader:
        - checkbox
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Increment Decrement Nachap Clear Glass Clear 00:00:00 00:11:56 00:11:56"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Nachap Clear"":
        - textbox: Nachap
        - button ""Clear""
        - button
      - cell ""Glass Clear"":
        - textbox: Glass
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:11:56"":
        - textbox: 00:11:56
      - cell ""00:11:56"":
        - textbox: 00:11:56
      - cell
    - row ""Increment Decrement Progressive + Melodic DECK Clear 00:11:56 00:13:31 00:01:35"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell:
        - textbox
        - button
      - cell ""Progressive + Melodic DECK Clear"":
        - textbox: Progressive + Melodic DECK
        - button ""Clear""
        - button
      - cell ""00:11:56"":
        - textbox: 00:11:56
      - cell ""00:13:31"":
        - textbox: 00:13:31
      - cell ""00:01:35"":
        - textbox: 00:01:35
      - cell:
        - button
    - row ""Increment Decrement Nomer 21 Clear Depersonalization Clear 00:13:31 00:19:14 00:05:43"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Nomer 21 Clear"":
        - textbox: Nomer 21
        - button ""Clear""
        - button
      - cell ""Depersonalization Clear"":
        - textbox: Depersonalization
        - button ""Clear""
        - button
      - cell ""00:13:31"":
        - textbox: 00:13:31
      - cell ""00:19:14"":
        - textbox: 00:19:14
      - cell ""00:05:43"":
        - textbox: 00:05:43
      - cell:
        - button
    - row ""Increment Decrement SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear Showing Off Clear 00:19:14 00:24:02 00:04:48"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear"":
        - textbox: SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay
        - button ""Clear""
        - button
      - cell ""Showing Off Clear"":
        - textbox: Showing Off
        - button ""Clear""
        - button
      - cell ""00:19:14"":
        - textbox: 00:19:14
      - cell ""00:24:02"":
        - textbox: 00:24:02
      - cell ""00:04:48"":
        - textbox: 00:04:48
      - cell:
        - button
    - row ""Increment Decrement Carlo Whale Clear Unconscious Clear 00:24:02 00:29:37 00:05:35"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Carlo Whale Clear"":
        - textbox: Carlo Whale
        - button ""Clear""
        - button
      - cell ""Unconscious Clear"":
        - textbox: Unconscious
        - button ""Clear""
        - button
      - cell ""00:24:02"":
        - textbox: 00:24:02
      - cell ""00:29:37"":
        - textbox: 00:29:37
      - cell ""00:05:35"":
        - textbox: 00:05:35
      - cell:
        - button
    - row ""Increment Decrement Arba Han Clear Timelaps Clear 00:29:37 00:33:13 00:03:36"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Arba Han Clear"":
        - textbox: Arba Han
        - button ""Clear""
        - button
      - cell ""Timelaps Clear"":
        - textbox: Timelaps
        - button ""Clear""
        - button
      - cell ""00:29:37"":
        - textbox: 00:29:37
      - cell ""00:33:13"":
        - textbox: 00:33:13
      - cell ""00:03:36"":
        - textbox: 00:03:36
      - cell:
        - button
    - row ""Increment Decrement Savill Clear Energy Surrounds Clear 00:33:13 00:40:30 00:07:17"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Savill Clear"":
        - textbox: Savill
        - button ""Clear""
        - button
      - cell ""Energy Surrounds Clear"":
        - textbox: Energy Surrounds
        - button ""Clear""
        - button
      - cell ""00:33:13"":
        - textbox: 00:33:13
      - cell ""00:40:30"":
        - textbox: 00:40:30
      - cell ""00:07:17"":
        - textbox: 00:07:17
      - cell:
        - button
    - row ""Increment Decrement Teklix Clear The Tribal Code Clear 00:40:30 00:48:53 00:08:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Teklix Clear"":
        - textbox: Teklix
        - button ""Clear""
        - button
      - cell ""The Tribal Code Clear"":
        - textbox: The Tribal Code
        - button ""Clear""
        - button
      - cell ""00:40:30"":
        - textbox: 00:40:30
      - cell ""00:48:53"":
        - textbox: 00:48:53
      - cell ""00:08:23"":
        - textbox: 00:08:23
      - cell:
        - button
    - row ""Increment Decrement Neuralis Clear I'm Looking for Answers Clear 00:48:53 00:54:34 00:05:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""9""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Neuralis Clear"":
        - textbox: Neuralis
        - button ""Clear""
        - button
      - cell ""I'm Looking for Answers Clear"":
        - textbox: I'm Looking for Answers
        - button ""Clear""
        - button
      - cell ""00:48:53"":
        - textbox: 00:48:53
      - cell ""00:54:34"":
        - textbox: 00:54:34
      - cell ""00:05:41"":
        - textbox: 00:05:41
      - cell:
        - button
    - row ""Increment Decrement Nopopstar &amp; Arsia Clear Dirty Moves Clear 00:54:34 01:00:24 00:05:50"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""10""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Nopopstar &amp; Arsia Clear"":
        - textbox: Nopopstar &amp; Arsia
        - button ""Clear""
        - button
      - cell ""Dirty Moves Clear"":
        - textbox: Dirty Moves
        - button ""Clear""
        - button
      - cell ""00:54:34"":
        - textbox: 00:54:34
      - cell ""01:00:24"":
        - textbox: 01:00:24
      - cell ""00:05:50"":
        - textbox: 00:05:50
      - cell:
        - button
    - row ""Increment Decrement SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear Lost (Maze 28 Remix) Clear 01:00:24 01:05:17 00:04:53"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""11""
        - button ""Increment""
        - button ""Decrement""
      - cell ""SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear"":
        - textbox: SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay
        - button ""Clear""
        - button
      - cell ""Lost (Maze 28 Remix) Clear"":
        - textbox: Lost (Maze 28 Remix)
        - button ""Clear""
        - button
      - cell ""01:00:24"":
        - textbox: 01:00:24
      - cell ""01:05:17"":
        - textbox: 01:05:17
      - cell ""00:04:53"":
        - textbox: 00:04:53
      - cell:
        - button
    - row ""Increment Decrement SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear Lost (Redspace Remix) Clear 01:05:17 01:08:22 00:03:05"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""12""
        - button ""Increment""
        - button ""Decrement""
      - cell ""SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear"":
        - textbox: SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay
        - button ""Clear""
        - button
      - cell ""Lost (Redspace Remix) Clear"":
        - textbox: Lost (Redspace Remix)
        - button ""Clear""
        - button
      - cell ""01:05:17"":
        - textbox: 01:05:17
      - cell ""01:08:22"":
        - textbox: 01:08:22
      - cell ""00:03:05"":
        - textbox: 00:03:05
      - cell:
        - button
    - row ""Increment Decrement Gadoz Clear 5d Clear 01:08:22 01:16:34 00:08:12"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""13""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Gadoz Clear"":
        - textbox: Gadoz
        - button ""Clear""
        - button
      - cell ""5d Clear"":
        - textbox: 5d
        - button ""Clear""
        - button
      - cell ""01:08:22"":
        - textbox: 01:08:22
      - cell ""01:16:34"":
        - textbox: 01:16:34
      - cell ""00:08:12"":
        - textbox: 00:08:12
      - cell:
        - button
    - row ""Increment Decrement DJ Danzik Clear Out of Space Clear 01:16:34 01:19:22 00:02:48"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""14""
        - button ""Increment""
        - button ""Decrement""
      - cell ""DJ Danzik Clear"":
        - textbox: DJ Danzik
        - button ""Clear""
        - button
      - cell ""Out of Space Clear"":
        - textbox: Out of Space
        - button ""Clear""
        - button
      - cell ""01:16:34"":
        - textbox: 01:16:34
      - cell ""01:19:22"":
        - textbox: 01:19:22
      - cell ""00:02:48"":
        - textbox: 00:02:48
      - cell:
        - button
    - row ""Increment Decrement Enis Çoban Clear Internet Clear 01:19:22 01:25:14 00:05:52"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""15""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Enis Çoban Clear"":
        - textbox: Enis Çoban
        - button ""Clear""
        - button
      - cell ""Internet Clear"":
        - textbox: Internet
        - button ""Clear""
        - button
      - cell ""01:19:22"":
        - textbox: 01:19:22
      - cell ""01:25:14"":
        - textbox: 01:25:14
      - cell ""00:05:52"":
        - textbox: 00:05:52
      - cell:
        - button
    - row ""Increment Decrement Cold Mind &amp; Alex Yikker Clear Rage Clear 01:25:14 01:31:33 00:06:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""16""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Cold Mind &amp; Alex Yikker Clear"":
        - textbox: Cold Mind &amp; Alex Yikker
        - button ""Clear""
        - button
      - cell ""Rage Clear"":
        - textbox: Rage
        - button ""Clear""
        - button
      - cell ""01:25:14"":
        - textbox: 01:25:14
      - cell ""01:31:33"":
        - textbox: 01:31:33
      - cell ""00:06:19"":
        - textbox: 00:06:19
      - cell:
        - button
    - row ""Increment Decrement Maze 28 Clear Sol (JAHAYA Remix) Clear 01:31:33 01:32:51 00:01:18"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""17""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Maze 28 Clear"":
        - textbox: Maze 28
        - button ""Clear""
        - button
      - cell ""Sol (JAHAYA Remix) Clear"":
        - textbox: Sol (JAHAYA Remix)
        - button ""Clear""
        - button
      - cell ""01:31:33"":
        - textbox: 01:31:33
      - cell ""01:32:51"":
        - textbox: 01:32:51
      - cell ""00:01:18"":
        - textbox: 00:01:18
      - cell:
        - button
    - row ""Increment Decrement Alex Grafton Clear Hi Baby Clear 01:32:51 01:42:13 00:09:22"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""18""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Alex Grafton Clear"":
        - textbox: Alex Grafton
        - button ""Clear""
        - button
      - cell ""Hi Baby Clear"":
        - textbox: Hi Baby
        - button ""Clear""
        - button
      - cell ""01:32:51"":
        - textbox: 01:32:51
      - cell ""01:42:13"":
        - textbox: 01:42:13
      - cell ""00:09:22"":
        - textbox: 00:09:22
      - cell:
        - button
    - row ""Increment Decrement Che&amp;Mos &amp; Halo Far Clear Daddy Clear 01:42:13 01:45:22 00:03:09"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""19""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Che&amp;Mos &amp; Halo Far Clear"":
        - textbox: Che&amp;Mos &amp; Halo Far
        - button ""Clear""
        - button
      - cell ""Daddy Clear"":
        - textbox: Daddy
        - button ""Clear""
        - button
      - cell ""01:42:13"":
        - textbox: 01:42:13
      - cell ""01:45:22"":
        - textbox: 01:45:22
      - cell ""00:03:09"":
        - textbox: 00:03:09
      - cell:
        - button
    - row ""Increment Decrement K KARDEN Clear Acid Rain Clear 01:45:22 01:48:40 00:03:18"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""20""
        - button ""Increment""
        - button ""Decrement""
      - cell ""K KARDEN Clear"":
        - textbox: K KARDEN
        - button ""Clear""
        - button
      - cell ""Acid Rain Clear"":
        - textbox: Acid Rain
        - button ""Clear""
        - button
      - cell ""01:45:22"":
        - textbox: 01:45:22
      - cell ""01:48:40"":
        - textbox: 01:48:40
      - cell ""00:03:18"":
        - textbox: 00:03:18
      - cell:
        - button
    - row ""Increment Decrement Dobrov &amp; Gar1sson Clear Analogic (Redspace Remix) Clear 01:48:40 01:56:40 00:08:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""21""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Dobrov &amp; Gar1sson Clear"":
        - textbox: Dobrov &amp; Gar1sson
        - button ""Clear""
        - button
      - cell ""Analogic (Redspace Remix) Clear"":
        - textbox: Analogic (Redspace Remix)
        - button ""Clear""
        - button
      - cell ""01:48:40"":
        - textbox: 01:48:40
      - cell ""01:56:40"":
        - textbox: 01:56:40
      - cell ""00:08:00"":
        - textbox: 00:08:00
      - cell:
        - button
    - row ""Increment Decrement Gazfluz Clear Vargan Clear 01:56:40 02:00:39 00:03:59"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""22""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Gazfluz Clear"":
        - textbox: Gazfluz
        - button ""Clear""
        - button
      - cell ""Vargan Clear"":
        - textbox: Vargan
        - button ""Clear""
        - button
      - cell ""01:56:40"":
        - textbox: 01:56:40
      - cell ""02:00:39"":
        - textbox: 02:00:39
      - cell ""00:03:59"":
        - textbox: 00:03:59
      - cell:
        - button
    - row ""Increment Decrement SHKAPOV Clear Control Clear 02:00:39 02:06:47 00:06:08"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""23""
        - button ""Increment""
        - button ""Decrement""
      - cell ""SHKAPOV Clear"":
        - textbox: SHKAPOV
        - button ""Clear""
        - button
      - cell ""Control Clear"":
        - textbox: Control
        - button ""Clear""
        - button
      - cell ""02:00:39"":
        - textbox: 02:00:39
      - cell ""02:06:47"":
        - textbox: 02:06:47
      - cell ""00:06:08"":
        - textbox: 00:06:08
      - cell:
        - button
    - row ""Increment Decrement QazaQ Clear On the Line Clear 02:06:47 02:09:09 00:02:22"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""24""
        - button ""Increment""
        - button ""Decrement""
      - cell ""QazaQ Clear"":
        - textbox: QazaQ
        - button ""Clear""
        - button
      - cell ""On the Line Clear"":
        - textbox: On the Line
        - button ""Clear""
        - button
      - cell ""02:06:47"":
        - textbox: 02:06:47
      - cell ""02:09:09"":
        - textbox: 02:09:09
      - cell ""00:02:22"":
        - textbox: 00:02:22
      - cell:
        - button
    - row ""Increment Decrement Alex Schaufel Clear Elizabeth (Larsun Hesh Remix) Clear 02:09:09 02:14:18 00:05:09"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""25""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Alex Schaufel Clear"":
        - textbox: Alex Schaufel
        - button ""Clear""
        - button
      - cell ""Elizabeth (Larsun Hesh Remix) Clear"":
        - textbox: Elizabeth (Larsun Hesh Remix)
        - button ""Clear""
        - button
      - cell ""02:09:09"":
        - textbox: 02:09:09
      - cell ""02:14:18"":
        - textbox: 02:14:18
      - cell ""00:05:09"":
        - textbox: 00:05:09
      - cell:
        - button
    - row ""Increment Decrement Oiro Clear Just Business Clear 02:14:18 02:19:22 00:05:04"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""26""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Oiro Clear"":
        - textbox: Oiro
        - button ""Clear""
        - button
      - cell ""Just Business Clear"":
        - textbox: Just Business
        - button ""Clear""
        - button
      - cell ""02:14:18"":
        - textbox: 02:14:18
      - cell ""02:19:22"":
        - textbox: 02:19:22
      - cell ""00:05:04"":
        - textbox: 00:05:04
      - cell:
        - button
    - row ""Increment Decrement Molex Clear Mind Split (Redspace Remix) Clear 02:19:22 02:27:48 00:08:26"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""27""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Molex Clear"":
        - textbox: Molex
        - button ""Clear""
        - button
      - cell ""Mind Split (Redspace Remix) Clear"":
        - textbox: Mind Split (Redspace Remix)
        - button ""Clear""
        - button
      - cell ""02:19:22"":
        - textbox: 02:19:22
      - cell ""02:27:48"":
        - textbox: 02:27:48
      - cell ""00:08:26"":
        - textbox: 00:08:26
      - cell:
        - button
    - row ""Increment Decrement SOLI Clear Give Me Your Mind Clear 02:27:48 02:33:48 00:06:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""28""
        - button ""Increment""
        - button ""Decrement""
      - cell ""SOLI Clear"":
        - textbox: SOLI
        - button ""Clear""
        - button
      - cell ""Give Me Your Mind Clear"":
        - textbox: Give Me Your Mind
        - button ""Clear""
        - button
      - cell ""02:27:48"":
        - textbox: 02:27:48
      - cell ""02:33:48"":
        - textbox: 02:33:48
      - cell ""00:06:00"":
        - textbox: 00:06:00
      - cell:
        - button
    - row ""Increment Decrement MANDU Clear Jacky Clear 02:33:48 02:39:05 00:05:17"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""29""
        - button ""Increment""
        - button ""Decrement""
      - cell ""MANDU Clear"":
        - textbox: MANDU
        - button ""Clear""
        - button
      - cell ""Jacky Clear"":
        - textbox: Jacky
        - button ""Clear""
        - button
      - cell ""02:33:48"":
        - textbox: 02:33:48
      - cell ""02:39:05"":
        - textbox: 02:39:05
      - cell ""00:05:17"":
        - textbox: 00:05:17
      - cell:
        - button
    - row ""Increment Decrement SOLI Clear Spacetoon Clear 02:39:05 02:41:31 00:02:26"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""30""
        - button ""Increment""
        - button ""Decrement""
      - cell ""SOLI Clear"":
        - textbox: SOLI
        - button ""Clear""
        - button
      - cell ""Spacetoon Clear"":
        - textbox: Spacetoon
        - button ""Clear""
        - button
      - cell ""02:39:05"":
        - textbox: 02:39:05
      - cell ""02:41:31"":
        - textbox: 02:41:31
      - cell ""00:02:26"":
        - textbox: 00:02:26
      - cell:
        - button
    - row ""Increment Decrement Sasha Fashion Clear Moqton Clear 02:41:31 02:50:18 00:08:47"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""31""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sasha Fashion Clear"":
        - textbox: Sasha Fashion
        - button ""Clear""
        - button
      - cell ""Moqton Clear"":
        - textbox: Moqton
        - button ""Clear""
        - button
      - cell ""02:41:31"":
        - textbox: 02:41:31
      - cell ""02:50:18"":
        - textbox: 02:50:18
      - cell ""00:08:47"":
        - textbox: 00:08:47
      - cell:
        - button
    - row ""Increment Decrement NAASA Clear Poison Clear 02:50:18 02:56:45 00:06:27"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""32""
        - button ""Increment""
        - button ""Decrement""
      - cell ""NAASA Clear"":
        - textbox: NAASA
        - button ""Clear""
        - button
      - cell ""Poison Clear"":
        - textbox: Poison
        - button ""Clear""
        - button
      - cell ""02:50:18"":
        - textbox: 02:50:18
      - cell ""02:56:45"":
        - textbox: 02:56:45
      - cell ""00:06:27"":
        - textbox: 00:06:27
      - cell:
        - button
    - row ""Increment Decrement Nopopstar, 2JOHN'S &amp; Eugene Jay Clear Nightlong Clear 02:56:45 02:59:14 00:02:29"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""33""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Nopopstar, 2JOHN'S &amp; Eugene Jay Clear"":
        - textbox: Nopopstar, 2JOHN'S &amp; Eugene Jay
        - button ""Clear""
        - button
      - cell ""Nightlong Clear"":
        - textbox: Nightlong
        - button ""Clear""
        - button
      - cell ""02:56:45"":
        - textbox: 02:56:45
      - cell ""02:59:14"":
        - textbox: 02:59:14
      - cell ""00:02:29"":
        - textbox: 00:02:29
      - cell:
        - button
    - row ""Increment Decrement Skillz jay Clear Choir Clear 02:59:14 03:05:49 00:06:35"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""34""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Skillz jay Clear"":
        - textbox: Skillz jay
        - button ""Clear""
        - button
      - cell ""Choir Clear"":
        - textbox: Choir
        - button ""Clear""
        - button
      - cell ""02:59:14"":
        - textbox: 02:59:14
      - cell ""03:05:49"":
        - textbox: 03:05:49
      - cell ""00:06:35"":
        - textbox: 00:06:35
      - cell:
        - button
    - row ""Increment Decrement Kovax Clear Controller Clear 03:05:49 03:08:31 00:02:42"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""35""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Kovax Clear"":
        - textbox: Kovax
        - button ""Clear""
        - button
      - cell ""Controller Clear"":
        - textbox: Controller
        - button ""Clear""
        - button
      - cell ""03:05:49"":
        - textbox: 03:05:49
      - cell ""03:08:31"":
        - textbox: 03:08:31
      - cell ""00:02:42"":
        - textbox: 00:02:42
      - cell:
        - button
    - row ""Increment Decrement Mumboi Clear Just a Beat Clear 03:08:31 03:15:18 00:06:47"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""36""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Mumboi Clear"":
        - textbox: Mumboi
        - button ""Clear""
        - button
      - cell ""Just a Beat Clear"":
        - textbox: Just a Beat
        - button ""Clear""
        - button
      - cell ""03:08:31"":
        - textbox: 03:08:31
      - cell ""03:15:18"":
        - textbox: 03:15:18
      - cell ""00:06:47"":
        - textbox: 00:06:47
      - cell:
        - button
    - row ""Increment Decrement Eclept Clear Sprut Clear 03:15:18 03:20:35 00:05:17"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""37""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Eclept Clear"":
        - textbox: Eclept
        - button ""Clear""
        - button
      - cell ""Sprut Clear"":
        - textbox: Sprut
        - button ""Clear""
        - button
      - cell ""03:15:18"":
        - textbox: 03:15:18
      - cell ""03:20:35"":
        - textbox: 03:20:35
      - cell ""00:05:17"":
        - textbox: 00:05:17
      - cell:
        - button
    - row ""Increment Decrement Rudensky Clear Dark Escort Clear 03:20:35 03:25:02 00:04:27"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""38""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Rudensky Clear"":
        - textbox: Rudensky
        - button ""Clear""
        - button
      - cell ""Dark Escort Clear"":
        - textbox: Dark Escort
        - button ""Clear""
        - button
      - cell ""03:20:35"":
        - textbox: 03:20:35
      - cell ""03:25:02"":
        - textbox: 03:25:02
      - cell ""00:04:27"":
        - textbox: 00:04:27
      - cell:
        - button
    - row ""Increment Decrement Alexey Union, Kinky Sound &amp; KOCHETOV Clear Connected Clear 03:25:02 03:32:30 00:07:28"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""39""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Alexey Union, Kinky Sound &amp; KOCHETOV Clear"":
        - textbox: Alexey Union, Kinky Sound &amp; KOCHETOV
        - button ""Clear""
        - button
      - cell ""Connected Clear"":
        - textbox: Connected
        - button ""Clear""
        - button
      - cell ""03:25:02"":
        - textbox: 03:25:02
      - cell ""03:32:30"":
        - textbox: 03:32:30
      - cell ""00:07:28"":
        - textbox: 00:07:28
      - cell:
        - button
    - row ""Increment Decrement ANMA (MD) Clear Space Yoda (Snyl Remix) Clear 03:32:30 03:37:53 00:05:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""40""
        - button ""Increment""
        - button ""Decrement""
      - cell ""ANMA (MD) Clear"":
        - textbox: ANMA (MD)
        - button ""Clear""
        - button
      - cell ""Space Yoda (Snyl Remix) Clear"":
        - textbox: Space Yoda (Snyl Remix)
        - button ""Clear""
        - button
      - cell ""03:32:30"":
        - textbox: 03:32:30
      - cell ""03:37:53"":
        - textbox: 03:37:53
      - cell ""00:05:23"":
        - textbox: 00:05:23
      - cell:
        - button
    - row ""Increment Decrement Inache Clear Andale (MONTA (TN) Remix) Clear 03:37:53"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""41""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Inache Clear"":
        - textbox: Inache
        - button ""Clear""
        - button
      - cell ""Andale (MONTA (TN) Remix) Clear"":
        - textbox: Andale (MONTA (TN) Remix)
        - button ""Clear""
        - button
      - cell ""03:37:53"":
        - textbox: 03:37:53
      - cell:
        - textbox
      - cell:
        - textbox
      - cell:
        - button
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task Open_ShouldImportProject_WhenUsingProjectfile()
        {
            var detailView = new DetailView(TestPage);
            var appBar = new AppBar(TestPage);
            await detailView.GotoAsync();
            await appBar.OpenFileAsync("Sample_Project.ace");
            await Expect(detailView.CuesheetArtistInput).ToHaveValueAsync("Sample CD Artist");
            await Expect(detailView.CuesheetTitleInput).ToHaveValueAsync("Sample CD Title");
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Artist Title Begin End Length Status"":
      - columnheader:
        - checkbox
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Increment Decrement Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Increment Decrement Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 8 Clear Sample Title 8 Clear 00:45:54"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell:
        - textbox
      - cell:
        - textbox
      - cell:
        - button
  - rowgroup:
    - row");
            await appBar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Paragraph).Filter(new() { HasText = "Tracks has invalid Count (0)!" })).ToBeVisibleAsync();
        }

        [TestMethod]
        public async Task Open_ShouldImportCuesheet_WhenUsingCuesheetfile()
        {
            var detailView = new DetailView(TestPage);
            var appBar = new AppBar(TestPage);
            await detailView.GotoAsync();
            await appBar.OpenFileAsync("Sample_Cuesheet.cue");
            await Expect(detailView.CuesheetArtistInput).ToHaveValueAsync("Sample CD Artist");
            await Expect(detailView.CuesheetTitleInput).ToHaveValueAsync("Sample CD Title");
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Artist Title Begin End Length Status"":
      - columnheader:
        - checkbox
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Increment Decrement Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Increment Decrement Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 8 Clear Sample Title 8 Clear 00:45:54"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell:
        - textbox
      - cell:
        - textbox
      - cell:
        - button
  - rowgroup:
    - row");
            await appBar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Paragraph).Filter(new() { HasText = "Tracks has invalid Count (0)!" })).ToBeVisibleAsync();
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WhenUsingText()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            var text = String.Join(Environment.NewLine, File.ReadAllLines("Sample_Inputfile.txt"));
            await importView.ImportTextAsync(text);
            await importView.Analyze();
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Artist Title Begin End Length Status"":
      - columnheader:
        - checkbox
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Increment Decrement Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Increment Decrement Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
      - cell:
        - button
  - rowgroup:
    - row");
        }
    }
}
