//This file is part of AudioCuesheetEditor.

//AudioCuesheetEditor is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.

//AudioCuesheetEditor is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with Foobar.  If not, see
//<http: //www.gnu.org/licenses />.
using AudioCuesheetEditor.End2EndTests.Models;
using Microsoft.Playwright;

namespace AudioCuesheetEditor.End2EndTests.Tests.Desktop
{
    [TestClass]
    public class ImportTest : PlaywrightTestBase
    {
        [TestMethod]
        public async Task Import_ShouldImportTracks_WhenUsingSampleInputfile()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            var detailView = new DetailView(TestPage);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Sample_Inputfile.txt");
            await importView.Analyze();
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Select row 2 Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Select row 3 Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""3""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Select row 4 Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""4""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Select row 5 Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""5""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Select row 6 Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""6""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Select row 7 Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""7""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Select row 8 Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""8""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
      - cell:
        - button
  - rowgroup:
    - row");
            await Expect(detailView.AudiofileInput).ToBeEmptyAsync();
            await importView.GotoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Button, new() { Name = "Analyze" })).ToBeVisibleAsync();
        }

        [TestMethod]
        public async Task Import_ShouldBeEditable_WhenEditingTrack()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Sample_Inputfile.txt");
            await importView.Analyze();
            await importView.SelectTracksAsync([5]);
            await importView.EditTracksModalAsync("Sample Title Edited 5");
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Select row 2 Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Select row 3 Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""3""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Select row 4 Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""4""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Select row 5 Sample Artist 5 Clear Sample Title Edited 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""5""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title Edited 5 Clear"":
        - textbox: Sample Title Edited 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Select row 6 Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""6""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Select row 7 Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""7""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Select row 8 Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""8""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
      - cell:
        - button
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WithSpecialTextfile()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Textimport-Bug-#54.txt");
            await importView.SwitchImportProfileAsync("Textfile (just track data)");
            await importView.Analyze();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
  - rowgroup:
    - row ""Select row 1 Adriatique Clear X. Clear 00:00:00 00:05:24 00:05:24"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Adriatique Clear"":
        - textbox: Adriatique
        - button ""Clear""
        - button
      - cell ""X. Clear"":
        - textbox: X.
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:24"":
        - textbox: 00:05:24
      - cell ""00:05:24"":
        - textbox: 00:05:24
    - row ""Select row 2 Third Harmony Clear Fears And Dreams (Original Mix) Clear 00:05:24 00:10:39 00:05:15"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell ""Third Harmony Clear"":
        - textbox: Third Harmony
        - button ""Clear""
        - button
      - cell ""Fears And Dreams (Original Mix) Clear"":
        - textbox: Fears And Dreams (Original Mix)
        - button ""Clear""
        - button
      - cell ""00:05:24"":
        - textbox: 00:05:24
      - cell ""00:10:39"":
        - textbox: 00:10:39
      - cell ""00:05:15"":
        - textbox: 00:05:15
    - row ""Select row 3 Dele Sosimi Afrobeat Orchestra Clear Too Much Information (Laolu Remix; Edit) Clear 00:10:39 00:17:06 00:06:27"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""3""
      - cell ""Dele Sosimi Afrobeat Orchestra Clear"":
        - textbox: Dele Sosimi Afrobeat Orchestra
        - button ""Clear""
        - button
      - cell ""Too Much Information (Laolu Remix; Edit) Clear"":
        - textbox: Too Much Information (Laolu Remix; Edit)
        - button ""Clear""
        - button
      - cell ""00:10:39"":
        - textbox: 00:10:39
      - cell ""00:17:06"":
        - textbox: 00:17:06
      - cell ""00:06:27"":
        - textbox: 00:06:27
    - row ""Select row 4 Edem, Govan Clear Ankh (Onetwo MX Remix) Clear 00:17:06 00:23:21 00:06:15"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""4""
      - cell ""Edem, Govan Clear"":
        - textbox: Edem, Govan
        - button ""Clear""
        - button
      - cell ""Ankh (Onetwo MX Remix) Clear"":
        - textbox: Ankh (Onetwo MX Remix)
        - button ""Clear""
        - button
      - cell ""00:17:06"":
        - textbox: 00:17:06
      - cell ""00:23:21"":
        - textbox: 00:23:21
      - cell ""00:06:15"":
        - textbox: 00:06:15
    - row ""Select row 5 Jody Wisternoff Clear For All Time (feat. Hendrik Burkhard) (Extended Mix) Clear 00:23:21 00:29:02 00:05:41"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""5""
      - cell ""Jody Wisternoff Clear"":
        - textbox: Jody Wisternoff
        - button ""Clear""
        - button
      - cell ""For All Time (feat. Hendrik Burkhard) (Extended Mix) Clear"":
        - textbox: For All Time (feat. Hendrik Burkhard) (Extended Mix)
        - button ""Clear""
        - button
      - cell ""00:23:21"":
        - textbox: 00:23:21
      - cell ""00:29:02"":
        - textbox: 00:29:02
      - cell ""00:05:41"":
        - textbox: 00:05:41
    - row ""Select row 6 Einmusik Clear Bead (Original Mix) Clear 00:29:02 00:34:27 00:05:25"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""6""
      - cell ""Einmusik Clear"":
        - textbox: Einmusik
        - button ""Clear""
        - button
      - cell ""Bead (Original Mix) Clear"":
        - textbox: Bead (Original Mix)
        - button ""Clear""
        - button
      - cell ""00:29:02"":
        - textbox: 00:29:02
      - cell ""00:34:27"":
        - textbox: 00:34:27
      - cell ""00:05:25"":
        - textbox: 00:05:25
    - row ""Select row 7 Sebastien Leger Clear La Danse du Scorpion Clear 00:34:27 00:40:59 00:06:32"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""7""
      - cell ""Sebastien Leger Clear"":
        - textbox: Sebastien Leger
        - button ""Clear""
        - button
      - cell ""La Danse du Scorpion Clear"":
        - textbox: La Danse du Scorpion
        - button ""Clear""
        - button
      - cell ""00:34:27"":
        - textbox: 00:34:27
      - cell ""00:40:59"":
        - textbox: 00:40:59
      - cell ""00:06:32"":
        - textbox: 00:06:32
    - row ""Select row 8 Paul Thomas & Solid Stone Clear La Bombo (Solid Stone Remix) Clear 00:40:59 00:46:19 00:05:20"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""8""
      - cell ""Paul Thomas & Solid Stone Clear"":
        - textbox: Paul Thomas & Solid Stone
        - button ""Clear""
        - button
      - cell ""La Bombo (Solid Stone Remix) Clear"":
        - textbox: La Bombo (Solid Stone Remix)
        - button ""Clear""
        - button
      - cell ""00:40:59"":
        - textbox: 00:40:59
      - cell ""00:46:19"":
        - textbox: 00:46:19
      - cell ""00:05:20"":
        - textbox: 00:05:20
    - row ""Select row 9 GusGus Clear Crossfade (Maceo Plex Mix) Clear 00:46:19 00:52:20 00:06:01"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""9""
      - cell ""GusGus Clear"":
        - textbox: GusGus
        - button ""Clear""
        - button
      - cell ""Crossfade (Maceo Plex Mix) Clear"":
        - textbox: Crossfade (Maceo Plex Mix)
        - button ""Clear""
        - button
      - cell ""00:46:19"":
        - textbox: 00:46:19
      - cell ""00:52:20"":
        - textbox: 00:52:20
      - cell ""00:06:01"":
        - textbox: 00:06:01
    - row ""Select row 10 Klangkarussell Clear Time (Original Mix) Clear 00:52:20 00:56:19 00:03:59"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""10""
      - cell ""Klangkarussell Clear"":
        - textbox: Klangkarussell
        - button ""Clear""
        - button
      - cell ""Time (Original Mix) Clear"":
        - textbox: Time (Original Mix)
        - button ""Clear""
        - button
      - cell ""00:52:20"":
        - textbox: 00:52:20
      - cell ""00:56:19"":
        - textbox: 00:56:19
      - cell ""00:03:59"":
        - textbox: 00:03:59
    - row ""Select row 11 Anysense & Un:said Clear Missing Path (Original Mix) Clear 00:56:19 01:01:41 00:05:22"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""11""
      - cell ""Anysense & Un:said Clear"":
        - textbox: Anysense & Un:said
        - button ""Clear""
        - button
      - cell ""Missing Path (Original Mix) Clear"":
        - textbox: Missing Path (Original Mix)
        - button ""Clear""
        - button
      - cell ""00:56:19"":
        - textbox: 00:56:19
      - cell ""01:01:41"":
        - textbox: 01:01:41
      - cell ""00:05:22"":
        - textbox: 00:05:22
    - row ""Select row 12 Space Food Clear Bombay Clear 01:01:41 01:06:33 00:04:52"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""12""
      - cell ""Space Food Clear"":
        - textbox: Space Food
        - button ""Clear""
        - button
      - cell ""Bombay Clear"":
        - textbox: Bombay
        - button ""Clear""
        - button
      - cell ""01:01:41"":
        - textbox: 01:01:41
      - cell ""01:06:33"":
        - textbox: 01:06:33
      - cell ""00:04:52"":
        - textbox: 00:04:52
    - row ""Select row 13 SHDW & Obscure Shape Clear Wächter der Nacht (Original Mix) Clear 01:06:33 01:11:04 00:04:31"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""13""
      - cell ""SHDW & Obscure Shape Clear"":
        - textbox: SHDW & Obscure Shape
        - button ""Clear""
        - button
      - cell ""Wächter der Nacht (Original Mix) Clear"":
        - textbox: Wächter der Nacht (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:06:33"":
        - textbox: 01:06:33
      - cell ""01:11:04"":
        - textbox: 01:11:04
      - cell ""00:04:31"":
        - textbox: 00:04:31
    - row ""Select row 14 HOSH Clear Karma Clear 01:11:04 01:15:28 00:04:24"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""14""
      - cell ""HOSH Clear"":
        - textbox: HOSH
        - button ""Clear""
        - button
      - cell ""Karma Clear"":
        - textbox: Karma
        - button ""Clear""
        - button
      - cell ""01:11:04"":
        - textbox: 01:11:04
      - cell ""01:15:28"":
        - textbox: 01:15:28
      - cell ""00:04:24"":
        - textbox: 00:04:24
    - row ""Select row 15 Alexey Union Clear Olympia (Original Mix) Clear 01:15:28 01:21:08 00:05:40"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""15""
      - cell ""Alexey Union Clear"":
        - textbox: Alexey Union
        - button ""Clear""
        - button
      - cell ""Olympia (Original Mix) Clear"":
        - textbox: Olympia (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:15:28"":
        - textbox: 01:15:28
      - cell ""01:21:08"":
        - textbox: 01:21:08
      - cell ""00:05:40"":
        - textbox: 00:05:40
    - row ""Select row 16 Paul Taylor Clear Afterglow Clear 01:21:08 01:25:38 00:04:30"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""16""
      - cell ""Paul Taylor Clear"":
        - textbox: Paul Taylor
        - button ""Clear""
        - button
      - cell ""Afterglow Clear"":
        - textbox: Afterglow
        - button ""Clear""
        - button
      - cell ""01:21:08"":
        - textbox: 01:21:08
      - cell ""01:25:38"":
        - textbox: 01:25:38
      - cell ""00:04:30"":
        - textbox: 00:04:30
    - row ""Select row 17 Philter Clear Stranger Clear 01:25:38 01:31:52 00:06:14"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""17""
      - cell ""Philter Clear"":
        - textbox: Philter
        - button ""Clear""
        - button
      - cell ""Stranger Clear"":
        - textbox: Stranger
        - button ""Clear""
        - button
      - cell ""01:25:38"":
        - textbox: 01:25:38
      - cell ""01:31:52"":
        - textbox: 01:31:52
      - cell ""00:06:14"":
        - textbox: 00:06:14
    - row ""Select row 18 Skizologic Clear Hypersphere (Original Mix) Clear 01:31:52 01:36:40 00:04:48"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""18""
      - cell ""Skizologic Clear"":
        - textbox: Skizologic
        - button ""Clear""
        - button
      - cell ""Hypersphere (Original Mix) Clear"":
        - textbox: Hypersphere (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:31:52"":
        - textbox: 01:31:52
      - cell ""01:36:40"":
        - textbox: 01:36:40
      - cell ""00:04:48"":
        - textbox: 00:04:48
    - row ""Select row 19 Thomas Schumacher, Caitlin Clear All of You (Remix) Clear 01:36:40 01:42:16 00:05:36"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""19""
      - cell ""Thomas Schumacher, Caitlin Clear"":
        - textbox: Thomas Schumacher, Caitlin
        - button ""Clear""
        - button
      - cell ""All of You (Remix) Clear"":
        - textbox: All of You (Remix)
        - button ""Clear""
        - button
      - cell ""01:36:40"":
        - textbox: 01:36:40
      - cell ""01:42:16"":
        - textbox: 01:42:16
      - cell ""00:05:36"":
        - textbox: 00:05:36
    - row ""Select row 20 A. Skomoroh Clear White Horse Conquest (Original Mix) Clear 01:42:16 01:47:04 00:04:48"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""20""
      - cell ""A. Skomoroh Clear"":
        - textbox: A. Skomoroh
        - button ""Clear""
        - button
      - cell ""White Horse Conquest (Original Mix) Clear"":
        - textbox: White Horse Conquest (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:42:16"":
        - textbox: 01:42:16
      - cell ""01:47:04"":
        - textbox: 01:47:04
      - cell ""00:04:48"":
        - textbox: 00:04:48
    - row ""Select row 21 Patrik Berg Clear Bright (Original Mix) Clear 01:47:04 01:52:37 00:05:33"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""21""
      - cell ""Patrik Berg Clear"":
        - textbox: Patrik Berg
        - button ""Clear""
        - button
      - cell ""Bright (Original Mix) Clear"":
        - textbox: Bright (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:47:04"":
        - textbox: 01:47:04
      - cell ""01:52:37"":
        - textbox: 01:52:37
      - cell ""00:05:33"":
        - textbox: 00:05:33
    - row ""Select row 22 Hidden Empire Clear Bengal Clear 01:52:37 01:58:05 00:05:28"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""22""
      - cell ""Hidden Empire Clear"":
        - textbox: Hidden Empire
        - button ""Clear""
        - button
      - cell ""Bengal Clear"":
        - textbox: Bengal
        - button ""Clear""
        - button
      - cell ""01:52:37"":
        - textbox: 01:52:37
      - cell ""01:58:05"":
        - textbox: 01:58:05
      - cell ""00:05:28"":
        - textbox: 00:05:28
    - row ""Select row 23 Mario Ochoa Clear Levitate Clear 01:58:05 02:03:00 00:04:55"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""23""
      - cell ""Mario Ochoa Clear"":
        - textbox: Mario Ochoa
        - button ""Clear""
        - button
      - cell ""Levitate Clear"":
        - textbox: Levitate
        - button ""Clear""
        - button
      - cell ""01:58:05"":
        - textbox: 01:58:05
      - cell ""02:03:00"":
        - textbox: 02:03:00
      - cell ""00:04:55"":
        - textbox: 00:04:55
    - row ""Select row 24 Raul Facio Clear Eyes Wide Shut (Original Mix) Clear 02:03:00 02:08:21 00:05:21"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""24""
      - cell ""Raul Facio Clear"":
        - textbox: Raul Facio
        - button ""Clear""
        - button
      - cell ""Eyes Wide Shut (Original Mix) Clear"":
        - textbox: Eyes Wide Shut (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:03:00"":
        - textbox: 02:03:00
      - cell ""02:08:21"":
        - textbox: 02:08:21
      - cell ""00:05:21"":
        - textbox: 00:05:21
    - row ""Select row 25 Soolver Clear Regular (Original Mix) Clear 02:08:21 02:14:31 00:06:10"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""25""
      - cell ""Soolver Clear"":
        - textbox: Soolver
        - button ""Clear""
        - button
      - cell ""Regular (Original Mix) Clear"":
        - textbox: Regular (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:08:21"":
        - textbox: 02:08:21
      - cell ""02:14:31"":
        - textbox: 02:14:31
      - cell ""00:06:10"":
        - textbox: 00:06:10
    - row ""Select row 26 Weska Clear EQ64 (Original Mix) Clear 02:14:31 02:18:35 00:04:04"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""26""
      - cell ""Weska Clear"":
        - textbox: Weska
        - button ""Clear""
        - button
      - cell ""EQ64 (Original Mix) Clear"":
        - textbox: EQ64 (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:14:31"":
        - textbox: 02:14:31
      - cell ""02:18:35"":
        - textbox: 02:18:35
      - cell ""00:04:04"":
        - textbox: 00:04:04
    - row ""Select row 27 Tempo Giusto Clear The Fall (Extended Mix) Clear 02:18:35 02:24:12 00:05:37"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""27""
      - cell ""Tempo Giusto Clear"":
        - textbox: Tempo Giusto
        - button ""Clear""
        - button
      - cell ""The Fall (Extended Mix) Clear"":
        - textbox: The Fall (Extended Mix)
        - button ""Clear""
        - button
      - cell ""02:18:35"":
        - textbox: 02:18:35
      - cell ""02:24:12"":
        - textbox: 02:24:12
      - cell ""00:05:37"":
        - textbox: 00:05:37
    - row ""Select row 28 Vlind & Asteroid & Gary Leroy Clear Trinity (Extended Mix) Clear 02:24:12 02:29:38 00:05:26"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""28""
      - cell ""Vlind & Asteroid & Gary Leroy Clear"":
        - textbox: Vlind & Asteroid & Gary Leroy
        - button ""Clear""
        - button
      - cell ""Trinity (Extended Mix) Clear"":
        - textbox: Trinity (Extended Mix)
        - button ""Clear""
        - button
      - cell ""02:24:12"":
        - textbox: 02:24:12
      - cell ""02:29:38"":
        - textbox: 02:29:38
      - cell ""00:05:26"":
        - textbox: 00:05:26
    - row ""Select row 29 Astral Legacy Clear Vaveyla (Original Mix) Clear 02:29:38 02:32:52 00:03:14"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""29""
      - cell ""Astral Legacy Clear"":
        - textbox: Astral Legacy
        - button ""Clear""
        - button
      - cell ""Vaveyla (Original Mix) Clear"":
        - textbox: Vaveyla (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:29:38"":
        - textbox: 02:29:38
      - cell ""02:32:52"":
        - textbox: 02:32:52
      - cell ""00:03:14"":
        - textbox: 00:03:14
    - row ""Select row 30 Gerrox Clear Chakra (Original Mix) Clear 02:32:52 02:37:00 00:04:08"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""30""
      - cell ""Gerrox Clear"":
        - textbox: Gerrox
        - button ""Clear""
        - button
      - cell ""Chakra (Original Mix) Clear"":
        - textbox: Chakra (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:32:52"":
        - textbox: 02:32:52
      - cell ""02:37:00"":
        - textbox: 02:37:00
      - cell ""00:04:08"":
        - textbox: 00:04:08
    - row ""Select row 31 Charlotte De Witte Clear Pattern Clear 02:37:00 02:41:55 00:04:55"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""31""
      - cell ""Charlotte De Witte Clear"":
        - textbox: Charlotte De Witte
        - button ""Clear""
        - button
      - cell ""Pattern Clear"":
        - textbox: Pattern
        - button ""Clear""
        - button
      - cell ""02:37:00"":
        - textbox: 02:37:00
      - cell ""02:41:55"":
        - textbox: 02:41:55
      - cell ""00:04:55"":
        - textbox: 00:04:55
    - row ""Select row 32 Space Food Clear Amabey Clear 02:41:55 02:46:55 00:05:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""32""
      - cell ""Space Food Clear"":
        - textbox: Space Food
        - button ""Clear""
        - button
      - cell ""Amabey Clear"":
        - textbox: Amabey
        - button ""Clear""
        - button
      - cell ""02:41:55"":
        - textbox: 02:41:55
      - cell ""02:46:55"":
        - textbox: 02:46:55
      - cell ""00:05:00"":
        - textbox: 00:05:00
    - row ""Select row 33 ARTBAT Clear Papilion (Original Mix) Clear 02:46:55 02:51:13 00:04:18"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""33""
      - cell ""ARTBAT Clear"":
        - textbox: ARTBAT
        - button ""Clear""
        - button
      - cell ""Papilion (Original Mix) Clear"":
        - textbox: Papilion (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:46:55"":
        - textbox: 02:46:55
      - cell ""02:51:13"":
        - textbox: 02:51:13
      - cell ""00:04:18"":
        - textbox: 00:04:18
    - row ""Select row 34 PETER PAHN Clear Enjoy Infinity (Original Mix) Clear 02:51:13 02:56:08 00:04:55"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""34""
      - cell ""PETER PAHN Clear"":
        - textbox: PETER PAHN
        - button ""Clear""
        - button
      - cell ""Enjoy Infinity (Original Mix) Clear"":
        - textbox: Enjoy Infinity (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:51:13"":
        - textbox: 02:51:13
      - cell ""02:56:08"":
        - textbox: 02:56:08
      - cell ""00:04:55"":
        - textbox: 00:04:55
    - row ""Select row 35 Solitek Clear Instinct (Original Mix) Clear 02:56:08 03:00:57 00:04:49"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""35""
      - cell ""Solitek Clear"":
        - textbox: Solitek
        - button ""Clear""
        - button
      - cell ""Instinct (Original Mix) Clear"":
        - textbox: Instinct (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:56:08"":
        - textbox: 02:56:08
      - cell ""03:00:57"":
        - textbox: 03:00:57
      - cell ""00:04:49"":
        - textbox: 00:04:49
    - row ""Select row 36 Veerus Clear Heavy Clear 03:00:57 03:05:19 00:04:22"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""36""
      - cell ""Veerus Clear"":
        - textbox: Veerus
        - button ""Clear""
        - button
      - cell ""Heavy Clear"":
        - textbox: Heavy
        - button ""Clear""
        - button
      - cell ""03:00:57"":
        - textbox: 03:00:57
      - cell ""03:05:19"":
        - textbox: 03:05:19
      - cell ""00:04:22"":
        - textbox: 00:04:22
    - row ""Select row 37 Secret Cinema & Reinier Zonneveld Clear Pain Thing (Original Mix) Clear 03:05:19 03:09:38 00:04:19"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""37""
      - cell ""Secret Cinema & Reinier Zonneveld Clear"":
        - textbox: Secret Cinema & Reinier Zonneveld
        - button ""Clear""
        - button
      - cell ""Pain Thing (Original Mix) Clear"":
        - textbox: Pain Thing (Original Mix)
        - button ""Clear""
        - button
      - cell ""03:05:19"":
        - textbox: 03:05:19
      - cell ""03:09:38"":
        - textbox: 03:09:38
      - cell ""00:04:19"":
        - textbox: 00:04:19
    - row ""Select row 38 Amelie Lens Clear Hypnotized Clear 03:09:38 03:13:13 00:03:35"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""38""
      - cell ""Amelie Lens Clear"":
        - textbox: Amelie Lens
        - button ""Clear""
        - button
      - cell ""Hypnotized Clear"":
        - textbox: Hypnotized
        - button ""Clear""
        - button
      - cell ""03:09:38"":
        - textbox: 03:09:38
      - cell ""03:13:13"":
        - textbox: 03:13:13
      - cell ""00:03:35"":
        - textbox: 00:03:35
    - row ""Select row 39 Nikolay Kirov Clear Chasing the Sun (Original Mix) Clear 03:13:13"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""39""
      - cell ""Nikolay Kirov Clear"":
        - textbox: Nikolay Kirov
        - button ""Clear""
        - button
      - cell ""Chasing the Sun (Original Mix) Clear"":
        - textbox: Chasing the Sun (Original Mix)
        - button ""Clear""
        - button
      - cell ""03:13:13"":
        - textbox: 03:13:13
      - cell:
        - textbox
      - cell:
        - textbox
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WhenUsingSampleInputfile2()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Sample_Inputfile2.txt");
            await importView.ClearSchemeCommonDataAsync();
            await importView.Analyze();
            await Expect(importView.CuesheetArtistInput).ToBeEmptyAsync();
            await Expect(importView.CuesheetTitleInput).ToBeEmptyAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
  - rowgroup:
    - row ""Select row 1 Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
    - row ""Select row 2 Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
    - row ""Select row 3 Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""3""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
    - row ""Select row 4 Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""4""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
    - row ""Select row 5 Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""5""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
    - row ""Select row 6 Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""6""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
    - row ""Select row 7 Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""7""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
    - row ""Select row 8 Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""8""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WithTraktorOutput()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Traktor Export.html");
            await importView.SwitchImportProfileAsync("Traktor history");
            await importView.Analyze();
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Nachap Clear Glass Clear 00:00:00 00:11:56 00:11:56"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Nachap Clear"":
        - textbox: Nachap
        - button ""Clear""
        - button
      - cell ""Glass Clear"":
        - textbox: Glass
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:11:56"":
        - textbox: 00:11:56
      - cell ""00:11:56"":
        - textbox: 00:11:56
      - cell
    - row ""Select row 2 Progressive + Melodic DECK Clear 00:11:56 00:13:31 00:01:35"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell:
        - textbox
        - button
      - cell ""Progressive + Melodic DECK Clear"":
        - textbox: Progressive + Melodic DECK
        - button ""Clear""
        - button
      - cell ""00:11:56"":
        - textbox: 00:11:56
      - cell ""00:13:31"":
        - textbox: 00:13:31
      - cell ""00:01:35"":
        - textbox: 00:01:35
      - cell:
        - button
    - row ""Select row 3 Nomer 21 Clear Depersonalization Clear 00:13:31 00:19:14 00:05:43"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""3""
      - cell ""Nomer 21 Clear"":
        - textbox: Nomer 21
        - button ""Clear""
        - button
      - cell ""Depersonalization Clear"":
        - textbox: Depersonalization
        - button ""Clear""
        - button
      - cell ""00:13:31"":
        - textbox: 00:13:31
      - cell ""00:19:14"":
        - textbox: 00:19:14
      - cell ""00:05:43"":
        - textbox: 00:05:43
      - cell:
        - button
    - row ""Select row 4 SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear Showing Off Clear 00:19:14 00:24:02 00:04:48"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""4""
      - cell ""SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear"":
        - textbox: SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay
        - button ""Clear""
        - button
      - cell ""Showing Off Clear"":
        - textbox: Showing Off
        - button ""Clear""
        - button
      - cell ""00:19:14"":
        - textbox: 00:19:14
      - cell ""00:24:02"":
        - textbox: 00:24:02
      - cell ""00:04:48"":
        - textbox: 00:04:48
      - cell:
        - button
    - row ""Select row 5 Carlo Whale Clear Unconscious Clear 00:24:02 00:29:37 00:05:35"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""5""
      - cell ""Carlo Whale Clear"":
        - textbox: Carlo Whale
        - button ""Clear""
        - button
      - cell ""Unconscious Clear"":
        - textbox: Unconscious
        - button ""Clear""
        - button
      - cell ""00:24:02"":
        - textbox: 00:24:02
      - cell ""00:29:37"":
        - textbox: 00:29:37
      - cell ""00:05:35"":
        - textbox: 00:05:35
      - cell:
        - button
    - row ""Select row 6 Arba Han Clear Timelaps Clear 00:29:37 00:33:13 00:03:36"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""6""
      - cell ""Arba Han Clear"":
        - textbox: Arba Han
        - button ""Clear""
        - button
      - cell ""Timelaps Clear"":
        - textbox: Timelaps
        - button ""Clear""
        - button
      - cell ""00:29:37"":
        - textbox: 00:29:37
      - cell ""00:33:13"":
        - textbox: 00:33:13
      - cell ""00:03:36"":
        - textbox: 00:03:36
      - cell:
        - button
    - row ""Select row 7 Savill Clear Energy Surrounds Clear 00:33:13 00:40:30 00:07:17"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""7""
      - cell ""Savill Clear"":
        - textbox: Savill
        - button ""Clear""
        - button
      - cell ""Energy Surrounds Clear"":
        - textbox: Energy Surrounds
        - button ""Clear""
        - button
      - cell ""00:33:13"":
        - textbox: 00:33:13
      - cell ""00:40:30"":
        - textbox: 00:40:30
      - cell ""00:07:17"":
        - textbox: 00:07:17
      - cell:
        - button
    - row ""Select row 8 Teklix Clear The Tribal Code Clear 00:40:30 00:48:53 00:08:23"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""8""
      - cell ""Teklix Clear"":
        - textbox: Teklix
        - button ""Clear""
        - button
      - cell ""The Tribal Code Clear"":
        - textbox: The Tribal Code
        - button ""Clear""
        - button
      - cell ""00:40:30"":
        - textbox: 00:40:30
      - cell ""00:48:53"":
        - textbox: 00:48:53
      - cell ""00:08:23"":
        - textbox: 00:08:23
      - cell:
        - button
    - row ""Select row 9 Neuralis Clear I'm Looking for Answers Clear 00:48:53 00:54:34 00:05:41"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""9""
      - cell ""Neuralis Clear"":
        - textbox: Neuralis
        - button ""Clear""
        - button
      - cell ""I'm Looking for Answers Clear"":
        - textbox: I'm Looking for Answers
        - button ""Clear""
        - button
      - cell ""00:48:53"":
        - textbox: 00:48:53
      - cell ""00:54:34"":
        - textbox: 00:54:34
      - cell ""00:05:41"":
        - textbox: 00:05:41
      - cell:
        - button
    - row ""Select row 10 Nopopstar &amp; Arsia Clear Dirty Moves Clear 00:54:34 01:00:24 00:05:50"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""10""
      - cell ""Nopopstar &amp; Arsia Clear"":
        - textbox: Nopopstar &amp; Arsia
        - button ""Clear""
        - button
      - cell ""Dirty Moves Clear"":
        - textbox: Dirty Moves
        - button ""Clear""
        - button
      - cell ""00:54:34"":
        - textbox: 00:54:34
      - cell ""01:00:24"":
        - textbox: 01:00:24
      - cell ""00:05:50"":
        - textbox: 00:05:50
      - cell:
        - button
    - row ""Select row 11 SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear Lost (Maze 28 Remix) Clear 01:00:24 01:05:17 00:04:53"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""11""
      - cell ""SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear"":
        - textbox: SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay
        - button ""Clear""
        - button
      - cell ""Lost (Maze 28 Remix) Clear"":
        - textbox: Lost (Maze 28 Remix)
        - button ""Clear""
        - button
      - cell ""01:00:24"":
        - textbox: 01:00:24
      - cell ""01:05:17"":
        - textbox: 01:05:17
      - cell ""00:04:53"":
        - textbox: 00:04:53
      - cell:
        - button
    - row ""Select row 12 SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear Lost (Redspace Remix) Clear 01:05:17 01:08:22 00:03:05"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""12""
      - cell ""SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay Clear"":
        - textbox: SevenEver, Nopopstar, 2JOHN'S &amp; Eugene Jay
        - button ""Clear""
        - button
      - cell ""Lost (Redspace Remix) Clear"":
        - textbox: Lost (Redspace Remix)
        - button ""Clear""
        - button
      - cell ""01:05:17"":
        - textbox: 01:05:17
      - cell ""01:08:22"":
        - textbox: 01:08:22
      - cell ""00:03:05"":
        - textbox: 00:03:05
      - cell:
        - button
    - row ""Select row 13 Gadoz Clear 5d Clear 01:08:22 01:16:34 00:08:12"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""13""
      - cell ""Gadoz Clear"":
        - textbox: Gadoz
        - button ""Clear""
        - button
      - cell ""5d Clear"":
        - textbox: 5d
        - button ""Clear""
        - button
      - cell ""01:08:22"":
        - textbox: 01:08:22
      - cell ""01:16:34"":
        - textbox: 01:16:34
      - cell ""00:08:12"":
        - textbox: 00:08:12
      - cell:
        - button
    - row ""Select row 14 DJ Danzik Clear Out of Space Clear 01:16:34 01:19:22 00:02:48"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""14""
      - cell ""DJ Danzik Clear"":
        - textbox: DJ Danzik
        - button ""Clear""
        - button
      - cell ""Out of Space Clear"":
        - textbox: Out of Space
        - button ""Clear""
        - button
      - cell ""01:16:34"":
        - textbox: 01:16:34
      - cell ""01:19:22"":
        - textbox: 01:19:22
      - cell ""00:02:48"":
        - textbox: 00:02:48
      - cell:
        - button
    - row ""Select row 15 Enis Çoban Clear Internet Clear 01:19:22 01:25:14 00:05:52"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""15""
      - cell ""Enis Çoban Clear"":
        - textbox: Enis Çoban
        - button ""Clear""
        - button
      - cell ""Internet Clear"":
        - textbox: Internet
        - button ""Clear""
        - button
      - cell ""01:19:22"":
        - textbox: 01:19:22
      - cell ""01:25:14"":
        - textbox: 01:25:14
      - cell ""00:05:52"":
        - textbox: 00:05:52
      - cell:
        - button
    - row ""Select row 16 Cold Mind &amp; Alex Yikker Clear Rage Clear 01:25:14 01:31:33 00:06:19"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""16""
      - cell ""Cold Mind &amp; Alex Yikker Clear"":
        - textbox: Cold Mind &amp; Alex Yikker
        - button ""Clear""
        - button
      - cell ""Rage Clear"":
        - textbox: Rage
        - button ""Clear""
        - button
      - cell ""01:25:14"":
        - textbox: 01:25:14
      - cell ""01:31:33"":
        - textbox: 01:31:33
      - cell ""00:06:19"":
        - textbox: 00:06:19
      - cell:
        - button
    - row ""Select row 17 Maze 28 Clear Sol (JAHAYA Remix) Clear 01:31:33 01:32:51 00:01:18"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""17""
      - cell ""Maze 28 Clear"":
        - textbox: Maze 28
        - button ""Clear""
        - button
      - cell ""Sol (JAHAYA Remix) Clear"":
        - textbox: Sol (JAHAYA Remix)
        - button ""Clear""
        - button
      - cell ""01:31:33"":
        - textbox: 01:31:33
      - cell ""01:32:51"":
        - textbox: 01:32:51
      - cell ""00:01:18"":
        - textbox: 00:01:18
      - cell:
        - button
    - row ""Select row 18 Alex Grafton Clear Hi Baby Clear 01:32:51 01:42:13 00:09:22"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""18""
      - cell ""Alex Grafton Clear"":
        - textbox: Alex Grafton
        - button ""Clear""
        - button
      - cell ""Hi Baby Clear"":
        - textbox: Hi Baby
        - button ""Clear""
        - button
      - cell ""01:32:51"":
        - textbox: 01:32:51
      - cell ""01:42:13"":
        - textbox: 01:42:13
      - cell ""00:09:22"":
        - textbox: 00:09:22
      - cell:
        - button
    - row ""Select row 19 Che&amp;Mos &amp; Halo Far Clear Daddy Clear 01:42:13 01:45:22 00:03:09"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""19""
      - cell ""Che&amp;Mos &amp; Halo Far Clear"":
        - textbox: Che&amp;Mos &amp; Halo Far
        - button ""Clear""
        - button
      - cell ""Daddy Clear"":
        - textbox: Daddy
        - button ""Clear""
        - button
      - cell ""01:42:13"":
        - textbox: 01:42:13
      - cell ""01:45:22"":
        - textbox: 01:45:22
      - cell ""00:03:09"":
        - textbox: 00:03:09
      - cell:
        - button
    - row ""Select row 20 K KARDEN Clear Acid Rain Clear 01:45:22 01:48:40 00:03:18"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""20""
      - cell ""K KARDEN Clear"":
        - textbox: K KARDEN
        - button ""Clear""
        - button
      - cell ""Acid Rain Clear"":
        - textbox: Acid Rain
        - button ""Clear""
        - button
      - cell ""01:45:22"":
        - textbox: 01:45:22
      - cell ""01:48:40"":
        - textbox: 01:48:40
      - cell ""00:03:18"":
        - textbox: 00:03:18
      - cell:
        - button
    - row ""Select row 21 Dobrov &amp; Gar1sson Clear Analogic (Redspace Remix) Clear 01:48:40 01:56:40 00:08:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""21""
      - cell ""Dobrov &amp; Gar1sson Clear"":
        - textbox: Dobrov &amp; Gar1sson
        - button ""Clear""
        - button
      - cell ""Analogic (Redspace Remix) Clear"":
        - textbox: Analogic (Redspace Remix)
        - button ""Clear""
        - button
      - cell ""01:48:40"":
        - textbox: 01:48:40
      - cell ""01:56:40"":
        - textbox: 01:56:40
      - cell ""00:08:00"":
        - textbox: 00:08:00
      - cell:
        - button
    - row ""Select row 22 Gazfluz Clear Vargan Clear 01:56:40 02:00:39 00:03:59"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""22""
      - cell ""Gazfluz Clear"":
        - textbox: Gazfluz
        - button ""Clear""
        - button
      - cell ""Vargan Clear"":
        - textbox: Vargan
        - button ""Clear""
        - button
      - cell ""01:56:40"":
        - textbox: 01:56:40
      - cell ""02:00:39"":
        - textbox: 02:00:39
      - cell ""00:03:59"":
        - textbox: 00:03:59
      - cell:
        - button
    - row ""Select row 23 SHKAPOV Clear Control Clear 02:00:39 02:06:47 00:06:08"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""23""
      - cell ""SHKAPOV Clear"":
        - textbox: SHKAPOV
        - button ""Clear""
        - button
      - cell ""Control Clear"":
        - textbox: Control
        - button ""Clear""
        - button
      - cell ""02:00:39"":
        - textbox: 02:00:39
      - cell ""02:06:47"":
        - textbox: 02:06:47
      - cell ""00:06:08"":
        - textbox: 00:06:08
      - cell:
        - button
    - row ""Select row 24 QazaQ Clear On the Line Clear 02:06:47 02:09:09 00:02:22"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""24""
      - cell ""QazaQ Clear"":
        - textbox: QazaQ
        - button ""Clear""
        - button
      - cell ""On the Line Clear"":
        - textbox: On the Line
        - button ""Clear""
        - button
      - cell ""02:06:47"":
        - textbox: 02:06:47
      - cell ""02:09:09"":
        - textbox: 02:09:09
      - cell ""00:02:22"":
        - textbox: 00:02:22
      - cell:
        - button
    - row ""Select row 25 Alex Schaufel Clear Elizabeth (Larsun Hesh Remix) Clear 02:09:09 02:14:18 00:05:09"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""25""
      - cell ""Alex Schaufel Clear"":
        - textbox: Alex Schaufel
        - button ""Clear""
        - button
      - cell ""Elizabeth (Larsun Hesh Remix) Clear"":
        - textbox: Elizabeth (Larsun Hesh Remix)
        - button ""Clear""
        - button
      - cell ""02:09:09"":
        - textbox: 02:09:09
      - cell ""02:14:18"":
        - textbox: 02:14:18
      - cell ""00:05:09"":
        - textbox: 00:05:09
      - cell:
        - button
    - row ""Select row 26 Oiro Clear Just Business Clear 02:14:18 02:19:22 00:05:04"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""26""
      - cell ""Oiro Clear"":
        - textbox: Oiro
        - button ""Clear""
        - button
      - cell ""Just Business Clear"":
        - textbox: Just Business
        - button ""Clear""
        - button
      - cell ""02:14:18"":
        - textbox: 02:14:18
      - cell ""02:19:22"":
        - textbox: 02:19:22
      - cell ""00:05:04"":
        - textbox: 00:05:04
      - cell:
        - button
    - row ""Select row 27 Molex Clear Mind Split (Redspace Remix) Clear 02:19:22 02:27:48 00:08:26"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""27""
      - cell ""Molex Clear"":
        - textbox: Molex
        - button ""Clear""
        - button
      - cell ""Mind Split (Redspace Remix) Clear"":
        - textbox: Mind Split (Redspace Remix)
        - button ""Clear""
        - button
      - cell ""02:19:22"":
        - textbox: 02:19:22
      - cell ""02:27:48"":
        - textbox: 02:27:48
      - cell ""00:08:26"":
        - textbox: 00:08:26
      - cell:
        - button
    - row ""Select row 28 SOLI Clear Give Me Your Mind Clear 02:27:48 02:33:48 00:06:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""28""
      - cell ""SOLI Clear"":
        - textbox: SOLI
        - button ""Clear""
        - button
      - cell ""Give Me Your Mind Clear"":
        - textbox: Give Me Your Mind
        - button ""Clear""
        - button
      - cell ""02:27:48"":
        - textbox: 02:27:48
      - cell ""02:33:48"":
        - textbox: 02:33:48
      - cell ""00:06:00"":
        - textbox: 00:06:00
      - cell:
        - button
    - row ""Select row 29 MANDU Clear Jacky Clear 02:33:48 02:39:05 00:05:17"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""29""
      - cell ""MANDU Clear"":
        - textbox: MANDU
        - button ""Clear""
        - button
      - cell ""Jacky Clear"":
        - textbox: Jacky
        - button ""Clear""
        - button
      - cell ""02:33:48"":
        - textbox: 02:33:48
      - cell ""02:39:05"":
        - textbox: 02:39:05
      - cell ""00:05:17"":
        - textbox: 00:05:17
      - cell:
        - button
    - row ""Select row 30 SOLI Clear Spacetoon Clear 02:39:05 02:41:31 00:02:26"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""30""
      - cell ""SOLI Clear"":
        - textbox: SOLI
        - button ""Clear""
        - button
      - cell ""Spacetoon Clear"":
        - textbox: Spacetoon
        - button ""Clear""
        - button
      - cell ""02:39:05"":
        - textbox: 02:39:05
      - cell ""02:41:31"":
        - textbox: 02:41:31
      - cell ""00:02:26"":
        - textbox: 00:02:26
      - cell:
        - button
    - row ""Select row 31 Sasha Fashion Clear Moqton Clear 02:41:31 02:50:18 00:08:47"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""31""
      - cell ""Sasha Fashion Clear"":
        - textbox: Sasha Fashion
        - button ""Clear""
        - button
      - cell ""Moqton Clear"":
        - textbox: Moqton
        - button ""Clear""
        - button
      - cell ""02:41:31"":
        - textbox: 02:41:31
      - cell ""02:50:18"":
        - textbox: 02:50:18
      - cell ""00:08:47"":
        - textbox: 00:08:47
      - cell:
        - button
    - row ""Select row 32 NAASA Clear Poison Clear 02:50:18 02:56:45 00:06:27"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""32""
      - cell ""NAASA Clear"":
        - textbox: NAASA
        - button ""Clear""
        - button
      - cell ""Poison Clear"":
        - textbox: Poison
        - button ""Clear""
        - button
      - cell ""02:50:18"":
        - textbox: 02:50:18
      - cell ""02:56:45"":
        - textbox: 02:56:45
      - cell ""00:06:27"":
        - textbox: 00:06:27
      - cell:
        - button
    - row ""Select row 33 Nopopstar, 2JOHN'S &amp; Eugene Jay Clear Nightlong Clear 02:56:45 02:59:14 00:02:29"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""33""
      - cell ""Nopopstar, 2JOHN'S &amp; Eugene Jay Clear"":
        - textbox: Nopopstar, 2JOHN'S &amp; Eugene Jay
        - button ""Clear""
        - button
      - cell ""Nightlong Clear"":
        - textbox: Nightlong
        - button ""Clear""
        - button
      - cell ""02:56:45"":
        - textbox: 02:56:45
      - cell ""02:59:14"":
        - textbox: 02:59:14
      - cell ""00:02:29"":
        - textbox: 00:02:29
      - cell:
        - button
    - row ""Select row 34 Skillz jay Clear Choir Clear 02:59:14 03:05:49 00:06:35"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""34""
      - cell ""Skillz jay Clear"":
        - textbox: Skillz jay
        - button ""Clear""
        - button
      - cell ""Choir Clear"":
        - textbox: Choir
        - button ""Clear""
        - button
      - cell ""02:59:14"":
        - textbox: 02:59:14
      - cell ""03:05:49"":
        - textbox: 03:05:49
      - cell ""00:06:35"":
        - textbox: 00:06:35
      - cell:
        - button
    - row ""Select row 35 Kovax Clear Controller Clear 03:05:49 03:08:31 00:02:42"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""35""
      - cell ""Kovax Clear"":
        - textbox: Kovax
        - button ""Clear""
        - button
      - cell ""Controller Clear"":
        - textbox: Controller
        - button ""Clear""
        - button
      - cell ""03:05:49"":
        - textbox: 03:05:49
      - cell ""03:08:31"":
        - textbox: 03:08:31
      - cell ""00:02:42"":
        - textbox: 00:02:42
      - cell:
        - button
    - row ""Select row 36 Mumboi Clear Just a Beat Clear 03:08:31 03:15:18 00:06:47"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""36""
      - cell ""Mumboi Clear"":
        - textbox: Mumboi
        - button ""Clear""
        - button
      - cell ""Just a Beat Clear"":
        - textbox: Just a Beat
        - button ""Clear""
        - button
      - cell ""03:08:31"":
        - textbox: 03:08:31
      - cell ""03:15:18"":
        - textbox: 03:15:18
      - cell ""00:06:47"":
        - textbox: 00:06:47
      - cell:
        - button
    - row ""Select row 37 Eclept Clear Sprut Clear 03:15:18 03:20:35 00:05:17"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""37""
      - cell ""Eclept Clear"":
        - textbox: Eclept
        - button ""Clear""
        - button
      - cell ""Sprut Clear"":
        - textbox: Sprut
        - button ""Clear""
        - button
      - cell ""03:15:18"":
        - textbox: 03:15:18
      - cell ""03:20:35"":
        - textbox: 03:20:35
      - cell ""00:05:17"":
        - textbox: 00:05:17
      - cell:
        - button
    - row ""Select row 38 Rudensky Clear Dark Escort Clear 03:20:35 03:25:02 00:04:27"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""38""
      - cell ""Rudensky Clear"":
        - textbox: Rudensky
        - button ""Clear""
        - button
      - cell ""Dark Escort Clear"":
        - textbox: Dark Escort
        - button ""Clear""
        - button
      - cell ""03:20:35"":
        - textbox: 03:20:35
      - cell ""03:25:02"":
        - textbox: 03:25:02
      - cell ""00:04:27"":
        - textbox: 00:04:27
      - cell:
        - button
    - row ""Select row 39 Alexey Union, Kinky Sound &amp; KOCHETOV Clear Connected Clear 03:25:02 03:32:30 00:07:28"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""39""
      - cell ""Alexey Union, Kinky Sound &amp; KOCHETOV Clear"":
        - textbox: Alexey Union, Kinky Sound &amp; KOCHETOV
        - button ""Clear""
        - button
      - cell ""Connected Clear"":
        - textbox: Connected
        - button ""Clear""
        - button
      - cell ""03:25:02"":
        - textbox: 03:25:02
      - cell ""03:32:30"":
        - textbox: 03:32:30
      - cell ""00:07:28"":
        - textbox: 00:07:28
      - cell:
        - button
    - row ""Select row 40 ANMA (MD) Clear Space Yoda (Snyl Remix) Clear 03:32:30 03:37:53 00:05:23"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""40""
      - cell ""ANMA (MD) Clear"":
        - textbox: ANMA (MD)
        - button ""Clear""
        - button
      - cell ""Space Yoda (Snyl Remix) Clear"":
        - textbox: Space Yoda (Snyl Remix)
        - button ""Clear""
        - button
      - cell ""03:32:30"":
        - textbox: 03:32:30
      - cell ""03:37:53"":
        - textbox: 03:37:53
      - cell ""00:05:23"":
        - textbox: 00:05:23
      - cell:
        - button
    - row ""Select row 41 Inache Clear Andale (MONTA (TN) Remix) Clear 03:37:53"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""41""
      - cell ""Inache Clear"":
        - textbox: Inache
        - button ""Clear""
        - button
      - cell ""Andale (MONTA (TN) Remix) Clear"":
        - textbox: Andale (MONTA (TN) Remix)
        - button ""Clear""
        - button
      - cell ""03:37:53"":
        - textbox: 03:37:53
      - cell:
        - textbox
      - cell:
        - textbox
      - cell:
        - button
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task Open_ShouldImportProject_WhenUsingProjectfile()
        {
            var detailView = new DetailView(TestPage);
            var appBar = new AppBar(TestPage);
            await detailView.GotoAsync();
            await appBar.OpenFileAsync("Sample_Project.ace");
            await Expect(detailView.CuesheetArtistInput).ToHaveValueAsync("Sample CD Artist");
            await Expect(detailView.CuesheetTitleInput).ToHaveValueAsync("Sample CD Title");
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Select row 2 Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Select row 3 Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""3""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Select row 4 Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""4""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Select row 5 Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""5""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Select row 6 Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""6""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Select row 7 Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""7""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Select row 8 Sample Artist 8 Clear Sample Title 8 Clear 00:45:54"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""8""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell:
        - textbox
      - cell:
        - textbox
      - cell:
        - button
  - rowgroup:
    - row");
            await appBar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Paragraph).Filter(new() { HasText = "Tracks has invalid Count (0)!" })).ToBeVisibleAsync();
        }

        [TestMethod]
        public async Task Open_ShouldImportCuesheet_WhenUsingCuesheetfile()
        {
            var detailView = new DetailView(TestPage);
            var appBar = new AppBar(TestPage);
            await detailView.GotoAsync();
            await appBar.OpenFileAsync("Sample_Cuesheet.cue");
            await Expect(detailView.CuesheetArtistInput).ToHaveValueAsync("Sample CD Artist");
            await Expect(detailView.CuesheetTitleInput).ToHaveValueAsync("Sample CD Title");
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Select row 2 Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Select row 3 Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""3""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Select row 4 Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""4""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Select row 5 Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""5""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Select row 6 Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""6""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Select row 7 Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""7""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Select row 8 Sample Artist 8 Clear Sample Title 8 Clear 00:45:54"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""8""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell:
        - textbox
      - cell:
        - textbox
      - cell:
        - button
  - rowgroup:
    - row");
            await appBar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Paragraph).Filter(new() { HasText = "Tracks has invalid Count (0)!" })).ToBeVisibleAsync();
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WhenUsingText()
        {
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            var text = String.Join(Environment.NewLine, File.ReadAllLines("Sample_Inputfile.txt"));
            await importView.ImportTextAsync(text);
            await importView.Analyze();
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Select row 2 Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Select row 3 Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""3""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Select row 4 Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""4""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Select row 5 Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""5""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Select row 6 Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""6""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Select row 7 Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""7""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Select row 8 Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""8""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
      - cell:
        - button
  - rowgroup:
    - row");
        }
    }
}
