//This file is part of AudioCuesheetEditor.

//AudioCuesheetEditor is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.

//AudioCuesheetEditor is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with Foobar.  If not, see
//<http: //www.gnu.org/licenses />.
using AudioCuesheetEditor.End2EndTests.Models;
using Microsoft.Playwright;

namespace AudioCuesheetEditor.End2EndTests.Tests.Desktop
{
    [TestClass]
    public class TracingTest : PlaywrightTestBase
    {
        [TestMethod]
        public async Task UndoRedo_ShouldRestoreTrackState_WhenUndoAndRedoAreUsed()
        {
            var bar = new AppBar(TestPage);
            var detailView = new DetailView(TestPage);
            await detailView.GotoAsync();
            await detailView.AddTrackAsync();
            await detailView.EditTrackAsync("Test Artist 1");
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await detailView.EditTrackAsync(title: "Test Title 1");
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await bar.UndoAsync();
            await bar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 00:00:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell:
        - textbox
        - button
      - cell:
        - textbox
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell:
        - textbox
      - cell:
        - textbox
      - cell
  - rowgroup:
    - row");
            await Expect(bar.RedoButton).ToBeEnabledAsync();
            await bar.RedoAsync();
            await bar.RedoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Test Artist 1 Clear Test Title 1 Clear 00:00:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Test Artist 1 Clear"":
        - textbox: Test Artist 1
        - button ""Clear""
        - button
      - cell ""Test Title 1 Clear"":
        - textbox: Test Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell:
        - textbox
      - cell:
        - textbox
      - cell
  - rowgroup:
    - row");
            await detailView.EditTrackAsync("Mozart", "Eine kleine Nachtmusik");
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Mozart Clear Eine kleine Nachtmusik Clear 00:00:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Mozart Clear"":
        - textbox: Mozart
        - button ""Clear""
        - button
      - cell ""Eine kleine Nachtmusik Clear"":
        - textbox: Eine kleine Nachtmusik
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell:
        - textbox
      - cell:
        - textbox
      - cell
  - rowgroup:
    - row");
            await bar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Mozart Clear Test Title 1 Clear 00:00:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Mozart Clear"":
        - textbox: Mozart
        - button ""Clear""
        - button
      - cell ""Test Title 1 Clear"":
        - textbox: Test Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell:
        - textbox
      - cell:
        - textbox
      - cell
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task UndoRedo_ShouldRestoreTrackState_WhenModalEdit()
        {
            var bar = new AppBar(TestPage);
            var detailView = new DetailView(TestPage);
            await detailView.GotoAsync();
            await detailView.AddTrackAsync();
            await detailView.SelectTracksAsync([1]);
            await detailView.EditTracksModalAsync("Test Track Artist 1", "Test Track Title 1", "00:02:23", ["channel audio (4CH)", "Serial copy management system"]);
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows"" [checked]
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Test Track Artist 1 Clear Test Track Title 1 Clear 00:00:00 00:02:23 00:02:23"" [selected]:
      - cell ""Select row"":
        - checkbox ""Select row"" [checked]
        - text: Select row
      - cell ""1""
      - cell ""Test Track Artist 1 Clear"":
        - textbox: Test Track Artist 1
        - button ""Clear""
        - button
      - cell ""Test Track Title 1 Clear"":
        - textbox: Test Track Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:02:23"":
        - textbox: 00:02:23
      - cell ""00:02:23"":
        - textbox: 00:02:23
      - cell
  - rowgroup:
    - row");
            await bar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows"" [checked]
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 00:00:00 End has no value! Length has no value!"" [selected]:
      - cell ""Select row"":
        - checkbox ""Select row"" [checked]
        - text: Select row
      - cell ""1""
      - cell:
        - textbox
        - button
      - cell:
        - textbox
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""End has no value!"":
        - textbox
        - text: End has no value!
      - cell ""Length has no value!"":
        - textbox
        - text: Length has no value!
      - cell
  - rowgroup:
    - row");
            await bar.RedoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows"" [checked]
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Test Track Artist 1 Clear Test Track Title 1 Clear 00:00:00 00:02:23 00:02:23"" [selected]:
      - cell ""Select row"":
        - checkbox ""Select row"" [checked]
        - text: Select row
      - cell ""1""
      - cell ""Test Track Artist 1 Clear"":
        - textbox: Test Track Artist 1
        - button ""Clear""
        - button
      - cell ""Test Track Title 1 Clear"":
        - textbox: Test Track Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:02:23"":
        - textbox: 00:02:23
      - cell ""00:02:23"":
        - textbox: 00:02:23
      - cell
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task UndoRedo_ShouldRestoreCuesheet_WhenUsingImport()
        {
            var bar = new AppBar(TestPage);
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Textimport with Cuesheetdata.txt");
            await importView.SetSchemeCommonDataAsync("Artist - Title - ");
            await importView.SelectSchemeCommonDataPlaceholderAsync("Cataloguenumber");
            await importView.Analyze();
            await Expect(bar.UndoButton).ToBeDisabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await importView.CompleteImportAsync();
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await bar.UndoAsync();
            await Expect(bar.UndoButton).ToBeDisabledAsync();
            await Expect(bar.RedoButton).ToBeEnabledAsync();
            await bar.RedoAsync();
            await Expect(importView.CuesheetArtistInput).ToHaveValueAsync("DJFreezeT");
            await Expect(importView.CuesheetTitleInput).ToHaveValueAsync("Rabbit Hole Mix");
            await Expect(importView.CatalogueNumberInput).ToHaveValueAsync("01 23456 78912 3");
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 Adriatique Clear X. Clear 00:00:00 00:05:24.2500000 00:05:24.2500000"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell ""Adriatique Clear"":
        - textbox: Adriatique
        - button ""Clear""
        - button
      - cell ""X. Clear"":
        - textbox: X.
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:24.2500000"":
        - textbox: 00:05:24.2500000
      - cell ""00:05:24.2500000"":
        - textbox: 00:05:24.2500000
      - cell
    - row ""Select row 2 Third Harmony Clear Fears And Dreams (Original Mix) Clear 00:05:24.2500000 00:10:39 00:05:14.7500000"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell ""Third Harmony Clear"":
        - textbox: Third Harmony
        - button ""Clear""
        - button
      - cell ""Fears And Dreams (Original Mix) Clear"":
        - textbox: Fears And Dreams (Original Mix)
        - button ""Clear""
        - button
      - cell ""00:05:24.2500000"":
        - textbox: 00:05:24.2500000
      - cell ""00:10:39"":
        - textbox: 00:10:39
      - cell ""00:05:14.7500000"":
        - textbox: 00:05:14.7500000
      - cell:
        - button
    - row ""Select row 3 Dele Sosimi Afrobeat Orchestra Clear Too Much Information (Laolu Remix; Edit) Clear 00:10:39 00:17:06 00:06:27"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""3""
      - cell ""Dele Sosimi Afrobeat Orchestra Clear"":
        - textbox: Dele Sosimi Afrobeat Orchestra
        - button ""Clear""
        - button
      - cell ""Too Much Information (Laolu Remix; Edit) Clear"":
        - textbox: Too Much Information (Laolu Remix; Edit)
        - button ""Clear""
        - button
      - cell ""00:10:39"":
        - textbox: 00:10:39
      - cell ""00:17:06"":
        - textbox: 00:17:06
      - cell ""00:06:27"":
        - textbox: 00:06:27
      - cell:
        - button
    - row ""Select row 4 Edem, Govan Clear Ankh (Onetwo MX Remix) Clear 00:17:06 00:23:21 00:06:15"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""4""
      - cell ""Edem, Govan Clear"":
        - textbox: Edem, Govan
        - button ""Clear""
        - button
      - cell ""Ankh (Onetwo MX Remix) Clear"":
        - textbox: Ankh (Onetwo MX Remix)
        - button ""Clear""
        - button
      - cell ""00:17:06"":
        - textbox: 00:17:06
      - cell ""00:23:21"":
        - textbox: 00:23:21
      - cell ""00:06:15"":
        - textbox: 00:06:15
      - cell:
        - button
    - row ""Select row 5 Jody Wisternoff Clear For All Time (feat. Hendrik Burkhard) (Extended Mix) Clear 00:23:21 00:29:02 00:05:41"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""5""
      - cell ""Jody Wisternoff Clear"":
        - textbox: Jody Wisternoff
        - button ""Clear""
        - button
      - cell ""For All Time (feat. Hendrik Burkhard) (Extended Mix) Clear"":
        - textbox: For All Time (feat. Hendrik Burkhard) (Extended Mix)
        - button ""Clear""
        - button
      - cell ""00:23:21"":
        - textbox: 00:23:21
      - cell ""00:29:02"":
        - textbox: 00:29:02
      - cell ""00:05:41"":
        - textbox: 00:05:41
      - cell:
        - button
    - row ""Select row 6 Einmusik Clear Bead (Original Mix) Clear 00:29:02 00:34:27 00:05:25"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""6""
      - cell ""Einmusik Clear"":
        - textbox: Einmusik
        - button ""Clear""
        - button
      - cell ""Bead (Original Mix) Clear"":
        - textbox: Bead (Original Mix)
        - button ""Clear""
        - button
      - cell ""00:29:02"":
        - textbox: 00:29:02
      - cell ""00:34:27"":
        - textbox: 00:34:27
      - cell ""00:05:25"":
        - textbox: 00:05:25
      - cell:
        - button
    - row ""Select row 7 Sebastien Leger Clear La Danse du Scorpion Clear 00:34:27 00:40:59 00:06:32"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""7""
      - cell ""Sebastien Leger Clear"":
        - textbox: Sebastien Leger
        - button ""Clear""
        - button
      - cell ""La Danse du Scorpion Clear"":
        - textbox: La Danse du Scorpion
        - button ""Clear""
        - button
      - cell ""00:34:27"":
        - textbox: 00:34:27
      - cell ""00:40:59"":
        - textbox: 00:40:59
      - cell ""00:06:32"":
        - textbox: 00:06:32
      - cell:
        - button
    - row ""Select row 8 Paul Thomas & Solid Stone Clear La Bombo (Solid Stone Remix) Clear 00:40:59 00:46:19 00:05:20"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""8""
      - cell ""Paul Thomas & Solid Stone Clear"":
        - textbox: Paul Thomas & Solid Stone
        - button ""Clear""
        - button
      - cell ""La Bombo (Solid Stone Remix) Clear"":
        - textbox: La Bombo (Solid Stone Remix)
        - button ""Clear""
        - button
      - cell ""00:40:59"":
        - textbox: 00:40:59
      - cell ""00:46:19"":
        - textbox: 00:46:19
      - cell ""00:05:20"":
        - textbox: 00:05:20
      - cell:
        - button
    - row ""Select row 9 GusGus Clear Crossfade (Maceo Plex Mix) Clear 00:46:19 00:52:20 00:06:01"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""9""
      - cell ""GusGus Clear"":
        - textbox: GusGus
        - button ""Clear""
        - button
      - cell ""Crossfade (Maceo Plex Mix) Clear"":
        - textbox: Crossfade (Maceo Plex Mix)
        - button ""Clear""
        - button
      - cell ""00:46:19"":
        - textbox: 00:46:19
      - cell ""00:52:20"":
        - textbox: 00:52:20
      - cell ""00:06:01"":
        - textbox: 00:06:01
      - cell:
        - button
    - row ""Select row 10 Klangkarussell Clear Time (Original Mix) Clear 00:52:20 00:56:19 00:03:59"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""10""
      - cell ""Klangkarussell Clear"":
        - textbox: Klangkarussell
        - button ""Clear""
        - button
      - cell ""Time (Original Mix) Clear"":
        - textbox: Time (Original Mix)
        - button ""Clear""
        - button
      - cell ""00:52:20"":
        - textbox: 00:52:20
      - cell ""00:56:19"":
        - textbox: 00:56:19
      - cell ""00:03:59"":
        - textbox: 00:03:59
      - cell:
        - button
    - row ""Select row 11 Anysense & Un:said Clear Missing Path (Original Mix) Clear 00:56:19 01:01:41 00:05:22"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""11""
      - cell ""Anysense & Un:said Clear"":
        - textbox: Anysense & Un:said
        - button ""Clear""
        - button
      - cell ""Missing Path (Original Mix) Clear"":
        - textbox: Missing Path (Original Mix)
        - button ""Clear""
        - button
      - cell ""00:56:19"":
        - textbox: 00:56:19
      - cell ""01:01:41"":
        - textbox: 01:01:41
      - cell ""00:05:22"":
        - textbox: 00:05:22
      - cell:
        - button
    - row ""Select row 12 Space Food Clear Bombay Clear 01:01:41 01:06:33 00:04:52"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""12""
      - cell ""Space Food Clear"":
        - textbox: Space Food
        - button ""Clear""
        - button
      - cell ""Bombay Clear"":
        - textbox: Bombay
        - button ""Clear""
        - button
      - cell ""01:01:41"":
        - textbox: 01:01:41
      - cell ""01:06:33"":
        - textbox: 01:06:33
      - cell ""00:04:52"":
        - textbox: 00:04:52
      - cell:
        - button
    - row ""Select row 13 SHDW & Obscure Shape Clear Wächter der Nacht (Original Mix) Clear 01:06:33 01:11:04 00:04:31"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""13""
      - cell ""SHDW & Obscure Shape Clear"":
        - textbox: SHDW & Obscure Shape
        - button ""Clear""
        - button
      - cell ""Wächter der Nacht (Original Mix) Clear"":
        - textbox: Wächter der Nacht (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:06:33"":
        - textbox: 01:06:33
      - cell ""01:11:04"":
        - textbox: 01:11:04
      - cell ""00:04:31"":
        - textbox: 00:04:31
      - cell:
        - button
    - row ""Select row 14 HOSH Clear Karma Clear 01:11:04 01:15:28 00:04:24"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""14""
      - cell ""HOSH Clear"":
        - textbox: HOSH
        - button ""Clear""
        - button
      - cell ""Karma Clear"":
        - textbox: Karma
        - button ""Clear""
        - button
      - cell ""01:11:04"":
        - textbox: 01:11:04
      - cell ""01:15:28"":
        - textbox: 01:15:28
      - cell ""00:04:24"":
        - textbox: 00:04:24
      - cell:
        - button
    - row ""Select row 15 Alexey Union Clear Olympia (Original Mix) Clear 01:15:28 01:21:08 00:05:40"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""15""
      - cell ""Alexey Union Clear"":
        - textbox: Alexey Union
        - button ""Clear""
        - button
      - cell ""Olympia (Original Mix) Clear"":
        - textbox: Olympia (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:15:28"":
        - textbox: 01:15:28
      - cell ""01:21:08"":
        - textbox: 01:21:08
      - cell ""00:05:40"":
        - textbox: 00:05:40
      - cell:
        - button
    - row ""Select row 16 Paul Taylor Clear Afterglow Clear 01:21:08 01:25:38 00:04:30"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""16""
      - cell ""Paul Taylor Clear"":
        - textbox: Paul Taylor
        - button ""Clear""
        - button
      - cell ""Afterglow Clear"":
        - textbox: Afterglow
        - button ""Clear""
        - button
      - cell ""01:21:08"":
        - textbox: 01:21:08
      - cell ""01:25:38"":
        - textbox: 01:25:38
      - cell ""00:04:30"":
        - textbox: 00:04:30
      - cell:
        - button
    - row ""Select row 17 Philter Clear Stranger Clear 01:25:38 01:31:52 00:06:14"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""17""
      - cell ""Philter Clear"":
        - textbox: Philter
        - button ""Clear""
        - button
      - cell ""Stranger Clear"":
        - textbox: Stranger
        - button ""Clear""
        - button
      - cell ""01:25:38"":
        - textbox: 01:25:38
      - cell ""01:31:52"":
        - textbox: 01:31:52
      - cell ""00:06:14"":
        - textbox: 00:06:14
      - cell:
        - button
    - row ""Select row 18 Skizologic Clear Hypersphere (Original Mix) Clear 01:31:52 01:36:40 00:04:48"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""18""
      - cell ""Skizologic Clear"":
        - textbox: Skizologic
        - button ""Clear""
        - button
      - cell ""Hypersphere (Original Mix) Clear"":
        - textbox: Hypersphere (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:31:52"":
        - textbox: 01:31:52
      - cell ""01:36:40"":
        - textbox: 01:36:40
      - cell ""00:04:48"":
        - textbox: 00:04:48
      - cell:
        - button
    - row ""Select row 19 Thomas Schumacher, Caitlin Clear All of You (Remix) Clear 01:36:40 01:42:16 00:05:36"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""19""
      - cell ""Thomas Schumacher, Caitlin Clear"":
        - textbox: Thomas Schumacher, Caitlin
        - button ""Clear""
        - button
      - cell ""All of You (Remix) Clear"":
        - textbox: All of You (Remix)
        - button ""Clear""
        - button
      - cell ""01:36:40"":
        - textbox: 01:36:40
      - cell ""01:42:16"":
        - textbox: 01:42:16
      - cell ""00:05:36"":
        - textbox: 00:05:36
      - cell:
        - button
    - row ""Select row 20 A. Skomoroh Clear White Horse Conquest (Original Mix) Clear 01:42:16 01:47:04 00:04:48"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""20""
      - cell ""A. Skomoroh Clear"":
        - textbox: A. Skomoroh
        - button ""Clear""
        - button
      - cell ""White Horse Conquest (Original Mix) Clear"":
        - textbox: White Horse Conquest (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:42:16"":
        - textbox: 01:42:16
      - cell ""01:47:04"":
        - textbox: 01:47:04
      - cell ""00:04:48"":
        - textbox: 00:04:48
      - cell:
        - button
    - row ""Select row 21 Patrik Berg Clear Bright (Original Mix) Clear 01:47:04 01:52:37 00:05:33"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""21""
      - cell ""Patrik Berg Clear"":
        - textbox: Patrik Berg
        - button ""Clear""
        - button
      - cell ""Bright (Original Mix) Clear"":
        - textbox: Bright (Original Mix)
        - button ""Clear""
        - button
      - cell ""01:47:04"":
        - textbox: 01:47:04
      - cell ""01:52:37"":
        - textbox: 01:52:37
      - cell ""00:05:33"":
        - textbox: 00:05:33
      - cell:
        - button
    - row ""Select row 22 Hidden Empire Clear Bengal Clear 01:52:37 01:58:05 00:05:28"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""22""
      - cell ""Hidden Empire Clear"":
        - textbox: Hidden Empire
        - button ""Clear""
        - button
      - cell ""Bengal Clear"":
        - textbox: Bengal
        - button ""Clear""
        - button
      - cell ""01:52:37"":
        - textbox: 01:52:37
      - cell ""01:58:05"":
        - textbox: 01:58:05
      - cell ""00:05:28"":
        - textbox: 00:05:28
      - cell:
        - button
    - row ""Select row 23 Mario Ochoa Clear Levitate Clear 01:58:05 02:03:00 00:04:55"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""23""
      - cell ""Mario Ochoa Clear"":
        - textbox: Mario Ochoa
        - button ""Clear""
        - button
      - cell ""Levitate Clear"":
        - textbox: Levitate
        - button ""Clear""
        - button
      - cell ""01:58:05"":
        - textbox: 01:58:05
      - cell ""02:03:00"":
        - textbox: 02:03:00
      - cell ""00:04:55"":
        - textbox: 00:04:55
      - cell:
        - button
    - row ""Select row 24 Raul Facio Clear Eyes Wide Shut (Original Mix) Clear 02:03:00 02:08:21 00:05:21"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""24""
      - cell ""Raul Facio Clear"":
        - textbox: Raul Facio
        - button ""Clear""
        - button
      - cell ""Eyes Wide Shut (Original Mix) Clear"":
        - textbox: Eyes Wide Shut (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:03:00"":
        - textbox: 02:03:00
      - cell ""02:08:21"":
        - textbox: 02:08:21
      - cell ""00:05:21"":
        - textbox: 00:05:21
      - cell:
        - button
    - row ""Select row 25 Soolver Clear Regular (Original Mix) Clear 02:08:21 02:14:31 00:06:10"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""25""
      - cell ""Soolver Clear"":
        - textbox: Soolver
        - button ""Clear""
        - button
      - cell ""Regular (Original Mix) Clear"":
        - textbox: Regular (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:08:21"":
        - textbox: 02:08:21
      - cell ""02:14:31"":
        - textbox: 02:14:31
      - cell ""00:06:10"":
        - textbox: 00:06:10
      - cell:
        - button
    - row ""Select row 26 Weska Clear EQ64 (Original Mix) Clear 02:14:31 02:18:35 00:04:04"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""26""
      - cell ""Weska Clear"":
        - textbox: Weska
        - button ""Clear""
        - button
      - cell ""EQ64 (Original Mix) Clear"":
        - textbox: EQ64 (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:14:31"":
        - textbox: 02:14:31
      - cell ""02:18:35"":
        - textbox: 02:18:35
      - cell ""00:04:04"":
        - textbox: 00:04:04
      - cell:
        - button
    - row ""Select row 27 Tempo Giusto Clear The Fall (Extended Mix) Clear 02:18:35 02:24:12 00:05:37"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""27""
      - cell ""Tempo Giusto Clear"":
        - textbox: Tempo Giusto
        - button ""Clear""
        - button
      - cell ""The Fall (Extended Mix) Clear"":
        - textbox: The Fall (Extended Mix)
        - button ""Clear""
        - button
      - cell ""02:18:35"":
        - textbox: 02:18:35
      - cell ""02:24:12"":
        - textbox: 02:24:12
      - cell ""00:05:37"":
        - textbox: 00:05:37
      - cell:
        - button
    - row ""Select row 28 Vlind & Asteroid & Gary Leroy Clear Trinity (Extended Mix) Clear 02:24:12 02:29:38 00:05:26"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""28""
      - cell ""Vlind & Asteroid & Gary Leroy Clear"":
        - textbox: Vlind & Asteroid & Gary Leroy
        - button ""Clear""
        - button
      - cell ""Trinity (Extended Mix) Clear"":
        - textbox: Trinity (Extended Mix)
        - button ""Clear""
        - button
      - cell ""02:24:12"":
        - textbox: 02:24:12
      - cell ""02:29:38"":
        - textbox: 02:29:38
      - cell ""00:05:26"":
        - textbox: 00:05:26
      - cell:
        - button
    - row ""Select row 29 Astral Legacy Clear Vaveyla (Original Mix) Clear 02:29:38 02:32:52 00:03:14"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""29""
      - cell ""Astral Legacy Clear"":
        - textbox: Astral Legacy
        - button ""Clear""
        - button
      - cell ""Vaveyla (Original Mix) Clear"":
        - textbox: Vaveyla (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:29:38"":
        - textbox: 02:29:38
      - cell ""02:32:52"":
        - textbox: 02:32:52
      - cell ""00:03:14"":
        - textbox: 00:03:14
      - cell:
        - button
    - row ""Select row 30 Gerrox Clear Chakra (Original Mix) Clear 02:32:52 02:37:00 00:04:08"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""30""
      - cell ""Gerrox Clear"":
        - textbox: Gerrox
        - button ""Clear""
        - button
      - cell ""Chakra (Original Mix) Clear"":
        - textbox: Chakra (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:32:52"":
        - textbox: 02:32:52
      - cell ""02:37:00"":
        - textbox: 02:37:00
      - cell ""00:04:08"":
        - textbox: 00:04:08
      - cell:
        - button
    - row ""Select row 31 Charlotte De Witte Clear Pattern Clear 02:37:00 02:41:55 00:04:55"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""31""
      - cell ""Charlotte De Witte Clear"":
        - textbox: Charlotte De Witte
        - button ""Clear""
        - button
      - cell ""Pattern Clear"":
        - textbox: Pattern
        - button ""Clear""
        - button
      - cell ""02:37:00"":
        - textbox: 02:37:00
      - cell ""02:41:55"":
        - textbox: 02:41:55
      - cell ""00:04:55"":
        - textbox: 00:04:55
      - cell:
        - button
    - row ""Select row 32 Space Food Clear Amabey Clear 02:41:55 02:46:55 00:05:00"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""32""
      - cell ""Space Food Clear"":
        - textbox: Space Food
        - button ""Clear""
        - button
      - cell ""Amabey Clear"":
        - textbox: Amabey
        - button ""Clear""
        - button
      - cell ""02:41:55"":
        - textbox: 02:41:55
      - cell ""02:46:55"":
        - textbox: 02:46:55
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell:
        - button
    - row ""Select row 33 ARTBAT Clear Papilion (Original Mix) Clear 02:46:55 02:51:13 00:04:18"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""33""
      - cell ""ARTBAT Clear"":
        - textbox: ARTBAT
        - button ""Clear""
        - button
      - cell ""Papilion (Original Mix) Clear"":
        - textbox: Papilion (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:46:55"":
        - textbox: 02:46:55
      - cell ""02:51:13"":
        - textbox: 02:51:13
      - cell ""00:04:18"":
        - textbox: 00:04:18
      - cell:
        - button
    - row ""Select row 34 PETER PAHN Clear Enjoy Infinity (Original Mix) Clear 02:51:13 02:56:08 00:04:55"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""34""
      - cell ""PETER PAHN Clear"":
        - textbox: PETER PAHN
        - button ""Clear""
        - button
      - cell ""Enjoy Infinity (Original Mix) Clear"":
        - textbox: Enjoy Infinity (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:51:13"":
        - textbox: 02:51:13
      - cell ""02:56:08"":
        - textbox: 02:56:08
      - cell ""00:04:55"":
        - textbox: 00:04:55
      - cell:
        - button
    - row ""Select row 35 Solitek Clear Instinct (Original Mix) Clear 02:56:08 03:00:57 00:04:49"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""35""
      - cell ""Solitek Clear"":
        - textbox: Solitek
        - button ""Clear""
        - button
      - cell ""Instinct (Original Mix) Clear"":
        - textbox: Instinct (Original Mix)
        - button ""Clear""
        - button
      - cell ""02:56:08"":
        - textbox: 02:56:08
      - cell ""03:00:57"":
        - textbox: 03:00:57
      - cell ""00:04:49"":
        - textbox: 00:04:49
      - cell:
        - button
    - row ""Select row 36 Veerus Clear Heavy Clear 03:00:57 03:05:19 00:04:22"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""36""
      - cell ""Veerus Clear"":
        - textbox: Veerus
        - button ""Clear""
        - button
      - cell ""Heavy Clear"":
        - textbox: Heavy
        - button ""Clear""
        - button
      - cell ""03:00:57"":
        - textbox: 03:00:57
      - cell ""03:05:19"":
        - textbox: 03:05:19
      - cell ""00:04:22"":
        - textbox: 00:04:22
      - cell:
        - button
    - row ""Select row 37 Secret Cinema & Reinier Zonneveld Clear Pain Thing (Original Mix) Clear 03:05:19 03:09:38 00:04:19"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""37""
      - cell ""Secret Cinema & Reinier Zonneveld Clear"":
        - textbox: Secret Cinema & Reinier Zonneveld
        - button ""Clear""
        - button
      - cell ""Pain Thing (Original Mix) Clear"":
        - textbox: Pain Thing (Original Mix)
        - button ""Clear""
        - button
      - cell ""03:05:19"":
        - textbox: 03:05:19
      - cell ""03:09:38"":
        - textbox: 03:09:38
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Select row 38 Amelie Lens Clear Hypnotized Clear 03:09:38 03:13:13 00:03:35"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""38""
      - cell ""Amelie Lens Clear"":
        - textbox: Amelie Lens
        - button ""Clear""
        - button
      - cell ""Hypnotized Clear"":
        - textbox: Hypnotized
        - button ""Clear""
        - button
      - cell ""03:09:38"":
        - textbox: 03:09:38
      - cell ""03:13:13"":
        - textbox: 03:13:13
      - cell ""00:03:35"":
        - textbox: 00:03:35
      - cell:
        - button
    - row ""Select row 39 Nikolay Kirov Clear Chasing the Sun (Original Mix) Clear 03:13:13"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""39""
      - cell ""Nikolay Kirov Clear"":
        - textbox: Nikolay Kirov
        - button ""Clear""
        - button
      - cell ""Chasing the Sun (Original Mix) Clear"":
        - textbox: Chasing the Sun (Original Mix)
        - button ""Clear""
        - button
      - cell ""03:13:13"":
        - textbox: 03:13:13
      - cell:
        - textbox
      - cell:
        - textbox
      - cell:
        - button
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task UndoRedo_ShouldRestoreTrackState_WhenUndoWithAudiofile()
        {
            var bar = new AppBar(TestPage);
            var detailView = new DetailView(TestPage);
            await detailView.GotoAsync();
            await detailView.AddTrackAsync();
            await detailView.AudiofileInput.SetInputFilesAsync("Kalimba.mp3");
            await detailView.AddTrackAsync();
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 00:00:00 End has no value! Length has no value!"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell:
        - textbox
        - button
      - cell:
        - textbox
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""End has no value!"":
        - textbox
        - text: End has no value!
      - cell ""Length has no value!"":
        - textbox
        - text: Length has no value!
      - cell
    - row ""Select row 2 00:05:48.0608330"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""2""
      - cell:
        - textbox
        - button
      - cell:
        - textbox
        - button
      - cell:
        - textbox
      - cell ""00:05:48.0608330"":
        - textbox: 00:05:48.0608330
      - cell:
        - textbox
      - cell:
        - button
  - rowgroup:
    - row");
            await bar.UndoAsync();
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeEnabledAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - 'row ""Select all rows # Artist Title Begin End Length Status""':
      - columnheader ""Select all rows"":
        - checkbox ""Select all rows""
      - columnheader ""#""
      - columnheader ""Artist""
      - columnheader ""Title""
      - columnheader ""Begin""
      - columnheader ""End""
      - columnheader ""Length""
      - columnheader ""Status""
  - rowgroup:
    - row ""Select row 1 00:00:00 00:05:48.0608330 00:05:48.0608330"":
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""1""
      - cell:
        - textbox
        - button
      - cell:
        - textbox
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:48.0608330"":
        - textbox: 00:05:48.0608330
      - cell ""00:05:48.0608330"":
        - textbox: 00:05:48.0608330
      - cell
  - rowgroup:
    - row");
        }
    }
}