//This file is part of AudioCuesheetEditor.

//AudioCuesheetEditor is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.

//AudioCuesheetEditor is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with Foobar.  If not, see
//<http: //www.gnu.org/licenses />.
using AudioCuesheetEditor.End2EndTests.Models;
using Microsoft.Playwright;

namespace AudioCuesheetEditor.End2EndTests.Tests.Smartphone
{
    [TestClass]
    public class TracingTest : PlaywrightTestBase
    {
        protected override string? DeviceName => "iPhone 13";

        [TestMethod]
        public async Task UndoRedo_ShouldRestoreTrackState_WhenUndoAndRedoAreUsed()
        {
            var bar = new AppBar(TestPage);
            var detailView = new DetailView(TestPage);
            await detailView.GotoAsync();
            await detailView.AddAudiofileAsync();
            await detailView.AddTrackAsync(0);
            await detailView.EditTrackAsync("Test Artist 1");
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await detailView.EditTrackAsync(title: "Test Title 1");
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await bar.UndoAsync();
            await bar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Title Begin 00:00:00 End Length Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 1""
      - cell ""Artist"":
        - text: Artist
        - combobox
        - button
      - cell ""Title"":
        - text: Title
        - combobox
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End"":
        - text: End
        - textbox
      - cell ""Length"":
        - text: Length
        - textbox
      - cell ""Status""");
            await Expect(bar.RedoButton).ToBeEnabledAsync();
            await bar.RedoAsync();
            await bar.RedoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Test Artist 1 Clear Title Test Title 1 Clear Begin 00:00:00 End Length Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 1""
      - cell ""Artist Test Artist 1 Clear"":
        - text: Artist
        - combobox: Test Artist 1
        - button ""Clear""
        - button
      - cell ""Title Test Title 1 Clear"":
        - text: Title
        - combobox: Test Title 1
        - button ""Clear""
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End"":
        - text: End
        - textbox
      - cell ""Length"":
        - text: Length
        - textbox
      - cell ""Status""");
            await detailView.EditTrackAsync("Mozart", "Eine kleine Nachtmusik");
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Mozart Clear Title Eine kleine Nachtmusik Clear Begin 00:00:00 End Length Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 1""
      - cell ""Artist Mozart Clear"":
        - text: Artist
        - combobox: Mozart
        - button ""Clear""
        - button
      - cell ""Title Eine kleine Nachtmusik Clear"":
        - text: Title
        - combobox: Eine kleine Nachtmusik
        - button ""Clear""
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End"":
        - text: End
        - textbox
      - cell ""Length"":
        - text: Length
        - textbox
      - cell ""Status""");
            await bar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Mozart Clear Title Test Title 1 Clear Begin 00:00:00 End Length Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 1""
      - cell ""Artist Mozart Clear"":
        - text: Artist
        - combobox: Mozart
        - button ""Clear""
        - button
      - cell ""Title Test Title 1 Clear"":
        - text: Title
        - combobox: Test Title 1
        - button ""Clear""
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End"":
        - text: End
        - textbox
      - cell ""Length"":
        - text: Length
        - textbox
      - cell ""Status""");
        }

        [TestMethod]
        public async Task UndoRedo_ShouldRestoreTrackState_WhenModalEdit()
        {
            var bar = new AppBar(TestPage);
            var detailView = new DetailView(TestPage);
            await detailView.GotoAsync();
            await detailView.AddAudiofileAsync();
            await detailView.AddTrackAsync(0);
            await detailView.SelectTracksAsync([1]);
            await detailView.EditTracksModalAsync("Test Track Artist 1", "Test Track Title 1", "00:02:23", ["channel audio (4CH)", "Serial copy management system"]);
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Test Track Artist 1 Clear Title Test Track Title 1 Clear Begin 00:00:00 End 00:02:23 Length 00:02:23 Status"" [selected]':
      - cell ""Select row"":
        - checkbox ""Select row"" [checked]
        - text: Select row
      - cell ""# 1""
      - cell ""Artist Test Track Artist 1 Clear"":
        - text: Artist
        - combobox: Test Track Artist 1
        - button ""Clear""
        - button
      - cell ""Title Test Track Title 1 Clear"":
        - text: Title
        - combobox: Test Track Title 1
        - button ""Clear""
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End 00:02:23"":
        - text: End
        - textbox: 00:02:23
      - cell ""Length 00:02:23"":
        - text: Length
        - textbox: 00:02:23
      - cell ""Status""");
            await bar.UndoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Title Begin 00:00:00 End Length Status"" [selected]':
      - cell ""Select row"":
        - checkbox ""Select row"" [checked]
        - text: Select row
      - cell ""# 1""
      - cell ""Artist"":
        - text: Artist
        - combobox
        - button
      - cell ""Title"":
        - text: Title
        - combobox
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End"":
        - text: End
        - textbox
      - cell ""Length"":
        - text: Length
        - textbox
      - cell ""Status""");
            await bar.RedoAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Test Track Artist 1 Clear Title Test Track Title 1 Clear Begin 00:00:00 End 00:02:23 Length 00:02:23 Status"" [selected]':
      - cell ""Select row"":
        - checkbox ""Select row"" [checked]
        - text: Select row
      - cell ""# 1""
      - cell ""Artist Test Track Artist 1 Clear"":
        - text: Artist
        - combobox: Test Track Artist 1
        - button ""Clear""
        - button
      - cell ""Title Test Track Title 1 Clear"":
        - text: Title
        - combobox: Test Track Title 1
        - button ""Clear""
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End 00:02:23"":
        - text: End
        - textbox: 00:02:23
      - cell ""Length 00:02:23"":
        - text: Length
        - textbox: 00:02:23
      - cell ""Status""");
        }

        [TestMethod]
        public async Task UndoRedo_ShouldRestoreCuesheet_WhenUsingImport()
        {
            var bar = new AppBar(TestPage);
            var importView = new ImportView(TestPage, DeviceName != null);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Textimport with Cuesheetdata.txt");
            await importView.SetSchemeCommonDataAsync("Artist - Title - ");
            await importView.SelectSchemeCommonDataPlaceholderAsync("Cataloguenumber");
            await importView.ClearSchemeAudiofilesAsync();
            await importView.Analyze();
            await Expect(bar.UndoButton).ToBeDisabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await importView.CompleteImportAsync();
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await bar.UndoAsync();
            await Expect(bar.UndoButton).ToBeDisabledAsync();
            await Expect(bar.RedoButton).ToBeEnabledAsync();
            await bar.RedoAsync();
            await Expect(importView.CuesheetArtistInput).ToHaveValueAsync("DJFreezeT");
            await Expect(importView.CuesheetTitleInput).ToHaveValueAsync("Rabbit Hole Mix");
            await Expect(importView.CatalogueNumberInput).ToHaveValueAsync("01 23456 78912 3");
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Adriatique Clear Title X. Clear Begin 00:00:00 End 00:05:24.2500000 Length 00:05:24.2500000 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 1""
      - cell ""Artist Adriatique Clear"":
        - text: Artist
        - combobox: Adriatique
        - button ""Clear""
        - button
      - cell ""Title X. Clear"":
        - text: Title
        - combobox: X.
        - button ""Clear""
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End 00:05:24.2500000"":
        - text: End
        - textbox: 00:05:24.2500000
      - cell ""Length 00:05:24.2500000"":
        - text: Length
        - textbox: 00:05:24.2500000
      - cell ""Status""
    - 'row ""Select row # 2 Artist Third Harmony Clear Title Fears And Dreams (Original Mix) Clear Begin 00:05:24.2500000 End 00:10:39 Length 00:05:14.7500000 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 2""
      - cell ""Artist Third Harmony Clear"":
        - text: Artist
        - combobox: Third Harmony
        - button ""Clear""
        - button
      - cell ""Title Fears And Dreams (Original Mix) Clear"":
        - text: Title
        - combobox: Fears And Dreams (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 00:05:24.2500000"":
        - text: Begin
        - textbox: 00:05:24.2500000
      - cell ""End 00:10:39"":
        - text: End
        - textbox: 00:10:39
      - cell ""Length 00:05:14.7500000"":
        - text: Length
        - textbox: 00:05:14.7500000
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 3 Artist Dele Sosimi Afrobeat Orchestra Clear Title Too Much Information (Laolu Remix; Edit) Clear Begin 00:10:39 End 00:17:06 Length 00:06:27 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 3""
      - cell ""Artist Dele Sosimi Afrobeat Orchestra Clear"":
        - text: Artist
        - combobox: Dele Sosimi Afrobeat Orchestra
        - button ""Clear""
        - button
      - cell ""Title Too Much Information (Laolu Remix; Edit) Clear"":
        - text: Title
        - combobox: Too Much Information (Laolu Remix; Edit)
        - button ""Clear""
        - button
      - cell ""Begin 00:10:39"":
        - text: Begin
        - textbox: 00:10:39
      - cell ""End 00:17:06"":
        - text: End
        - textbox: 00:17:06
      - cell ""Length 00:06:27"":
        - text: Length
        - textbox: 00:06:27
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 4 Artist Edem, Govan Clear Title Ankh (Onetwo MX Remix) Clear Begin 00:17:06 End 00:23:21 Length 00:06:15 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 4""
      - cell ""Artist Edem, Govan Clear"":
        - text: Artist
        - combobox: Edem, Govan
        - button ""Clear""
        - button
      - cell ""Title Ankh (Onetwo MX Remix) Clear"":
        - text: Title
        - combobox: Ankh (Onetwo MX Remix)
        - button ""Clear""
        - button
      - cell ""Begin 00:17:06"":
        - text: Begin
        - textbox: 00:17:06
      - cell ""End 00:23:21"":
        - text: End
        - textbox: 00:23:21
      - cell ""Length 00:06:15"":
        - text: Length
        - textbox: 00:06:15
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 5 Artist Jody Wisternoff Clear Title For All Time (feat. Hendrik Burkhard) (Extended Mix) Clear Begin 00:23:21 End 00:29:02 Length 00:05:41 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 5""
      - cell ""Artist Jody Wisternoff Clear"":
        - text: Artist
        - combobox: Jody Wisternoff
        - button ""Clear""
        - button
      - cell ""Title For All Time (feat. Hendrik Burkhard) (Extended Mix) Clear"":
        - text: Title
        - combobox: For All Time (feat. Hendrik Burkhard) (Extended Mix)
        - button ""Clear""
        - button
      - cell ""Begin 00:23:21"":
        - text: Begin
        - textbox: 00:23:21
      - cell ""End 00:29:02"":
        - text: End
        - textbox: 00:29:02
      - cell ""Length 00:05:41"":
        - text: Length
        - textbox: 00:05:41
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 6 Artist Einmusik Clear Title Bead (Original Mix) Clear Begin 00:29:02 End 00:34:27 Length 00:05:25 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 6""
      - cell ""Artist Einmusik Clear"":
        - text: Artist
        - combobox: Einmusik
        - button ""Clear""
        - button
      - cell ""Title Bead (Original Mix) Clear"":
        - text: Title
        - combobox: Bead (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 00:29:02"":
        - text: Begin
        - textbox: 00:29:02
      - cell ""End 00:34:27"":
        - text: End
        - textbox: 00:34:27
      - cell ""Length 00:05:25"":
        - text: Length
        - textbox: 00:05:25
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 7 Artist Sebastien Leger Clear Title La Danse du Scorpion Clear Begin 00:34:27 End 00:40:59 Length 00:06:32 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 7""
      - cell ""Artist Sebastien Leger Clear"":
        - text: Artist
        - combobox: Sebastien Leger
        - button ""Clear""
        - button
      - cell ""Title La Danse du Scorpion Clear"":
        - text: Title
        - combobox: La Danse du Scorpion
        - button ""Clear""
        - button
      - cell ""Begin 00:34:27"":
        - text: Begin
        - textbox: 00:34:27
      - cell ""End 00:40:59"":
        - text: End
        - textbox: 00:40:59
      - cell ""Length 00:06:32"":
        - text: Length
        - textbox: 00:06:32
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 8 Artist Paul Thomas & Solid Stone Clear Title La Bombo (Solid Stone Remix) Clear Begin 00:40:59 End 00:46:19 Length 00:05:20 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 8""
      - cell ""Artist Paul Thomas & Solid Stone Clear"":
        - text: Artist
        - combobox: Paul Thomas & Solid Stone
        - button ""Clear""
        - button
      - cell ""Title La Bombo (Solid Stone Remix) Clear"":
        - text: Title
        - combobox: La Bombo (Solid Stone Remix)
        - button ""Clear""
        - button
      - cell ""Begin 00:40:59"":
        - text: Begin
        - textbox: 00:40:59
      - cell ""End 00:46:19"":
        - text: End
        - textbox: 00:46:19
      - cell ""Length 00:05:20"":
        - text: Length
        - textbox: 00:05:20
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 9 Artist GusGus Clear Title Crossfade (Maceo Plex Mix) Clear Begin 00:46:19 End 00:52:20 Length 00:06:01 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 9""
      - cell ""Artist GusGus Clear"":
        - text: Artist
        - combobox: GusGus
        - button ""Clear""
        - button
      - cell ""Title Crossfade (Maceo Plex Mix) Clear"":
        - text: Title
        - combobox: Crossfade (Maceo Plex Mix)
        - button ""Clear""
        - button
      - cell ""Begin 00:46:19"":
        - text: Begin
        - textbox: 00:46:19
      - cell ""End 00:52:20"":
        - text: End
        - textbox: 00:52:20
      - cell ""Length 00:06:01"":
        - text: Length
        - textbox: 00:06:01
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 10 Artist Klangkarussell Clear Title Time (Original Mix) Clear Begin 00:52:20 End 00:56:19 Length 00:03:59 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 10""
      - cell ""Artist Klangkarussell Clear"":
        - text: Artist
        - combobox: Klangkarussell
        - button ""Clear""
        - button
      - cell ""Title Time (Original Mix) Clear"":
        - text: Title
        - combobox: Time (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 00:52:20"":
        - text: Begin
        - textbox: 00:52:20
      - cell ""End 00:56:19"":
        - text: End
        - textbox: 00:56:19
      - cell ""Length 00:03:59"":
        - text: Length
        - textbox: 00:03:59
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 11 Artist Anysense & Un:said Clear Title Missing Path (Original Mix) Clear Begin 00:56:19 End 01:01:41 Length 00:05:22 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 11""
      - cell ""Artist Anysense & Un:said Clear"":
        - text: Artist
        - combobox: Anysense & Un:said
        - button ""Clear""
        - button
      - cell ""Title Missing Path (Original Mix) Clear"":
        - text: Title
        - combobox: Missing Path (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 00:56:19"":
        - text: Begin
        - textbox: 00:56:19
      - cell ""End 01:01:41"":
        - text: End
        - textbox: 01:01:41
      - cell ""Length 00:05:22"":
        - text: Length
        - textbox: 00:05:22
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 12 Artist Space Food Clear Title Bombay Clear Begin 01:01:41 End 01:06:33 Length 00:04:52 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 12""
      - cell ""Artist Space Food Clear"":
        - text: Artist
        - combobox: Space Food
        - button ""Clear""
        - button
      - cell ""Title Bombay Clear"":
        - text: Title
        - combobox: Bombay
        - button ""Clear""
        - button
      - cell ""Begin 01:01:41"":
        - text: Begin
        - textbox: 01:01:41
      - cell ""End 01:06:33"":
        - text: End
        - textbox: 01:06:33
      - cell ""Length 00:04:52"":
        - text: Length
        - textbox: 00:04:52
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 13 Artist SHDW & Obscure Shape Clear Title Wächter der Nacht (Original Mix) Clear Begin 01:06:33 End 01:11:04 Length 00:04:31 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 13""
      - cell ""Artist SHDW & Obscure Shape Clear"":
        - text: Artist
        - combobox: SHDW & Obscure Shape
        - button ""Clear""
        - button
      - cell ""Title Wächter der Nacht (Original Mix) Clear"":
        - text: Title
        - combobox: Wächter der Nacht (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 01:06:33"":
        - text: Begin
        - textbox: 01:06:33
      - cell ""End 01:11:04"":
        - text: End
        - textbox: 01:11:04
      - cell ""Length 00:04:31"":
        - text: Length
        - textbox: 00:04:31
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 14 Artist HOSH Clear Title Karma Clear Begin 01:11:04 End 01:15:28 Length 00:04:24 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 14""
      - cell ""Artist HOSH Clear"":
        - text: Artist
        - combobox: HOSH
        - button ""Clear""
        - button
      - cell ""Title Karma Clear"":
        - text: Title
        - combobox: Karma
        - button ""Clear""
        - button
      - cell ""Begin 01:11:04"":
        - text: Begin
        - textbox: 01:11:04
      - cell ""End 01:15:28"":
        - text: End
        - textbox: 01:15:28
      - cell ""Length 00:04:24"":
        - text: Length
        - textbox: 00:04:24
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 15 Artist Alexey Union Clear Title Olympia (Original Mix) Clear Begin 01:15:28 End 01:21:08 Length 00:05:40 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 15""
      - cell ""Artist Alexey Union Clear"":
        - text: Artist
        - combobox: Alexey Union
        - button ""Clear""
        - button
      - cell ""Title Olympia (Original Mix) Clear"":
        - text: Title
        - combobox: Olympia (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 01:15:28"":
        - text: Begin
        - textbox: 01:15:28
      - cell ""End 01:21:08"":
        - text: End
        - textbox: 01:21:08
      - cell ""Length 00:05:40"":
        - text: Length
        - textbox: 00:05:40
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 16 Artist Paul Taylor Clear Title Afterglow Clear Begin 01:21:08 End 01:25:38 Length 00:04:30 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 16""
      - cell ""Artist Paul Taylor Clear"":
        - text: Artist
        - combobox: Paul Taylor
        - button ""Clear""
        - button
      - cell ""Title Afterglow Clear"":
        - text: Title
        - combobox: Afterglow
        - button ""Clear""
        - button
      - cell ""Begin 01:21:08"":
        - text: Begin
        - textbox: 01:21:08
      - cell ""End 01:25:38"":
        - text: End
        - textbox: 01:25:38
      - cell ""Length 00:04:30"":
        - text: Length
        - textbox: 00:04:30
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 17 Artist Philter Clear Title Stranger Clear Begin 01:25:38 End 01:31:52 Length 00:06:14 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 17""
      - cell ""Artist Philter Clear"":
        - text: Artist
        - combobox: Philter
        - button ""Clear""
        - button
      - cell ""Title Stranger Clear"":
        - text: Title
        - combobox: Stranger
        - button ""Clear""
        - button
      - cell ""Begin 01:25:38"":
        - text: Begin
        - textbox: 01:25:38
      - cell ""End 01:31:52"":
        - text: End
        - textbox: 01:31:52
      - cell ""Length 00:06:14"":
        - text: Length
        - textbox: 00:06:14
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 18 Artist Skizologic Clear Title Hypersphere (Original Mix) Clear Begin 01:31:52 End 01:36:40 Length 00:04:48 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 18""
      - cell ""Artist Skizologic Clear"":
        - text: Artist
        - combobox: Skizologic
        - button ""Clear""
        - button
      - cell ""Title Hypersphere (Original Mix) Clear"":
        - text: Title
        - combobox: Hypersphere (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 01:31:52"":
        - text: Begin
        - textbox: 01:31:52
      - cell ""End 01:36:40"":
        - text: End
        - textbox: 01:36:40
      - cell ""Length 00:04:48"":
        - text: Length
        - textbox: 00:04:48
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 19 Artist Thomas Schumacher, Caitlin Clear Title All of You (Remix) Clear Begin 01:36:40 End 01:42:16 Length 00:05:36 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 19""
      - cell ""Artist Thomas Schumacher, Caitlin Clear"":
        - text: Artist
        - combobox: Thomas Schumacher, Caitlin
        - button ""Clear""
        - button
      - cell ""Title All of You (Remix) Clear"":
        - text: Title
        - combobox: All of You (Remix)
        - button ""Clear""
        - button
      - cell ""Begin 01:36:40"":
        - text: Begin
        - textbox: 01:36:40
      - cell ""End 01:42:16"":
        - text: End
        - textbox: 01:42:16
      - cell ""Length 00:05:36"":
        - text: Length
        - textbox: 00:05:36
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 20 Artist A. Skomoroh Clear Title White Horse Conquest (Original Mix) Clear Begin 01:42:16 End 01:47:04 Length 00:04:48 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 20""
      - cell ""Artist A. Skomoroh Clear"":
        - text: Artist
        - combobox: A. Skomoroh
        - button ""Clear""
        - button
      - cell ""Title White Horse Conquest (Original Mix) Clear"":
        - text: Title
        - combobox: White Horse Conquest (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 01:42:16"":
        - text: Begin
        - textbox: 01:42:16
      - cell ""End 01:47:04"":
        - text: End
        - textbox: 01:47:04
      - cell ""Length 00:04:48"":
        - text: Length
        - textbox: 00:04:48
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 21 Artist Patrik Berg Clear Title Bright (Original Mix) Clear Begin 01:47:04 End 01:52:37 Length 00:05:33 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 21""
      - cell ""Artist Patrik Berg Clear"":
        - text: Artist
        - combobox: Patrik Berg
        - button ""Clear""
        - button
      - cell ""Title Bright (Original Mix) Clear"":
        - text: Title
        - combobox: Bright (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 01:47:04"":
        - text: Begin
        - textbox: 01:47:04
      - cell ""End 01:52:37"":
        - text: End
        - textbox: 01:52:37
      - cell ""Length 00:05:33"":
        - text: Length
        - textbox: 00:05:33
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 22 Artist Hidden Empire Clear Title Bengal Clear Begin 01:52:37 End 01:58:05 Length 00:05:28 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 22""
      - cell ""Artist Hidden Empire Clear"":
        - text: Artist
        - combobox: Hidden Empire
        - button ""Clear""
        - button
      - cell ""Title Bengal Clear"":
        - text: Title
        - combobox: Bengal
        - button ""Clear""
        - button
      - cell ""Begin 01:52:37"":
        - text: Begin
        - textbox: 01:52:37
      - cell ""End 01:58:05"":
        - text: End
        - textbox: 01:58:05
      - cell ""Length 00:05:28"":
        - text: Length
        - textbox: 00:05:28
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 23 Artist Mario Ochoa Clear Title Levitate Clear Begin 01:58:05 End 02:03:00 Length 00:04:55 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 23""
      - cell ""Artist Mario Ochoa Clear"":
        - text: Artist
        - combobox: Mario Ochoa
        - button ""Clear""
        - button
      - cell ""Title Levitate Clear"":
        - text: Title
        - combobox: Levitate
        - button ""Clear""
        - button
      - cell ""Begin 01:58:05"":
        - text: Begin
        - textbox: 01:58:05
      - cell ""End 02:03:00"":
        - text: End
        - textbox: 02:03:00
      - cell ""Length 00:04:55"":
        - text: Length
        - textbox: 00:04:55
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 24 Artist Raul Facio Clear Title Eyes Wide Shut (Original Mix) Clear Begin 02:03:00 End 02:08:21 Length 00:05:21 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 24""
      - cell ""Artist Raul Facio Clear"":
        - text: Artist
        - combobox: Raul Facio
        - button ""Clear""
        - button
      - cell ""Title Eyes Wide Shut (Original Mix) Clear"":
        - text: Title
        - combobox: Eyes Wide Shut (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:03:00"":
        - text: Begin
        - textbox: 02:03:00
      - cell ""End 02:08:21"":
        - text: End
        - textbox: 02:08:21
      - cell ""Length 00:05:21"":
        - text: Length
        - textbox: 00:05:21
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 25 Artist Soolver Clear Title Regular (Original Mix) Clear Begin 02:08:21 End 02:14:31 Length 00:06:10 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 25""
      - cell ""Artist Soolver Clear"":
        - text: Artist
        - combobox: Soolver
        - button ""Clear""
        - button
      - cell ""Title Regular (Original Mix) Clear"":
        - text: Title
        - combobox: Regular (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:08:21"":
        - text: Begin
        - textbox: 02:08:21
      - cell ""End 02:14:31"":
        - text: End
        - textbox: 02:14:31
      - cell ""Length 00:06:10"":
        - text: Length
        - textbox: 00:06:10
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 26 Artist Weska Clear Title EQ64 (Original Mix) Clear Begin 02:14:31 End 02:18:35 Length 00:04:04 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 26""
      - cell ""Artist Weska Clear"":
        - text: Artist
        - combobox: Weska
        - button ""Clear""
        - button
      - cell ""Title EQ64 (Original Mix) Clear"":
        - text: Title
        - combobox: EQ64 (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:14:31"":
        - text: Begin
        - textbox: 02:14:31
      - cell ""End 02:18:35"":
        - text: End
        - textbox: 02:18:35
      - cell ""Length 00:04:04"":
        - text: Length
        - textbox: 00:04:04
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 27 Artist Tempo Giusto Clear Title The Fall (Extended Mix) Clear Begin 02:18:35 End 02:24:12 Length 00:05:37 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 27""
      - cell ""Artist Tempo Giusto Clear"":
        - text: Artist
        - combobox: Tempo Giusto
        - button ""Clear""
        - button
      - cell ""Title The Fall (Extended Mix) Clear"":
        - text: Title
        - combobox: The Fall (Extended Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:18:35"":
        - text: Begin
        - textbox: 02:18:35
      - cell ""End 02:24:12"":
        - text: End
        - textbox: 02:24:12
      - cell ""Length 00:05:37"":
        - text: Length
        - textbox: 00:05:37
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 28 Artist Vlind & Asteroid & Gary Leroy Clear Title Trinity (Extended Mix) Clear Begin 02:24:12 End 02:29:38 Length 00:05:26 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 28""
      - cell ""Artist Vlind & Asteroid & Gary Leroy Clear"":
        - text: Artist
        - combobox: Vlind & Asteroid & Gary Leroy
        - button ""Clear""
        - button
      - cell ""Title Trinity (Extended Mix) Clear"":
        - text: Title
        - combobox: Trinity (Extended Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:24:12"":
        - text: Begin
        - textbox: 02:24:12
      - cell ""End 02:29:38"":
        - text: End
        - textbox: 02:29:38
      - cell ""Length 00:05:26"":
        - text: Length
        - textbox: 00:05:26
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 29 Artist Astral Legacy Clear Title Vaveyla (Original Mix) Clear Begin 02:29:38 End 02:32:52 Length 00:03:14 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 29""
      - cell ""Artist Astral Legacy Clear"":
        - text: Artist
        - combobox: Astral Legacy
        - button ""Clear""
        - button
      - cell ""Title Vaveyla (Original Mix) Clear"":
        - text: Title
        - combobox: Vaveyla (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:29:38"":
        - text: Begin
        - textbox: 02:29:38
      - cell ""End 02:32:52"":
        - text: End
        - textbox: 02:32:52
      - cell ""Length 00:03:14"":
        - text: Length
        - textbox: 00:03:14
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 30 Artist Gerrox Clear Title Chakra (Original Mix) Clear Begin 02:32:52 End 02:37:00 Length 00:04:08 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 30""
      - cell ""Artist Gerrox Clear"":
        - text: Artist
        - combobox: Gerrox
        - button ""Clear""
        - button
      - cell ""Title Chakra (Original Mix) Clear"":
        - text: Title
        - combobox: Chakra (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:32:52"":
        - text: Begin
        - textbox: 02:32:52
      - cell ""End 02:37:00"":
        - text: End
        - textbox: 02:37:00
      - cell ""Length 00:04:08"":
        - text: Length
        - textbox: 00:04:08
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 31 Artist Charlotte De Witte Clear Title Pattern Clear Begin 02:37:00 End 02:41:55 Length 00:04:55 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 31""
      - cell ""Artist Charlotte De Witte Clear"":
        - text: Artist
        - combobox: Charlotte De Witte
        - button ""Clear""
        - button
      - cell ""Title Pattern Clear"":
        - text: Title
        - combobox: Pattern
        - button ""Clear""
        - button
      - cell ""Begin 02:37:00"":
        - text: Begin
        - textbox: 02:37:00
      - cell ""End 02:41:55"":
        - text: End
        - textbox: 02:41:55
      - cell ""Length 00:04:55"":
        - text: Length
        - textbox: 00:04:55
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 32 Artist Space Food Clear Title Amabey Clear Begin 02:41:55 End 02:46:55 Length 00:05:00 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 32""
      - cell ""Artist Space Food Clear"":
        - text: Artist
        - combobox: Space Food
        - button ""Clear""
        - button
      - cell ""Title Amabey Clear"":
        - text: Title
        - combobox: Amabey
        - button ""Clear""
        - button
      - cell ""Begin 02:41:55"":
        - text: Begin
        - textbox: 02:41:55
      - cell ""End 02:46:55"":
        - text: End
        - textbox: 02:46:55
      - cell ""Length 00:05:00"":
        - text: Length
        - textbox: 00:05:00
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 33 Artist ARTBAT Clear Title Papilion (Original Mix) Clear Begin 02:46:55 End 02:51:13 Length 00:04:18 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 33""
      - cell ""Artist ARTBAT Clear"":
        - text: Artist
        - combobox: ARTBAT
        - button ""Clear""
        - button
      - cell ""Title Papilion (Original Mix) Clear"":
        - text: Title
        - combobox: Papilion (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:46:55"":
        - text: Begin
        - textbox: 02:46:55
      - cell ""End 02:51:13"":
        - text: End
        - textbox: 02:51:13
      - cell ""Length 00:04:18"":
        - text: Length
        - textbox: 00:04:18
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 34 Artist PETER PAHN Clear Title Enjoy Infinity (Original Mix) Clear Begin 02:51:13 End 02:56:08 Length 00:04:55 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 34""
      - cell ""Artist PETER PAHN Clear"":
        - text: Artist
        - combobox: PETER PAHN
        - button ""Clear""
        - button
      - cell ""Title Enjoy Infinity (Original Mix) Clear"":
        - text: Title
        - combobox: Enjoy Infinity (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:51:13"":
        - text: Begin
        - textbox: 02:51:13
      - cell ""End 02:56:08"":
        - text: End
        - textbox: 02:56:08
      - cell ""Length 00:04:55"":
        - text: Length
        - textbox: 00:04:55
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 35 Artist Solitek Clear Title Instinct (Original Mix) Clear Begin 02:56:08 End 03:00:57 Length 00:04:49 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 35""
      - cell ""Artist Solitek Clear"":
        - text: Artist
        - combobox: Solitek
        - button ""Clear""
        - button
      - cell ""Title Instinct (Original Mix) Clear"":
        - text: Title
        - combobox: Instinct (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 02:56:08"":
        - text: Begin
        - textbox: 02:56:08
      - cell ""End 03:00:57"":
        - text: End
        - textbox: 03:00:57
      - cell ""Length 00:04:49"":
        - text: Length
        - textbox: 00:04:49
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 36 Artist Veerus Clear Title Heavy Clear Begin 03:00:57 End 03:05:19 Length 00:04:22 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 36""
      - cell ""Artist Veerus Clear"":
        - text: Artist
        - combobox: Veerus
        - button ""Clear""
        - button
      - cell ""Title Heavy Clear"":
        - text: Title
        - combobox: Heavy
        - button ""Clear""
        - button
      - cell ""Begin 03:00:57"":
        - text: Begin
        - textbox: 03:00:57
      - cell ""End 03:05:19"":
        - text: End
        - textbox: 03:05:19
      - cell ""Length 00:04:22"":
        - text: Length
        - textbox: 00:04:22
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 37 Artist Secret Cinema & Reinier Zonneveld Clear Title Pain Thing (Original Mix) Clear Begin 03:05:19 End 03:09:38 Length 00:04:19 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 37""
      - cell ""Artist Secret Cinema & Reinier Zonneveld Clear"":
        - text: Artist
        - combobox: Secret Cinema & Reinier Zonneveld
        - button ""Clear""
        - button
      - cell ""Title Pain Thing (Original Mix) Clear"":
        - text: Title
        - combobox: Pain Thing (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 03:05:19"":
        - text: Begin
        - textbox: 03:05:19
      - cell ""End 03:09:38"":
        - text: End
        - textbox: 03:09:38
      - cell ""Length 00:04:19"":
        - text: Length
        - textbox: 00:04:19
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 38 Artist Amelie Lens Clear Title Hypnotized Clear Begin 03:09:38 End 03:13:13 Length 00:03:35 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 38""
      - cell ""Artist Amelie Lens Clear"":
        - text: Artist
        - combobox: Amelie Lens
        - button ""Clear""
        - button
      - cell ""Title Hypnotized Clear"":
        - text: Title
        - combobox: Hypnotized
        - button ""Clear""
        - button
      - cell ""Begin 03:09:38"":
        - text: Begin
        - textbox: 03:09:38
      - cell ""End 03:13:13"":
        - text: End
        - textbox: 03:13:13
      - cell ""Length 00:03:35"":
        - text: Length
        - textbox: 00:03:35
      - cell ""Status"":
        - text: Status
        - button
    - 'row ""Select row # 39 Artist Nikolay Kirov Clear Title Chasing the Sun (Original Mix) Clear Begin 03:13:13 End Length Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 39""
      - cell ""Artist Nikolay Kirov Clear"":
        - text: Artist
        - combobox: Nikolay Kirov
        - button ""Clear""
        - button
      - cell ""Title Chasing the Sun (Original Mix) Clear"":
        - text: Title
        - combobox: Chasing the Sun (Original Mix)
        - button ""Clear""
        - button
      - cell ""Begin 03:13:13"":
        - text: Begin
        - textbox: 03:13:13
      - cell ""End"":
        - text: End
        - textbox
      - cell ""Length"":
        - text: Length
        - textbox
      - cell ""Status"":
        - text: Status
        - button");
        }

        [TestMethod]
        public async Task UndoRedo_ShouldRestoreTrackState_WhenUndoWithAudiofile()
        {
            var bar = new AppBar(TestPage);
            var detailView = new DetailView(TestPage);
            await detailView.GotoAsync();
            await detailView.AddAudiofileAsync();
            await detailView.SetAudiofileInputFileAsync(0, "Kalimba.mp3");
            await detailView.AddTrackAsync(0);
            await detailView.AddTrackAsync(0);
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeDisabledAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Title Begin 00:00:00 End Length Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 1""
      - cell ""Artist"":
        - text: Artist
        - combobox
        - button
      - cell ""Title"":
        - text: Title
        - combobox
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End"":
        - text: End
        - textbox
      - cell ""Length"":
        - text: Length
        - textbox
      - cell ""Status""
    - 'row ""Select row # 2 Artist Title Begin End 00:05:48.0608330 Length Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 2""
      - cell ""Artist"":
        - text: Artist
        - combobox
        - button
      - cell ""Title"":
        - text: Title
        - combobox
        - button
      - cell ""Begin"":
        - text: Begin
        - textbox
      - cell ""End 00:05:48.0608330"":
        - text: End
        - textbox: 00:05:48.0608330
      - cell ""Length"":
        - text: Length
        - textbox
      - cell ""Status"":
        - text: Status
        - button");
            await bar.UndoAsync();
            await Expect(bar.UndoButton).ToBeEnabledAsync();
            await Expect(bar.RedoButton).ToBeEnabledAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup
  - rowgroup:
    - 'row ""Select row # 1 Artist Title Begin 00:00:00 End 00:05:48.0608330 Length 00:05:48.0608330 Status""':
      - cell ""Select row"":
        - checkbox ""Select row""
        - text: Select row
      - cell ""# 1""
      - cell ""Artist"":
        - text: Artist
        - combobox
        - button
      - cell ""Title"":
        - text: Title
        - combobox
        - button
      - cell ""Begin 00:00:00"":
        - text: Begin
        - textbox: 00:00:00
      - cell ""End 00:05:48.0608330"":
        - text: End
        - textbox: 00:05:48.0608330
      - cell ""Length 00:05:48.0608330"":
        - text: Length
        - textbox: 00:05:48.0608330
      - cell ""Status""");
        }
    }
}
