//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioCuesheetEditor.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioCuesheetEditor.Shared.ResourceFiles.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort ähnelt.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About AudioCuesheetEditor ähnelt.
        /// </summary>
        public static string AboutAudioCuesheetEditor {
            get {
                return ResourceManager.GetString("AboutAudioCuesheetEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add identifier to import scheme ähnelt.
        /// </summary>
        public static string AddIdentifierToImportScheme {
            get {
                return ResourceManager.GetString("AddIdentifierToImportScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new export profile ähnelt.
        /// </summary>
        public static string AddNewExportProfile {
            get {
                return ResourceManager.GetString("AddNewExportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new track ähnelt.
        /// </summary>
        public static string Addnewtrack {
            get {
                return ResourceManager.GetString("Addnewtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add placeholder to the export footer scheme ähnelt.
        /// </summary>
        public static string AddPlaceholderToExportSchemeFooter {
            get {
                return ResourceManager.GetString("AddPlaceholderToExportSchemeFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add placeholder to the export head scheme ähnelt.
        /// </summary>
        public static string AddPlaceholderToExportSchemeHead {
            get {
                return ResourceManager.GetString("AddPlaceholderToExportSchemeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add placeholder to the export track scheme ähnelt.
        /// </summary>
        public static string AddPlaceholderToExportSchemeTrack {
            get {
                return ResourceManager.GetString("AddPlaceholderToExportSchemeTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Artist ähnelt.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audiofile ähnelt.
        /// </summary>
        public static string Audiofile {
            get {
                return ResourceManager.GetString("Audiofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio player ähnelt.
        /// </summary>
        public static string AudioPlayer {
            get {
                return ResourceManager.GetString("AudioPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Begin ähnelt.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Catalogue number ähnelt.
        /// </summary>
        public static string CatalogueNumber {
            get {
                return ResourceManager.GetString("CatalogueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cataloguenumber contains non digits. ähnelt.
        /// </summary>
        public static string CataloguenumberContainsNonDigits {
            get {
                return ResourceManager.GetString("CataloguenumberContainsNonDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CD artist ähnelt.
        /// </summary>
        public static string CDArtist {
            get {
                return ResourceManager.GetString("CDArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CD Textfile ähnelt.
        /// </summary>
        public static string CDTextfile {
            get {
                return ResourceManager.GetString("CDTextfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CD title ähnelt.
        /// </summary>
        public static string CDTitle {
            get {
                return ResourceManager.GetString("CDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;strong&gt;Choose files&lt;/strong&gt;&lt;span&gt; or drag them here&lt;/span&gt; ähnelt.
        /// </summary>
        public static string ChooseFileOrDrag {
            get {
                return ResourceManager.GetString("ChooseFileOrDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete all tracks? This can not be reversed. ähnelt.
        /// </summary>
        public static string ConfirmDeleteOfAllTracks {
            get {
                return ResourceManager.GetString("ConfirmDeleteOfAllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to import this file? This can not be reversed and unsaved changes are lost! ähnelt.
        /// </summary>
        public static string ConfirmImportCuesheet {
            get {
                return ResourceManager.GetString("ConfirmImportCuesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirmation required ähnelt.
        /// </summary>
        public static string ConfirmRequired {
            get {
                return ResourceManager.GetString("ConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to reset the cuesheet? This can not be reversed. ähnelt.
        /// </summary>
        public static string ConfirmResetCuesheet {
            get {
                return ResourceManager.GetString("ConfirmResetCuesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please confirm, that you want to restart the whole application. All data will be lost if not saved before! ähnelt.
        /// </summary>
        public static string ConfirmRestartOfApplication {
            get {
                return ResourceManager.GetString("ConfirmRestartOfApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a Cuesheet ähnelt.
        /// </summary>
        public static string CreateCuesheet {
            get {
                return ResourceManager.GetString("CreateCuesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creation of Cuesheet can be done very easily and fast using the standard GUI without import of files. To do so, enter the CD artist and CD title in the appropriate fields. Also select an audio file on your computer by draging the file from file explorer to the drop zone or manually selecting the file via file chooser. &lt;br /&gt;&lt;img src=&quot;images/CreateCuesheet1.png&quot;/&gt;&lt;br/&gt;Afterwards you need to insert a track by clickin the &quot;Add new track&quot; button. A new track is added and you can edit its properties like Artist, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string CreateCuesheetText {
            get {
                return ResourceManager.GetString("CreateCuesheetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cuesheet data ähnelt.
        /// </summary>
        public static string CuesheetData {
            get {
                return ResourceManager.GetString("CuesheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import of Cuesheet ähnelt.
        /// </summary>
        public static string CuesheetfileImport {
            get {
                return ResourceManager.GetString("CuesheetfileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cuesheet result ähnelt.
        /// </summary>
        public static string CuesheetResult {
            get {
                return ResourceManager.GetString("CuesheetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cuesheet tracks ähnelt.
        /// </summary>
        public static string CuesheetTracks {
            get {
                return ResourceManager.GetString("CuesheetTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Culture set: ähnelt.
        /// </summary>
        public static string CultureSetting {
            get {
                return ResourceManager.GetString("CultureSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This track is played ähnelt.
        /// </summary>
        public static string CurrentTrackIsPlayed {
            get {
                return ResourceManager.GetString("CurrentTrackIsPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decline ähnelt.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete all tracks ähnelt.
        /// </summary>
        public static string DeleteAllTracks {
            get {
                return ResourceManager.GetString("DeleteAllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete current export profile ähnelt.
        /// </summary>
        public static string DeleteExportProfile {
            get {
                return ResourceManager.GetString("DeleteExportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete this track ähnelt.
        /// </summary>
        public static string DeleteTrackTooltip {
            get {
                return ResourceManager.GetString("DeleteTrackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please describe how the error occured:
        ///1.What were you trying to do?
        ///2.Does this error occure, if you try it again? ähnelt.
        /// </summary>
        public static string DescribeHowTheErrorOccured {
            get {
                return ResourceManager.GetString("DescribeHowTheErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donate for this project ähnelt.
        /// </summary>
        public static string DonateForThisProject {
            get {
                return ResourceManager.GetString("DonateForThisProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download cuesheet file ähnelt.
        /// </summary>
        public static string Downloadcuesheet {
            get {
                return ResourceManager.GetString("Downloadcuesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download export file ähnelt.
        /// </summary>
        public static string DownloadExport {
            get {
                return ResourceManager.GetString("DownloadExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drop input files here ähnelt.
        /// </summary>
        public static string DropFiles {
            get {
                return ResourceManager.GetString("DropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End ähnelt.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter audiofile here ähnelt.
        /// </summary>
        public static string Enteraudiofilehere {
            get {
                return ResourceManager.GetString("Enteraudiofilehere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the catalogue number of the cuesheet. Catalogue number is a 13 decimal digits number. ähnelt.
        /// </summary>
        public static string EnterCatalogueNumberHere {
            get {
                return ResourceManager.GetString("EnterCatalogueNumberHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter CD artist here ähnelt.
        /// </summary>
        public static string EnterCDartisthere {
            get {
                return ResourceManager.GetString("EnterCDartisthere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter CD title here ähnelt.
        /// </summary>
        public static string EnterCDtitlehere {
            get {
                return ResourceManager.GetString("EnterCDtitlehere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter name of file for export profile here ähnelt.
        /// </summary>
        public static string EnterExportProfileFilenameHere {
            get {
                return ResourceManager.GetString("EnterExportProfileFilenameHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter name of export profile here ähnelt.
        /// </summary>
        public static string EnterExportProfileNameHere {
            get {
                return ResourceManager.GetString("EnterExportProfileNameHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter scheme for export of footer here ähnelt.
        /// </summary>
        public static string EnterExportSchemeFooterHere {
            get {
                return ResourceManager.GetString("EnterExportSchemeFooterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter scheme for export of footer here. Each placeholder will be replaced by the placeholder value. Placeholder start and end with %. ähnelt.
        /// </summary>
        public static string EnterExportSchemeFooterHereTooltip {
            get {
                return ResourceManager.GetString("EnterExportSchemeFooterHereTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter scheme for export of header here ähnelt.
        /// </summary>
        public static string EnterExportSchemeHeadHere {
            get {
                return ResourceManager.GetString("EnterExportSchemeHeadHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter scheme for export of header here. Each placeholder will be replaced by the placeholder value. Placeholder start and end with %. ähnelt.
        /// </summary>
        public static string EnterExportSchemeHeadHereTooltip {
            get {
                return ResourceManager.GetString("EnterExportSchemeHeadHereTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter scheme for export of tracks here ähnelt.
        /// </summary>
        public static string EnterExportSchemeTrackHere {
            get {
                return ResourceManager.GetString("EnterExportSchemeTrackHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter scheme for export of tracks here. Each placeholder will be replaced by the placeholder value. Placeholder start and end with %. ähnelt.
        /// </summary>
        public static string EnterExportSchemeTrackHereTooltip {
            get {
                return ResourceManager.GetString("EnterExportSchemeTrackHereTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter textscheme for import here ähnelt.
        /// </summary>
        public static string EnterTextImportSchemeHere {
            get {
                return ResourceManager.GetString("EnterTextImportSchemeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter textscheme for import here. Identification will be done using regular expressions. ähnelt.
        /// </summary>
        public static string EnterTextImportSchemeTooltip {
            get {
                return ResourceManager.GetString("EnterTextImportSchemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured during text import ähnelt.
        /// </summary>
        public static string ErrorDuringTextImport {
            get {
                return ResourceManager.GetString("ErrorDuringTextImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error report ähnelt.
        /// </summary>
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Errors ähnelt.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception ähnelt.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An internal exception has occured and the application has stopped working. Please fill out the error report and send it to the developer, so the Bug can get fixed. ähnelt.
        /// </summary>
        public static string ExceptionOccuredPleaseFillErrorReport {
            get {
                return ResourceManager.GetString("ExceptionOccuredPleaseFillErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename ähnelt.
        /// </summary>
        public static string ExportProfileFilename {
            get {
                return ResourceManager.GetString("ExportProfileFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export profile is not exportable. Please check the validation errors and fix them in order to download the export. ähnelt.
        /// </summary>
        public static string ExportProfileIsNotExportable {
            get {
                return ResourceManager.GetString("ExportProfileIsNotExportable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ExportProfileName {
            get {
                return ResourceManager.GetString("ExportProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Profiles ähnelt.
        /// </summary>
        public static string ExportProfiles {
            get {
                return ResourceManager.GetString("ExportProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scheme footer ähnelt.
        /// </summary>
        public static string ExportProfileSchemeFooter {
            get {
                return ResourceManager.GetString("ExportProfileSchemeFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export profile footer scheme validation errors ähnelt.
        /// </summary>
        public static string ExportProfileSchemeFooterValidationErrors {
            get {
                return ResourceManager.GetString("ExportProfileSchemeFooterValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scheme header ähnelt.
        /// </summary>
        public static string ExportProfileSchemeHead {
            get {
                return ResourceManager.GetString("ExportProfileSchemeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export profile head scheme validation errors ähnelt.
        /// </summary>
        public static string ExportProfileSchemeHeadValidationErrors {
            get {
                return ResourceManager.GetString("ExportProfileSchemeHeadValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scheme tracks ähnelt.
        /// </summary>
        public static string ExportProfileSchemeTrack {
            get {
                return ResourceManager.GetString("ExportProfileSchemeTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export profile track scheme validation errors ähnelt.
        /// </summary>
        public static string ExportProfileSchemeTrackValidationErrors {
            get {
                return ResourceManager.GetString("ExportProfileSchemeTrackValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export result ähnelt.
        /// </summary>
        public static string ExportResult {
            get {
                return ResourceManager.GetString("ExportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Features ähnelt.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ul&gt;&lt;li&gt;Validation for all data&lt;/li&gt;&lt;li&gt;Textimport&lt;/li&gt;&lt;li&gt;Cuesheet import&lt;/li&gt;&lt;li&gt;Different export profiles (XML/CSV,Text, etc)&lt;/li&gt;&lt;li&gt;Audio playback&lt;/li&gt;&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string FeaturesText {
            get {
                return ResourceManager.GetString("FeaturesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &quot;{0}&quot; you supplied does not match the requested operation: &quot;{1}&quot;. Please provide a valid file! ähnelt.
        /// </summary>
        public static string FileHasInvalidMimeType {
            get {
                return ResourceManager.GetString("FileHasInvalidMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Begin is not valid (must be equal or greater than 00:00:00). Please enter a valid time. ähnelt.
        /// </summary>
        public static string HasInvalidBegin {
            get {
                return ResourceManager.GetString("HasInvalidBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End is not valid (must be equal or greater than 00:00:00). Please enter a valid time. ähnelt.
        /// </summary>
        public static string HasInvalidEnd {
            get {
                return ResourceManager.GetString("HasInvalidEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} has invalid length({1})! ähnelt.
        /// </summary>
        public static string HasInvalidLength {
            get {
                return ResourceManager.GetString("HasInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} has invalid value! ähnelt.
        /// </summary>
        public static string HasInvalidValue {
            get {
                return ResourceManager.GetString("HasInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} has no value! ähnelt.
        /// </summary>
        public static string HasNoValue {
            get {
                return ResourceManager.GetString("HasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import a cuesheet file and extract all data from it ähnelt.
        /// </summary>
        public static string ImportCuesheetTooltip {
            get {
                return ResourceManager.GetString("ImportCuesheetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import files ähnelt.
        /// </summary>
        public static string ImportFiles {
            get {
                return ResourceManager.GetString("ImportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import is not possible due to errors. Please check import errors! ähnelt.
        /// </summary>
        public static string ImportNotPossible {
            get {
                return ResourceManager.GetString("ImportNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import of cuesheet files ähnelt.
        /// </summary>
        public static string ImportOfCuesheetFiles {
            get {
                return ResourceManager.GetString("ImportOfCuesheetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can import already finished cuesheets and edit them. It doesn&apos;t matter if the cuesheet is written by this program or another one. Only the format of file matters. To import a cuesheet, simply drag it from your file system to the dropzone or manually select it via file system chooser:&lt;br/&gt;&lt;img src=&quot;images/ImportCuesheet1.png&quot;/&gt;&lt;br/&gt;A confirmation will be required, since all of the exisiting data will be replaced.&lt;br/&gt;&lt;img src=&quot;images/ImportCuesheet2.png&quot;/&gt;&lt;br/&gt;Confirming this dialog will import the cuesh [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string ImportOfCuesheetFilesText {
            get {
                return ResourceManager.GetString("ImportOfCuesheetFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import of files ähnelt.
        /// </summary>
        public static string ImportOfFiles {
            get {
                return ResourceManager.GetString("ImportOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import of text files ähnelt.
        /// </summary>
        public static string ImportOfTextFiles {
            get {
                return ResourceManager.GetString("ImportOfTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can import plain text files and analyse the content of each line by simple regular expressions. A simple sample textfile can be found &lt;a href=&quot;/samples/Sample_Inputfile.txt&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;.&lt;br/&gt;&lt;img src=&quot;images/SampleInputfile1.png&quot;/&gt;&lt;br/&gt;Each line represents a track and every detail can be extracted from the line. First information that can be found is the track artist, followed by &quot; - &quot; and then track title. Afterwards some tabs come and you can see information about the track end time. So i [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string ImportOfTextFilesText {
            get {
                return ResourceManager.GetString("ImportOfTextFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import a plain text file and extract data via regular expressions ähnelt.
        /// </summary>
        public static string ImportTextfileTooltip {
            get {
                return ResourceManager.GetString("ImportTextfileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Introduction ähnelt.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid file ähnelt.
        /// </summary>
        public static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length ähnelt.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length has no value! Please check Begin and End. ähnelt.
        /// </summary>
        public static string LengthHasNoValue {
            get {
                return ResourceManager.GetString("LengthHasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licence ähnelt.
        /// </summary>
        public static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move this track one position down ähnelt.
        /// </summary>
        public static string MoveTrackDownTooltip {
            get {
                return ResourceManager.GetString("MoveTrackDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move this track one position up ähnelt.
        /// </summary>
        public static string MoveTrackUpTooltip {
            get {
                return ResourceManager.GetString("MoveTrackUpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Once you submit the error report, you will get redirected to formspree.io. This is normal, since the error report will get send by them. Afterwards you can go back in browser history and use the application again. Thanks for your help! ähnelt.
        /// </summary>
        public static string OnceYouSubmitTheErrorReport {
            get {
                return ResourceManager.GetString("OnceYouSubmitTheErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display Export Profiles ähnelt.
        /// </summary>
        public static string OpenExportProfilesDialog {
            get {
                return ResourceManager.GetString("OpenExportProfilesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jump playback position to next track beginning ähnelt.
        /// </summary>
        public static string PlayNextTrackTooltip {
            get {
                return ResourceManager.GetString("PlayNextTrackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jump playback position to previous track beginning ähnelt.
        /// </summary>
        public static string PlayPreviousTrackTooltip {
            get {
                return ResourceManager.GetString("PlayPreviousTrackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please check processing hints for errors. Otherwise the file is not exportable. ähnelt.
        /// </summary>
        public static string PleaseCheckProcessingHints {
            get {
                return ResourceManager.GetString("PleaseCheckProcessingHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position ähnelt.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processing hints ähnelt.
        /// </summary>
        public static string ProcessingHints {
            get {
                return ResourceManager.GetString("ProcessingHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick links ähnelt.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset cuesheet ähnelt.
        /// </summary>
        public static string ResetCuesheet {
            get {
                return ResourceManager.GetString("ResetCuesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart complete application ähnelt.
        /// </summary>
        public static string RestartCompleteApplication {
            get {
                return ResourceManager.GetString("RestartCompleteApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scheme contains placeholder that can not be resolved! ähnelt.
        /// </summary>
        public static string SchemeContainsPlaceholdersThatCanNotBeSolved {
            get {
                return ResourceManager.GetString("SchemeContainsPlaceholdersThatCanNotBeSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scroll to top ähnelt.
        /// </summary>
        public static string ScrollToTop {
            get {
                return ResourceManager.GetString("ScrollToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select export profile ähnelt.
        /// </summary>
        public static string SelectExportProfile {
            get {
                return ResourceManager.GetString("SelectExportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select placeholder ähnelt.
        /// </summary>
        public static string SelectPlaceholder {
            get {
                return ResourceManager.GetString("SelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send ähnelt.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start playing this track ähnelt.
        /// </summary>
        public static string StartPlaybackThisTrack {
            get {
                return ResourceManager.GetString("StartPlaybackThisTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start import of tracks ähnelt.
        /// </summary>
        public static string StartTrackImport {
            get {
                return ResourceManager.GetString("StartTrackImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfile ähnelt.
        /// </summary>
        public static string Textfile {
            get {
                return ResourceManager.GetString("Textfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfile import ähnelt.
        /// </summary>
        public static string TextfileImport {
            get {
                return ResourceManager.GetString("TextfileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import textfile assistant ähnelt.
        /// </summary>
        public static string TextImportAssistance {
            get {
                return ResourceManager.GetString("TextImportAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Textscheme ähnelt.
        /// </summary>
        public static string TextImportScheme {
            get {
                return ResourceManager.GetString("TextImportScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track {0} has invalid Value {1} ({2})! ähnelt.
        /// </summary>
        public static string TrackHasInvalidValue {
            get {
                return ResourceManager.GetString("TrackHasInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controls ähnelt.
        /// </summary>
        public static string TrackTableControls {
            get {
                return ResourceManager.GetString("TrackTableControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation ähnelt.
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AudioCuesheetEditor works with a validation model and evaluates every input. Currently there are 2 types of validation: Warning and Error. Warnings are validationmessages, that might be important for you, but don&apos;t block functions. Errors are validationmessages that need to be corrected (like tracks with invalid times). Validation messages are displayed on the right with link to the corresponding fields.&lt;br/&gt;&lt;img src=&quot;images/Validation1.png&quot;/&gt; ähnelt.
        /// </summary>
        public static string ValidationText {
            get {
                return ResourceManager.GetString("ValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnings ähnelt.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What is AudioCuesheetEditor? ähnelt.
        /// </summary>
        public static string WhatIsAudioCuesheetEditor {
            get {
                return ResourceManager.GetString("WhatIsAudioCuesheetEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;strong&gt;AudioCuesheet&lt;/strong&gt; is a web application for writting audio cuesheet files. Audio cuesheet files are little text files which provide information about the provided audio file like artist, name, etc. AudioCuesheetEditor is an application that helps you writting valid cuesheet files by checking and validation input data. You can also import data from files to minimize your work. ähnelt.
        /// </summary>
        public static string WhatIsAudioCuesheetEditorText {
            get {
                return ResourceManager.GetString("WhatIsAudioCuesheetEditorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Written by Sven Baus (&lt;a href=&apos;mailto&amp;#58;%73&amp;#46;ba&amp;#117;%7386%4&amp;#48;g&amp;#37;6D%78&amp;#46;ne%&amp;#55;4&apos;&gt;s&amp;#46;baus8&amp;#54;&amp;#64;&amp;#103;mx&amp;#46;net&lt;/a&gt;) ähnelt.
        /// </summary>
        public static string WrittenBy {
            get {
                return ResourceManager.GetString("WrittenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You selected or dropped a file (&quot;{0}&quot;) that can not be processed. Please select only valid files (Textfiles, Cuesheets, Audiofiles)! ähnelt.
        /// </summary>
        public static string YouDroppedAFileThatCanNotBeProcessed {
            get {
                return ResourceManager.GetString("YouDroppedAFileThatCanNotBeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your emailaddress (optional) ähnelt.
        /// </summary>
        public static string YourEmailAddress {
            get {
                return ResourceManager.GetString("YourEmailAddress", resourceCulture);
            }
        }
    }
}
