using AudioCuesheetEditor.End2EndTests.Models;
using Microsoft.Playwright;
using System.Text.RegularExpressions;
using static System.Net.Mime.MediaTypeNames;

namespace AudioCuesheetEditor.End2EndTests.Tests
{
    [TestClass]
    public class ImportTest : PlaywrightTestBase
    {
        [TestMethod]
        public async Task Import_ShouldImportTracks_WhenUsingSampleInputfile()
        {
            var importView = new ImportView(TestPage);
            var detailView = new DetailView(TestPage);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Sample_Inputfile.txt");
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Sort Column options Artist Sort Column options Title Sort Column options Begin Sort Column options End Sort Column options Length Sort Column options Status"":
      - columnheader:
        - checkbox
      - columnheader ""# Sort Column options"":
        - text: ""#""
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Artist Sort Column options"":
        - text: Artist
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Title Sort Column options"":
        - text: Title
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Begin Sort Column options"":
        - text: Begin
        - button ""Sort""
        - button ""Column options""
      - columnheader ""End Sort Column options"":
        - text: End
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Length Sort Column options"":
        - text: Length
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Status""
  - rowgroup:
    - row ""Increment Decrement Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Increment Decrement Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
      - cell:
        - button
  - rowgroup:
    - row");
            await Expect(detailView.AudiofileInput).ToBeEmptyAsync();
            await importView.GotoAsync();
            await Expect(TestPage.GetByText("PreviousNext")).ToBeVisibleAsync();
        }

        [TestMethod]
        public async Task Import_ShouldBeEditable_WhenEditingTrack()
        {
            var importView = new ImportView(TestPage);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Sample_Inputfile.txt");
            await importView.SelectTracksAsync([5]);
            await importView.EditTracksModalAsync("Sample Title Edited 5");
            await importView.CompleteImportAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Sort Column options Artist Sort Column options Title Sort Column options Begin Sort Column options End Sort Column options Length Sort Column options Status"":
      - columnheader:
        - checkbox
      - columnheader ""# Sort Column options"":
        - text: ""#""
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Artist Sort Column options"":
        - text: Artist
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Title Sort Column options"":
        - text: Title
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Begin Sort Column options"":
        - text: Begin
        - button ""Sort""
        - button ""Column options""
      - columnheader ""End Sort Column options"":
        - text: End
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Length Sort Column options"":
        - text: Length
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Status""
  - rowgroup:
    - row ""Increment Decrement Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell
    - row ""Increment Decrement Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 5 Clear Sample Title Edited 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title Edited 5 Clear"":
        - textbox: Sample Title Edited 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
      - cell:
        - button
    - row ""Increment Decrement Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
      - cell:
        - button
  - rowgroup:
    - row");
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WithSpecialTextfile()
        {
            var importView = new ImportView(TestPage);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Textimport-Bug-#54.txt");
            await importView.SwitchImportProfileAsync("Textfile (just track data)");
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync("- table:\n  - rowgroup:\n    - row \"# Sort Column options Artist Sort Column options Title Sort Column options Begin Sort Column options End Sort Column options Length Sort Column options\":\n      - columnheader:\n        - checkbox\n      - columnheader \"# Sort Column options\":\n        - button \"Sort\"\n        - button \"Column options\"\n      - columnheader \"Artist Sort Column options\":\n        - button \"Sort\"\n        - button \"Column options\"\n      - columnheader \"Title Sort Column options\":\n        - button \"Sort\"\n        - button \"Column options\"\n      - columnheader \"Begin Sort Column options\":\n        - button \"Sort\"\n        - button \"Column options\"\n      - columnheader \"End Sort Column options\":\n        - button \"Sort\"\n        - button \"Column options\"\n      - columnheader \"Length Sort Column options\":\n        - button \"Sort\"\n        - button \"Column options\"\n  - rowgroup:\n    - row /Increment Decrement Adriatique Clear X\\. Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: \"1\"\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Adriatique Clear\":\n        - textbox: Adriatique\n        - button \"Clear\"\n        - button\n      - cell \"X. Clear\":\n        - textbox: X.\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Third Harmony Clear Fears And Dreams \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: \"2\"\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Third Harmony Clear\":\n        - textbox: Third Harmony\n        - button \"Clear\"\n        - button\n      - cell \"Fears And Dreams (Original Mix) Clear\":\n        - textbox: Fears And Dreams (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Dele Sosimi Afrobeat Orchestra Clear Too Much Information \\(Laolu Remix; Edit\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: \"3\"\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Dele Sosimi Afrobeat Orchestra Clear\":\n        - textbox: Dele Sosimi Afrobeat Orchestra\n        - button \"Clear\"\n        - button\n      - cell \"Too Much Information (Laolu Remix; Edit) Clear\":\n        - textbox: Too Much Information (Laolu Remix; Edit)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Edem, Govan Clear Ankh \\(Onetwo MX Remix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: \"4\"\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Edem, Govan Clear\":\n        - textbox: Edem, Govan\n        - button \"Clear\"\n        - button\n      - cell \"Ankh (Onetwo MX Remix) Clear\":\n        - textbox: Ankh (Onetwo MX Remix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Jody Wisternoff Clear For All Time \\(feat\\. Hendrik Burkhard\\) \\(Extended Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: \"5\"\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Jody Wisternoff Clear\":\n        - textbox: Jody Wisternoff\n        - button \"Clear\"\n        - button\n      - cell \"For All Time (feat. Hendrik Burkhard) (Extended Mix) Clear\":\n        - textbox: For All Time (feat. Hendrik Burkhard) (Extended Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Einmusik Clear Bead \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: \"6\"\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Einmusik Clear\":\n        - textbox: Einmusik\n        - button \"Clear\"\n        - button\n      - cell \"Bead (Original Mix) Clear\":\n        - textbox: Bead (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Sebastien Leger Clear La Danse du Scorpion Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: \"7\"\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Sebastien Leger Clear\":\n        - textbox: Sebastien Leger\n        - button \"Clear\"\n        - button\n      - cell \"La Danse du Scorpion Clear\":\n        - textbox: La Danse du Scorpion\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Paul Thomas & Solid Stone Clear La Bombo \\(Solid Stone Remix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: \"8\"\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Paul Thomas & Solid Stone Clear\":\n        - textbox: Paul Thomas & Solid Stone\n        - button \"Clear\"\n        - button\n      - cell \"La Bombo (Solid Stone Remix) Clear\":\n        - textbox: La Bombo (Solid Stone Remix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement GusGus Clear Crossfade \\(Maceo Plex Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: \"9\"\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"GusGus Clear\":\n        - textbox: GusGus\n        - button \"Clear\"\n        - button\n      - cell \"Crossfade (Maceo Plex Mix) Clear\":\n        - textbox: Crossfade (Maceo Plex Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Klangkarussell Clear Time \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Klangkarussell Clear\":\n        - textbox: Klangkarussell\n        - button \"Clear\"\n        - button\n      - cell \"Time (Original Mix) Clear\":\n        - textbox: Time (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Anysense & Un:said Clear Missing Path \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Anysense & Un:said Clear\":\n        - textbox: Anysense & Un:said\n        - button \"Clear\"\n        - button\n      - cell \"Missing Path (Original Mix) Clear\":\n        - textbox: Missing Path (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Space Food Clear Bombay Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Space Food Clear\":\n        - textbox: Space Food\n        - button \"Clear\"\n        - button\n      - cell \"Bombay Clear\":\n        - textbox: Bombay\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement SHDW & Obscure Shape Clear Wächter der Nacht \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"SHDW & Obscure Shape Clear\":\n        - textbox: SHDW & Obscure Shape\n        - button \"Clear\"\n        - button\n      - cell \"Wächter der Nacht (Original Mix) Clear\":\n        - textbox: Wächter der Nacht (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement HOSH Clear Karma Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"HOSH Clear\":\n        - textbox: HOSH\n        - button \"Clear\"\n        - button\n      - cell \"Karma Clear\":\n        - textbox: Karma\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Alexey Union Clear Olympia \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Alexey Union Clear\":\n        - textbox: Alexey Union\n        - button \"Clear\"\n        - button\n      - cell \"Olympia (Original Mix) Clear\":\n        - textbox: Olympia (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Paul Taylor Clear Afterglow Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Paul Taylor Clear\":\n        - textbox: Paul Taylor\n        - button \"Clear\"\n        - button\n      - cell \"Afterglow Clear\":\n        - textbox: Afterglow\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Philter Clear Stranger Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Philter Clear\":\n        - textbox: Philter\n        - button \"Clear\"\n        - button\n      - cell \"Stranger Clear\":\n        - textbox: Stranger\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Skizologic Clear Hypersphere \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Skizologic Clear\":\n        - textbox: Skizologic\n        - button \"Clear\"\n        - button\n      - cell \"Hypersphere (Original Mix) Clear\":\n        - textbox: Hypersphere (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Thomas Schumacher, Caitlin Clear All of You \\(Remix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Thomas Schumacher, Caitlin Clear\":\n        - textbox: Thomas Schumacher, Caitlin\n        - button \"Clear\"\n        - button\n      - cell \"All of You (Remix) Clear\":\n        - textbox: All of You (Remix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement A\\. Skomoroh Clear White Horse Conquest \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"A. Skomoroh Clear\":\n        - textbox: A. Skomoroh\n        - button \"Clear\"\n        - button\n      - cell \"White Horse Conquest (Original Mix) Clear\":\n        - textbox: White Horse Conquest (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Patrik Berg Clear Bright \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Patrik Berg Clear\":\n        - textbox: Patrik Berg\n        - button \"Clear\"\n        - button\n      - cell \"Bright (Original Mix) Clear\":\n        - textbox: Bright (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Hidden Empire Clear Bengal Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Hidden Empire Clear\":\n        - textbox: Hidden Empire\n        - button \"Clear\"\n        - button\n      - cell \"Bengal Clear\":\n        - textbox: Bengal\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Mario Ochoa Clear Levitate Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Mario Ochoa Clear\":\n        - textbox: Mario Ochoa\n        - button \"Clear\"\n        - button\n      - cell \"Levitate Clear\":\n        - textbox: Levitate\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Raul Facio Clear Eyes Wide Shut \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Raul Facio Clear\":\n        - textbox: Raul Facio\n        - button \"Clear\"\n        - button\n      - cell \"Eyes Wide Shut (Original Mix) Clear\":\n        - textbox: Eyes Wide Shut (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Soolver Clear Regular \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Soolver Clear\":\n        - textbox: Soolver\n        - button \"Clear\"\n        - button\n      - cell \"Regular (Original Mix) Clear\":\n        - textbox: Regular (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Weska Clear EQ64 \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Weska Clear\":\n        - textbox: Weska\n        - button \"Clear\"\n        - button\n      - cell \"EQ64 (Original Mix) Clear\":\n        - textbox: EQ64 (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Tempo Giusto Clear The Fall \\(Extended Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Tempo Giusto Clear\":\n        - textbox: Tempo Giusto\n        - button \"Clear\"\n        - button\n      - cell \"The Fall (Extended Mix) Clear\":\n        - textbox: The Fall (Extended Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Vlind & Asteroid & Gary Leroy Clear Trinity \\(Extended Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Vlind & Asteroid & Gary Leroy Clear\":\n        - textbox: Vlind & Asteroid & Gary Leroy\n        - button \"Clear\"\n        - button\n      - cell \"Trinity (Extended Mix) Clear\":\n        - textbox: Trinity (Extended Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Astral Legacy Clear Vaveyla \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Astral Legacy Clear\":\n        - textbox: Astral Legacy\n        - button \"Clear\"\n        - button\n      - cell \"Vaveyla (Original Mix) Clear\":\n        - textbox: Vaveyla (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Gerrox Clear Chakra \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Gerrox Clear\":\n        - textbox: Gerrox\n        - button \"Clear\"\n        - button\n      - cell \"Chakra (Original Mix) Clear\":\n        - textbox: Chakra (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Charlotte De Witte Clear Pattern Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Charlotte De Witte Clear\":\n        - textbox: Charlotte De Witte\n        - button \"Clear\"\n        - button\n      - cell \"Pattern Clear\":\n        - textbox: Pattern\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Space Food Clear Amabey Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Space Food Clear\":\n        - textbox: Space Food\n        - button \"Clear\"\n        - button\n      - cell \"Amabey Clear\":\n        - textbox: Amabey\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement ARTBAT Clear Papilion \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"ARTBAT Clear\":\n        - textbox: ARTBAT\n        - button \"Clear\"\n        - button\n      - cell \"Papilion (Original Mix) Clear\":\n        - textbox: Papilion (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement PETER PAHN Clear Enjoy Infinity \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"PETER PAHN Clear\":\n        - textbox: PETER PAHN\n        - button \"Clear\"\n        - button\n      - cell \"Enjoy Infinity (Original Mix) Clear\":\n        - textbox: Enjoy Infinity (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Solitek Clear Instinct \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Solitek Clear\":\n        - textbox: Solitek\n        - button \"Clear\"\n        - button\n      - cell \"Instinct (Original Mix) Clear\":\n        - textbox: Instinct (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Veerus Clear Heavy Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Veerus Clear\":\n        - textbox: Veerus\n        - button \"Clear\"\n        - button\n      - cell \"Heavy Clear\":\n        - textbox: Heavy\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Secret Cinema & Reinier Zonneveld Clear Pain Thing \\(Original Mix\\) Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Secret Cinema & Reinier Zonneveld Clear\":\n        - textbox: Secret Cinema & Reinier Zonneveld\n        - button \"Clear\"\n        - button\n      - cell \"Pain Thing (Original Mix) Clear\":\n        - textbox: Pain Thing (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Amelie Lens Clear Hypnotized Clear \\d+:\\d+:\\d+ \\d+:\\d+:\\d+ \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Amelie Lens Clear\":\n        - textbox: Amelie Lens\n        - button \"Clear\"\n        - button\n      - cell \"Hypnotized Clear\":\n        - textbox: Hypnotized\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n    - row /Increment Decrement Nikolay Kirov Clear Chasing the Sun \\(Original Mix\\) Clear \\d+:\\d+:\\d+/:\n      - cell:\n        - checkbox\n      - cell \"Increment Decrement\":\n        - spinbutton: /\\d+/\n        - button \"Increment\"\n        - button \"Decrement\"\n      - cell \"Nikolay Kirov Clear\":\n        - textbox: Nikolay Kirov\n        - button \"Clear\"\n        - button\n      - cell \"Chasing the Sun (Original Mix) Clear\":\n        - textbox: Chasing the Sun (Original Mix)\n        - button \"Clear\"\n        - button\n      - cell /\\d+:\\d+:\\d+/:\n        - textbox: /\\d+:\\d+:\\d+/\n      - cell:\n        - textbox\n      - cell:\n        - textbox\n  - rowgroup:\n    - row");
        }

        [TestMethod]
        public async Task Import_ShouldImportTracks_WhenUsingSampleInputfile2()
        {
            var importView = new ImportView(TestPage);
            await importView.GotoAsync();
            await importView.ImportFileAsync("Sample_Inputfile2.txt");
            await importView.ClearSchemesAsync(true);
            await Expect(importView.CuesheetArtistInput).ToBeEmptyAsync();
            await Expect(importView.CuesheetTitleInput).ToBeEmptyAsync();
            await Expect(TestPage.GetByRole(AriaRole.Table)).ToMatchAriaSnapshotAsync(@"- table:
  - rowgroup:
    - row ""# Sort Column options Artist Sort Column options Title Sort Column options Begin Sort Column options End Sort Column options Length Sort Column options"":
      - columnheader:
        - checkbox
      - columnheader ""# Sort Column options"":
        - text: ""#""
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Artist Sort Column options"":
        - text: Artist
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Title Sort Column options"":
        - text: Title
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Begin Sort Column options"":
        - text: Begin
        - button ""Sort""
        - button ""Column options""
      - columnheader ""End Sort Column options"":
        - text: End
        - button ""Sort""
        - button ""Column options""
      - columnheader ""Length Sort Column options"":
        - text: Length
        - button ""Sort""
        - button ""Column options""
  - rowgroup:
    - row ""Increment Decrement Sample Artist 1 Clear Sample Title 1 Clear 00:00:00 00:05:00 00:05:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""1""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 1 Clear"":
        - textbox: Sample Artist 1
        - button ""Clear""
        - button
      - cell ""Sample Title 1 Clear"":
        - textbox: Sample Title 1
        - button ""Clear""
        - button
      - cell ""00:00:00"":
        - textbox: 00:00:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:05:00"":
        - textbox: 00:05:00
    - row ""Increment Decrement Sample Artist 2 Clear Sample Title 2 Clear 00:05:00 00:09:23 00:04:23"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""2""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 2 Clear"":
        - textbox: Sample Artist 2
        - button ""Clear""
        - button
      - cell ""Sample Title 2 Clear"":
        - textbox: Sample Title 2
        - button ""Clear""
        - button
      - cell ""00:05:00"":
        - textbox: 00:05:00
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:04:23"":
        - textbox: 00:04:23
    - row ""Increment Decrement Sample Artist 3 Clear Sample Title 3 Clear 00:09:23 00:15:54 00:06:31"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""3""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 3 Clear"":
        - textbox: Sample Artist 3
        - button ""Clear""
        - button
      - cell ""Sample Title 3 Clear"":
        - textbox: Sample Title 3
        - button ""Clear""
        - button
      - cell ""00:09:23"":
        - textbox: 00:09:23
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:06:31"":
        - textbox: 00:06:31
    - row ""Increment Decrement Sample Artist 4 Clear Sample Title 4 Clear 00:15:54 00:20:13 00:04:19"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""4""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 4 Clear"":
        - textbox: Sample Artist 4
        - button ""Clear""
        - button
      - cell ""Sample Title 4 Clear"":
        - textbox: Sample Title 4
        - button ""Clear""
        - button
      - cell ""00:15:54"":
        - textbox: 00:15:54
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:04:19"":
        - textbox: 00:04:19
    - row ""Increment Decrement Sample Artist 5 Clear Sample Title 5 Clear 00:20:13 00:24:54 00:04:41"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""5""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 5 Clear"":
        - textbox: Sample Artist 5
        - button ""Clear""
        - button
      - cell ""Sample Title 5 Clear"":
        - textbox: Sample Title 5
        - button ""Clear""
        - button
      - cell ""00:20:13"":
        - textbox: 00:20:13
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:04:41"":
        - textbox: 00:04:41
    - row ""Increment Decrement Sample Artist 6 Clear Sample Title 6 Clear 00:24:54 00:31:54 00:07:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""6""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 6 Clear"":
        - textbox: Sample Artist 6
        - button ""Clear""
        - button
      - cell ""Sample Title 6 Clear"":
        - textbox: Sample Title 6
        - button ""Clear""
        - button
      - cell ""00:24:54"":
        - textbox: 00:24:54
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:07:00"":
        - textbox: 00:07:00
    - row ""Increment Decrement Sample Artist 7 Clear Sample Title 7 Clear 00:31:54 00:45:54 00:14:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""7""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 7 Clear"":
        - textbox: Sample Artist 7
        - button ""Clear""
        - button
      - cell ""Sample Title 7 Clear"":
        - textbox: Sample Title 7
        - button ""Clear""
        - button
      - cell ""00:31:54"":
        - textbox: 00:31:54
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""00:14:00"":
        - textbox: 00:14:00
    - row ""Increment Decrement Sample Artist 8 Clear Sample Title 8 Clear 00:45:54 01:15:54 00:30:00"":
      - cell:
        - checkbox
      - cell ""Increment Decrement"":
        - spinbutton: ""8""
        - button ""Increment""
        - button ""Decrement""
      - cell ""Sample Artist 8 Clear"":
        - textbox: Sample Artist 8
        - button ""Clear""
        - button
      - cell ""Sample Title 8 Clear"":
        - textbox: Sample Title 8
        - button ""Clear""
        - button
      - cell ""00:45:54"":
        - textbox: 00:45:54
      - cell ""01:15:54"":
        - textbox: 01:15:54
      - cell ""00:30:00"":
        - textbox: 00:30:00
  - rowgroup:
    - row");
        }
    }
}
