name: Deploy to GitHub Pages

# Run workflow on every push to the production branch
on:
  push:
    branches: [ production ]

jobs:    
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the production branch
    - uses: actions/checkout@v2
      with:
        ref: production
    
    # sets up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.102'
      
    # Only publish when unit tests are ok
    - name: Run Unit Tests
      run: dotnet test

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish --no-restore AudioCuesheetEditor/AudioCuesheetEditor.csproj -c Release -o release --nologo
    
    # changes the base-tag in index.html from '/' to 'AudioCuesheetEditor' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to AudioCuesheetEditor
      run: sed -i 's/<base href="\/" \/>/<base href="\/AudioCuesheetEditor\/" \/>/g' release/wwwroot/index.html
      
    # changes the favicon in index.html from '/' to 'AudioCuesheetEditor' to match GitHub Pages repository subdirectory
    - name: Change favicon in index.html from / to AudioCuesheetEditor
      run: sed -i 's/<link rel="shortcut icon" type="image\/x-icon" href="favicon.ico">/<link rel="shortcut icon" type="image\/x-icon" href="\/AudioCuesheetEditor\/favicon.ico">/g' release/wwwroot/index.html
      
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
