name: Run unit tests

# Run workflow on every push to the master branch
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:    
  run-unit-tests:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the production branch
    - uses: actions/checkout@v2
    
    # sets up .NET
    # version can be found here https://dotnet.microsoft.com/en-us/download/dotnet/6.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.401'
      
    # Only publish when unit tests are ok
    - name: Run Unit Tests
      run: dotnet test
