name: Run unit tests

# Run workflow on every push to the master branch
on:
  push:
  pull_request:

jobs:    
  run-unit-tests:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    
    # sets up .NET
    # version can be found here https://dotnet.microsoft.com/en-us/download/dotnet/7.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.101'
    
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools-net7
      
    # Only publish when unit tests are ok
    - name: Run Unit Tests
      run: dotnet test
