name: Run unit tests

# Run workflow on every push to the master branch
on:
  push:
  pull_request:

jobs:    
  run-unit-tests:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    
    # sets up .NET
    # version can be found here https://dotnet.microsoft.com/en-us/download/dotnet/6.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '7.0.101'
    
    - name: Restore workload
      run: dotnet workload restore
      
    # Only publish when unit tests are ok
    - name: Run Unit Tests
      run: dotnet test
